deploy/deploy.go
=> quick fix for issue #25

app/sign/client.go, app/stamp/server.go, deploy/deploy_test.go, deploy/simulation/test_naive_multi.toml, deploy/simulation/test_ntree_multi.toml, deploy/simulation/test_shamir_multi.toml, deploy/simulation/test_sign_multi.toml, deploy/simulation/test_stamp_multi.toml
Wrote test for deploy. This should pass before we can merge replace_wallclock_with_rusage
=> testing for deploy

deploy/platform/deterlab.go, deploy/platform/localhost.go, deploy/platform/platform.go
So that we can now give additionals arguments to the apps (will be used to remove the "static" port nubmer of monitor later)
=> added optional args to start

lib/monitor/stats.go
Sets default discarding of
```
round,verify
```
=> added default-discard of round,verify

lib/monitor/stats.go
Includes the default discard-line
=> Quickfix discard

app/conode/README.md
=> Revert "Dev readme"

app/conode/README.md
=> redo of dev_readme

deploy/deploy.go, deploy/platform/deterlab/users/users.go
Does two things:
- adds -clean flag
- no double-cleanup when running simulations
=> added -clean flag to deploy to only cleanup the platform

deploy/platform/platform.go
=> re-arrangement - most important structures on top

README.md, app/conode/README.md, app/conode/check.go, app/conode/config.go, app/conode/conode.go, app/conode/exit.go, app/conode/run.go, app/conode/validate.go
Revision of the READMEs [cothority/README.md](https://github.com/DeDiS/cothority/blob/development/README.md) and [cothority/app/conode/README.md](https://github.com/DeDiS/cothority/blob/development/app/conode/README.md). Includes also explanations how to properly handle passphrase-protected SSH keys (see issue #93).
=> Revise READMEs

app/naive/server.go, app/ntree/sign.go, app/shamir/server.go, app/sign/server.go, app/stamp/stamp.go, deploy/deploy.go, lib/monitor/measure.go, lib/monitor/monitor.go, lib/monitor/monitor_test.go, lib/monitor/stats.go, lib/monitor/stats_test.go
monitor now is used iwth a structure for more control on the concurrency. Test added + working (included the TestMonitor !)
=> reworked monitor + test working

app/skeleton/skeleton.go, deploy/platform/deterlab.go, deploy/platform/localhost.go, deploy/simulation/skeleton.toml, lib/app/config_skeleton.go, lib/conode/peer.go
This is the basic code to have when one wants to implement a new app using cothority trees. Note this app is to use with deploy/ lib, not as a standalone app. In this way, we can easily deploy a new app and make measurements and have nice graphs !
=> Skeleton app

app/naive/naive.go, app/ntree/ntree.go, app/shamir/peer.go, app/shamir/server.go, app/shamir/shamir.go, app/stamp/client_funcs.go, app/stamp/stamper.go, deploy/deploy.go, lib/app/app.go, lib/cliutils/utils.go, lib/coconet/goconn.go, lib/coconet/gohost.go, lib/coconet/tcphost.go, lib/coconet/view.go, lib/dbg/debug_lvl.go, lib/logutils/logutils.go, lib/sign/nodeprotocol.go, lib/sign/nodeutils.go
=> log calls to dbg

lib/hashid/hashid.go, lib/tree/peer.go, lib/tree/peer_test.go, lib/tree/tree.go, lib/tree/tree_test.go
Some refactoring done on Tree + peer + PeerList 
* no localhost,
* clear initialization...
=> Refactoring of tree package

README.md
=> Some general info on cothorities

lib/sign/messagessign.go, lib/sign/nodehelper.go, lib/sign/nodeprotocol.go, lib/sign/nodeutils.go, lib/sign/nodevoting.go
This was used during voting process that we don't do know, old legacy code.
Don't use Atomic.LoadInt64 with 32-bit architecture on ARM ;)
=> removed LastSeenVote parameter

lib/sda/host.go
As a consequence of: https://github.com/dedis/crypto/issues/60
=> Adapt NewHostKey to the new NewKeyPair function

lib/network/net.go, lib/sda/host.go, lib/sda/host_test.go, lib/sda/protocol.go
So to automatically connect to the TreeNode.
=> Sda auto connect

lib/merkle/merkle.go, lib/merkle/merkle_test.go, lib/network/encoding.go
Basic commit-tree implementation used (resolves issue  #192)
=> Basic commit tree implementation (issue #192)

lib/cosi/cosi.go, protocols/cosi/cosi.go
=> worked some of the English in the comments

lib/crypto/schnorr.go, lib/crypto/schnorr_test.go
changes: public key wasn't used for verification (now it is), some refactoring, added test
=> Fix #218: Verification of Schnorr signatures works (and is tested)

protocols/cosi/cosi.go, protocols/cosi/packets.go
=> Remove obsolete field (#209)

lib/cliutils/utils.go, simul/platform/deterlab.go, simul/platform/localhost.go, simul/platform/platform.go, simul/platform/platform_test.go, simul/simul.go
You can do
`./simul  -debug 3  -race -platform localhost runfiles/my_favorite_simul.toml` now.
=> Implement issue #244

lib/monitor/proxy.go, simul/platform/deterlab.go, simul/platform/localhost.go, simul/platform/platform.go, simul/platform/platform_test.go, simul/runfiles/cosi_simple.toml, simul/simul.go
=> MonitorPort is not propagated to platforms

lib/cosi/cosi.go, lib/sda/tree.go, lib/sda/tree_test.go, protocols/cosi/cosi.go
Nothing more to add that the title does not already say... ;)
=> Cosi : verifcation at level of tree

lib/monitor/stats.go, lib/monitor/stats_test.go
Pulled from `redo_cosi_graphs`
=> passing monitor-test with new stats.String()

lib/sda/node.go, lib/sda/overlay.go, protocols/byzcoin/pbft/pbft.go, protocols/byzcoin/pbft/simulation.go, protocols/cosi/cosi_test.go, protocols/ntree/simulation.go, simul/cothority/cothority.go
Refers to https://github.com/dedis/cothority/issues/278
=> Infinite Loop with Start()

lib/sda/host_test.go
Enabling HackyCosi test again by importing only cosi-protocol and not all.
=> adding only cosi-protocol

app/chose_version.sh, app/cosid/main.go, app/cross-compile.sh
Couldn't resist to make some scripts for easy deployment. Tested it on my server (the EPFL-server is down) and it doesn't work - see issue in cosi_cli.
=> some scripts for convenient app-building

protocols/cosi/cosi.go, protocols/cosi/cosi_test.go
Corner-case: only one node in the Cothority. Correct signature.
=> added correct running for one node only

lib/crypto/proof.go, lib/network/encoding.go, lib/network/net.go, lib/network/net_test.go, lib/network/simple_test.go, lib/network/struct.go, lib/sda/export_test.go, lib/sda/host.go, lib/sda/host_msg.go, lib/sda/host_test.go, lib/sda/local.go, lib/sda/node.go, lib/sda/node_test.go, lib/sda/overlay.go, lib/sda/protocol.go, lib/sda/protocol_test.go, lib/sda/tree.go, lib/sda/tree_test.go, lint.sh, protocols/byzcoin/byzcoin.go, protocols/byzcoin/ntree/ntree.go, protocols/byzcoin/pbft/pbft.go, protocols/byzcoin/server.go, protocols/cosi/cosi.go, protocols/cosi/packets.go, protocols/jvss/jvss.go, protocols/jvss/jvss_test.go, protocols/manage/broadcast.go
=> Differentiate uuid.UUID

README.md
Changing the README for the new binaries. Closes #329
=> added comment about fetching cosi_cli

simul/runfiles/test_jvss.toml
=> Update .toml for JVSS

app/cosi/cosi.go
There was a stray 'dbg'-message when signing a message - took it away and cleaned up some of the debug-msgs.
=> better stdoutput for sign msg

app/cosi/cosi.go, lib/sda/host.go, lib/sda/local.go, lib/sda/processor.go, protocols/cosi/cosi.go, services/cosi/api.go, services/cosi/cosi.go, services/cosi/cosi_simul.go, services/cosi/encode.go
This gives us a running example of how to use the service processors.
=> Add service processor to cosi

lib/dbg/debug_lvl.go, lib/dbg/debug_lvl_test.go
Directly to development because we merged usability before this one.
Refer to #377 for details.
=> Usability dbg stdout

app/cosi/cosi.go, app/libtest.sh, app/test_cosi.sh
Making the "test_cosi.sh" test passes
=> Fix usability test_cosi.sh test

lib/sda/tree.go
PR in order to save time (no further changes in dedis/cosi)
=> Helper for reading the list of public keys from an EntityList

.travis.yml, lib/config/config.go, lib/config/config_test.go
Adds a test for the reading of the group-toml-file and also returns the description.
=> adding server descriptions

lib/sda/host_test.go
This test will have to pass. It checks #389
=> failing reconnection

protocols/manage/count_test.go, protocols/manage/propagate.go, protocols/manage/propagate_test.go
Adding a protocol to propagate structures in services.
=> Protocol propagate

lib/sda/tree_test.go
Added Benchmark for conversion between Marshaled and Unmarshaled trees
=> added benchmark

lib/cosi/cosi_test.go, lib/network/encoding.go
Using the optimized (and formatted) ed25519 curve.
See #408 .
=> Use ed25519 optimzed curve

protocols/medco/deterministic_switching_protocol.go, protocols/medco/deterministic_switching_test.go, protocols/medco/key_switching_protocol.go, protocols/medco/key_switching_test.go, protocols/medco/private_aggregate_protocol.go, protocols/medco/private_aggregate_test.go, protocols/medco/probabilistic_switching_protocol.go, protocols/medco/probabilistic_switching_test.go, services/medco/api.go, services/medco/libmedco/crypto.go, services/medco/libmedco/crypto_test.go, services/medco/libmedco/medco_structs.go, services/medco/libmedco/survey_store_test.go, services/medco/service_test.go
Making medco goimports-compatible
=> merged goimports-formatting of import

monitor/rtime_windows.go, simul/platform/localhost.go, simul/simul_test.bat
=> Windows test batch file added

Makefile
=> don't echo test-calling

app/lib/config/config.go, network/struct.go, sda/context.go, sda/export_test.go, sda/host.go, sda/node_test.go, sda/overlay.go, sda/processor.go, sda/processor_test.go, sda/service_test.go, sda/tree.go, services/identity/service.go, services/medco/service.go, services/skipchain/skipchain.go, services/status/status.go
=> Cleaning up #512

simul/platform/platform_test.go
=> changed /tmp to ioutils.tmpfile

crypto/crypto_test.go, crypto/hash.go, crypto/hash_test.go, crypto/proof_test.go, simul/platform/platform_test.go
=> implemented 517

sda/processor.go, sda/processor_test.go
=> implemented #530

sda/overlay.go, sda/service_test.go, sda/tree_test.go
When editing the code with `Atom`, these linter issues popped up.
=> some linter issues

app/lib/server/server.go, app/test_cothorityd.sh, test_integration.sh
Implements #537 - depends on https://github.com/dedis/cosi/pull/54
=> all integration-tests run (with the exception of test_cisc)

sda/service.go, sda/service_test.go
=> implemented AvailableServices and Service in serviceManager

network/tcp.go
Changes in comments helping me to read and understand the code ;)
=> Comment edits from refactor_network_tcp

sda/host.go, sda/processor.go, sda/service.go, sda/simulation.go
Added methods for
- `(Host|SimulationConfig).GetService` - to retrieve the service of a host
- `Client.(Rx|Tx)` - retrieve the bandwidth-data
=> added missing methods

.travis.yml, coveralls.sh, log/lvl_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dedis/cothority/613)
=> Fix coveralls/travis reporting

sda/context.go, sda/processor.go, sda/service.go, sda/status.go
=> Comments for SDA changes [5/7]

sda/context.go, sda/export_test.go, sda/local.go, sda/overlay.go, sda/service.go, sda/service_test.go, simul/cothority/cothority.go
=> renaming host->conode and variables

app/test_cisc.sh, app/test_cothorityd.sh, app/test_guard.sh, app/test_status.sh
=> made app/test-outputs less verbose

install.sh, protocols/bftcosi/bftcosi_test.go, protocols/byzcoin/byzcoin_simulation.go, protocols/byzcoin/ntree/ntree_simulation.go, protocols/byzcoin/pbft/simulation.go, protocols/cosimul/protocol.go, protocols/example/channels/example.go, protocols/example/handlers/example.go, protocols/jvss/jvss.go, protocols/manage/broadcast.go, protocols/manage/close_all.go, protocols/manage/count.go, protocols/manage/propagate.go, protocols/ntree/ntree.go, protocols/randhound/randhound.go, sda/conode.go, sda/conode_test.go, sda/local.go, sda/node_test.go, sda/overlay.go, sda/overlay_test.go, sda/protocol.go, sda/protocol_test.go, sda/treenode.go, services/skipchain/skipchain.go
=> Store protocols in Conode

simul/matplotlib/stats.py
small change in stats.py that allows usage of read .csv-file with numpy - ported from `nsdi_base`.
=> using numpy-arrays

network/client.go, network/local.go, network/tcp.go
=> Error handling in network

app/lib/server/server.go, protocols/cosi/cosi.go
=> Checking 681

app/cisc/cisc.go, app/cisc/commands.go, app/cisc/lib.go, app/cothorityd/cothorityd.go, app/guard/guard.go, app/status/status.go
=> changed to ufavre and tested

app/cothorityd/cothorityd.go, app/lib/server/server.go, app/test_cothorityd.sh, protocols/cosi/cosi.go
=> cothorityd has also check-argument now

log/lvl.go
=> and there was colors

monitor/measure.go, monitor/monitor.go, monitor/monitor_test.go, monitor/proxy.go, monitor/stats.go, monitor/stats_test.go
Fix the issue #603 : namely it goes from `NewSingleMeasure().Record()` to `RecordSingleMeasure()`.
=> Monitor - single measure as private 

network/encoding.go, network/tcp.go, protocols/cosi/cosi.go, protocols/cosi/cosi_test.go, protocols/cosi/packets.go, protocols/cosimul/protocol.go, sda/context.go, sda/export_test.go, sda/local.go, sda/messages.go, sda/overlay.go, sda/protocol.go, sda/protocol_test.go, sda/treenode.go, services/cosi/cosi.go
=> Refactor packet sda

network/router.go, network/router_test.go, network/tcp.go, network/tcp_test.go
This PR is intended to solve the exhaustion of file descriptor of connections.
=> Fix network connections - max file descriptors

app/lib/config/config.go, app/lib/server/server.go, app/lib/test/cothorityd.sh, network/struct.go
=> adding description and removing unused method

app/lib/config/config.go, app/lib/server/server.go, app/lib/test/cothorityd.sh, app/test_cosi.sh, network/struct.go
=> re-did is_description

README.md, bftcosi/bftcosi.go, byzcoin/byzcoin_simulation.go, byzcoin/ntree/ntree_simulation.go, byzcoin/pbft/simulation.go, cosimul/simulation.go, cothority.go, example/channels/simulation.go, example/channels/struct.go, example/handlers/simulation.go, example/handlers/struct.go, identity/api.go, identity/service.go, jvss/handlers.go, jvss/jvss.go, jvss/simulation.go, manage/propagate.go, manage/propagate_test.go, manage/simulation.go, ntree/simulation.go, randhound/simulation.go, randhound/struct.go, skipchain/api.go, skipchain/skipchain.go
Some renaming from SDA to onet that were still present.
=> Renaming to onet - left overs

cisc/cisc.go, cisc/lib.go, cisc/test.sh, cosi/check/check.go, cosi/client.go, cosi/cosi.go, cosi/server.go, cosi/test.sh, cothority.go, guard/guard.go, guard/test.sh, integration_test.sh, status/status.go, status/test.sh, test.sh
=> moved to new onet-apps

coveralls.sh
=> Coveralls exclude 753

bftcosi/packets.go, byzcoin/cosi/cosi.go, byzcoin/ntree/ntree.go, byzcoin/packets.go, byzcoin/pbft/packets.go, cisc/lib.go, cosi/protocol/packets.go, cosi/service/cosi.go, example/channels/example.go, example/handlers/example.go, guard/guard.go, guard/service/guard.go, identity/api.go, identity/service.go, identity/struct.go, jvss/handlers.go, messaging/broadcast.go, messaging/propagate.go, messaging/propagate_test.go, ntree/ntree.go, randhound/randhound.go, randhound/struct.go, skipchain/api.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/struct.go, status/service/status.go
This PR brings the change relative to the onet's changes done in https://github.com/dedis/onet/pull/62
=> Adapting code to network changes #722 onet

messaging/propagate_test.go, randhound/simulation/randhound.go, skipchain/skipchain_test.go
Applies once https://github.com/dedis/onet/pull/70 is merged
Closes #777
=> following onet changes 2/2

cosi/service/cosi.go, guard/service/guard.go, identity/service.go, messaging/propagate_test.go, randhound/simulation/randhound.go, skipchain/skipchain.go, skipchain/skipchain_test.go, status/service/status.go
Closes #491 
Once https://github.com/dedis/onet/pull/59 is merged.
=> following onet changes 1/2

cosi/cosi.go
=> PR: CoSi help texts

cosi/protocol/cosi_test.go, cosi/simulation/cosi_test.go, randhound/simulation/randhound.go
Changes regarding the reduced API of Onet
=> Changes to reduced Onet's API

conode/README.md, conode/conode.go, cosi/cosi.go
=> Conode Help Text and README

conode/run_conode.sh
=> Run conode 788

cisc/test.sh, cosi/test.sh, guard/test.sh, status/test.sh
=> Integration tests 794

cisc/test.sh, conode/run_conode.sh, conode/test.sh, cosi/test.sh, guard/test.sh, status/test.sh
I hope these are the last changes for `v1`...
=> changed path in all scripts

cisc/cisc.go
=> kv votes directly now

cisc/README.md, cisc/cisc.go, cisc/lib.go, cisc/test.sh
=> make symlink if authorized_keys exist

cisc/cisc.go, cisc/lib.go, cisc/test.sh
=> Give more info when voting

pop/service/api.go, pop/service/api_test.go, pop/service/service.go, pop/service/service_test.go, pop/service/struct.go
This is a first part of the Proof-of-personhood code - the service.
It is set up as a suite of good and nice commits. So you can have a look at each commit and understand how the thing grows. And yes, each commit passes all tests ;)
=> Pop service - 1/2

pop/app.go, pop/app_test.go, pop/commands.go, pop/test.sh
This adds the application to the pop-party. Some things are still missing, see #818 - but they will come later.
Closes #817
=> Pop app - 2/2

conode/run_conode.sh
=> don't fail if public.toml not present

coveralls.sh
Changing coveralls so that it tests against cothority.v1
=> test in correct directory

conode/conode_test.go, cosi/cosi_test.go, cosi/simulation/simul_test.go, example/simulation/simul_test.go, guard/guard_test.go, jvss/simulation/simul_test.go, ntree/simulation/ntree.toml, ntree/simulation/simul_test.go, pop/app_test.go, status/status_test.go
Gets better coverage for simulations...
=> Coverage 556

conode/run_conode.sh
Closes #840 
This one is for @Daeinar so he can run his conode without killing all other people on the server.
=> added memory-argument

scmgr/app.go, scmgr/test.sh
Here is the code of the scmgr index command
Gaylor
=> feat(scmgr): implement index command

scmgr/app.go, scmgr/test.sh
=> Skipchain 835

cosi/service/cosi.go, cosi/service/cosi_test.go
=> cosi doesn't hang anymore 839

Makefile
=> remove jvss/simulation from testing

cosi/service/cosi.go, messaging/broadcast.go, skipchain/msgs.go
=> made ID use consistent - 2/2

cosi/service/cosi_test.go
Cosi-tests should use our debug-framework correctly.
=> small cleanup

identity/service.go, skipchain/api.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go, skipchain/verification.go
=> Skipchain 1/2

identity/api.go, identity/service.go, identity/struct.go
small changes while working on the cisc-app.
=> saving, sending and marshalling correctly

cosi/service/cosi_test.go, scmgr/README.md, scmgr/app.go, scmgr/app_test.go, scmgr/test.sh
=> SkipChain Manager 2/2

messaging/propagate.go
=> Propagate: error-handling and longer wait

cosi/protocol/cosi_test.go, cosi/service/cosi_test.go
That's the way it should be...
=> Cosi test cleanup

cisc/cisc.go, cisc/commands.go, cisc/test.sh
Adds the possibility to print a qrcode of the current cisc-configuration.
=> Cisc qrcode implementation

cisc/test.sh, identity/service.go, identity/struct.go, skipchain/verification.go
=> Android app patches

.gitignore, skipchain/api.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go
Sometimes we need to be able to search by the index of the block. This is a linear implementation.
=> Skipchain search

byzcoin/blockchain/blkparser/tx.go
=> uncomment btcsuite because its not go-getable

skipchain/skipchain_test.go
Leftovers from previous testing.
=> removed AfterTest calls

skipchain/api.go, skipchain/skipchain.go, skipchain/skipchain_test.go
=> better blocking on new requests

skipchain/api.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
Merging back changes done in other repo. Main changes:
- leader is the first node in the roster
- only leader can create new blocks
=> Ocs sc skipchains

cosi/service/cosi.go, cosi/service/cosi_test.go
=> Fix gh-922 check if root-node exists

conode/Docker.md, conode/Dockerfile, conode/Makefile, conode/README.md, conode/conode.service, conode/run_conode.sh
Making a docker-container for conodes.
=> Docker conode

pop/app.go, pop/app_test.go, pop/commands.go, pop/service/api.go, pop/service/service.go, pop/service/service_test.go, pop/service/struct.go, pop/test.sh
* Add support multiple parties per conode
* Add support merging parties
Closes #912 #908 #906 #907
=> Add multiple parties support and merge process

dedis-cothority.toml
=> adding Sinas node

.travis.yml, Makefile, skipchain/skipchain_test.go
Waiting for propagations to be finished in skipchains and only testing with 10 parallel blocks.
=> testing skipchains - some more

dedis-cothority.toml
I know descriptions are important.
=> Adds lbarman's cothority server

cisc/cisc.go, pop/app.go, pop/service/api.go
Use the new methods in `onet/crypto`.
=> more deprecated warnings

identity/api_test.go
When https://github.com/dedis/onet/pull/229 will be merged, one test will fail...
=> preparing for new schnorr signature

pop/README.md, pop/app.go, pop/commands.go
Added a readme to the pop-directory.
Also updated the help-messages for the commands.
Depends on onet#228
=> Pop readme

skipchain/api.go, skipchain/api_test.go
=> dont marshall bytes

bftcosi/bftcosi.go, bftcosi/bftcosi_test.go
=> correctly naming the threshold

identity/api_test.go, identity/service.go, pop/service/service.go, pop/service/service_test.go, skipchain/skipchain.go
This is to accommodate the changes introduced in https://github.com/dedis/onet/pull/261
I want to get this in first instead of with https://github.com/dedis/cothority/pull/964 which may take a bit more time especially if it needs to be merged with the new skipchain that @ineiti is working on
=> Remove DataAvailable uses

cisc/cisc.go, cisc/commands.go, cisc/test.sh
Implements `kvValue` that returns the value of a key
Added `kvWeb` that stores a website on the CISC
=> implemented missing kvvalue and added kvweb

bftcosi/bftcosi.go, bftcosi/bftcosi_test.go, identity/service.go, messaging/propagate.go, messaging/propagate_test.go, pop/service/service.go, pop/service/service_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go
If the threshold is greater than 0, the function will only wait for c-t
messages where c is the number of children.
=> Change NewPropagationFunc to accept a threshold

skipchain/skipchain.go
Adds a needed accessor for onchain-secrets.
=> adding accessor to db

conode/README.md
=> fixing paths for MacOSX conodes

conode/conode.go, dedis-cothority.toml
making method in cli-definition and converting dedis-cothority.toml to hex
=> cleanup conode.go

pop/app.go, pop/paperkey.sh, pop/service/api.go
using hex instead of base64 in pop
=> Pop improvement

cisc/cisc.go, cosi/service/api.go, cosi/service/cosi.go, cosi/service/cosi_test.go, identity/api.go, identity/api_test.go, identity/service.go, identity/service_test.go, pop/app.go, pop/service/api.go, pop/service/service.go, pop/service/service_test.go, randhound/proof.go, randhound/randhound.go, scmgr/app.go, skipchain/api.go, skipchain/api_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, status/service/api.go, status/service/status.go, status/service/status_test.go
Also: export some named errors that callers can check if they need to.
=> Remove ClientError

Makefile, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/struct.go
new method to add public keys - this will be used by the identity-service to allow for secure creation of new blocks.
Plus a small fix for not searching nil-blocks.
=> Skipchain improvement

cisc/cisc.go, cisc/lib.go, conode/conode.go, cosi/cosi.go, cosi/service/api.go, identity/api.go, pop/service/api.go, skipchain/api.go, status/service/api.go
Needs https://github.com/dedis/onet/pull/322 to build
=> Use suite as the first argument

conode/run_conode.sh, pop/app.go, scmgr/app.go
More replacements of 127.0.0.1 with localhost
=> more localhost replacements

skipchain/protocol_test.go
=> commenting out heisenbug

pop/app.go, pop/test.sh
Fixes a bug in the shell-parsing of toml-files
=> correcting wrong assumptions of toml-files

external/js/kyber/lib/group/group.js, external/js/kyber/lib/group/nist/curve.js, external/js/kyber/lib/group/nist/point.js, external/js/kyber/lib/group/nist/scalar.js, external/js/kyber/lib/random.js, external/js/kyber/lib/sign/schnorr/schnorr.js, external/js/kyber/test/group/nist/index.js
Fixes for random byte generation in NIST curve. Also changed to ES6 class style syntax. Modified schnorr.js to use the same
=> KyberJS: nist fixes

conode/conode.go, cosi/cosi.go, pop/app.go, scmgr/app.go, scmgr/test.sh
Depends on https://github.com/dedis/onet/pull/325
Fixes #985
=> Better and more consistent config path

.travis.yml, external/js/cothority/lib/index.js
This PR makes travis tests both subfolders and also tries to compile the bundle. Some imports were breaking when trying to build but not when testing.
=> JS: testing + building cothority & kyber sub-folders

identity/service_test.go, skipchain/skipchain_test.go
I couple that I missed in https://github.com/dedis/cothority/pull/1021
Needs https://github.com/dedis/onet/pull/330 to build
=> Move suite to the first argument

external/js/kyber/index.js, external/js/kyber/lib/curve/edwards25519/curve.js, external/js/kyber/lib/curve/edwards25519/index.js, external/js/kyber/lib/curve/edwards25519/point.js, external/js/kyber/lib/curve/edwards25519/scalar.js, external/js/kyber/lib/curve/index.js, external/js/kyber/lib/curve/nist/curve.js, external/js/kyber/lib/curve/nist/index.js, external/js/kyber/lib/curve/nist/params.js, external/js/kyber/lib/curve/nist/point.js, external/js/kyber/lib/curve/nist/scalar.js, external/js/kyber/lib/sign/schnorr/schnorr.js, external/js/kyber/test/group/edwards25519/index.js, external/js/kyber/test/group/nist/index.js, external/js/kyber/test/group/test.js, external/js/kyber/test/sign/schnorr/schnorr.js
Add a way to list of available curves and to instantiate one by name. See main file of interest: https://github.com/dedis/cothority/pull/1047/files#diff-19aeaf5f81f3b527f786cd5c295a3516
I don't get why it says all these are new files, I just changed from `curves` to `curve`... :/
=> JS: added listing of curves

conode/run_conode.sh, skipchain/skipchain.go
Make sure level 2 is for auditing and errors. Default to level 2.
Updates dedis/onet#300.
=> Tune log messages for production use

external/js/cothority/lib/skipchain/skipchain.js, external/js/cothority/test/skipchain/skipchain.js
Skipchain test failed on my machine but mocha was still happy because `done()` was called correctly. There was an failed attempt to check if an error is null or not. Long live javascript. Now the code throws an error, as regular js code should do.
=> [JS] Fix undetected failing skipchain test

external/js/cothority/package-lock.json, external/js/cothority/package.json
Build protobuf files from `external/js/protobuf` as a part of prepublish hook.
=> build protobuf files before publishing

evoting/api.go, evoting/api_test.go, evoting/service/service.go, evoting/struct.go, evoting/struct_test.go
This adds a lookup call to the evoting module.
=> adding sciper lookup to evoting

cosi/protocol/protocol.go
ByzCoinX is a bit too verbose.
=> too verbose

cosi/service/cosi.go, evoting/service/service.go, identity/api_test.go, messaging/propagate.go, pop/service/service.go, skipchain/skipchain.go
Changes to cothority to correctly create trees.
=> following latest onet

evoting/api_test.go, evoting/app/app.go, evoting/app/app_test.go, evoting/lib/lib_test.go, evoting/protocol/decrypt_test.go, evoting/protocol/shuffle_test.go, evoting/service/service.go, evoting/service/service_test.go
This adds an end-to-end test using all the service methods of the evoting system, to make sure that it really works. The other tests use internal functions and not only the external ones.
=> Add test to evoting

ftcosi/client.go
replaces base64 from `ftcosi` with hex.
=> hexifying ftcosi

cisc/README.md, cisc/cisc.go, cisc/commands.go, cisc/test.sh, evoting/lib/election_test.go, evoting/service/cast_test.go, evoting/service/decrypt_test.go, skipchain/api_test.go, skipchain/skipchain_test.go
=> made commands clearer

skipchain/api.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/protocol.go, skipchain/skipchain.go, skipchain/skipchain_test.go
I give my reasons for why fixing the documentation may be a better idea in this issue https://github.com/dedis/cothority/issues/1110
Closes #1110
=> Fix documentation to say that LatestID may be updated

bftcosi/bftcosi.go, bftcosi/bftcosi_test.go, skipchain/struct.go
Concretely, this commit https://github.com/dedis/cothority/commit/a2a69b9d5f1b5dd48da68b2654ad388f372ec39b
=> Cherry-pick changes in bftcosi from byzgen_poc back to master

evoting/lib/election.go, evoting/service/service_test.go
Fields suggested after discussion with Lindo about the layout.
=> Add Subtitle, MoreInfo and Footer fields

skipchain/api_test.go
Trying to make Jenkins happily running all tests.
=> using -race makes this very slow, so limit to 225 blocks

scmgr/app.go, scmgr/test.sh
I have a dream: Jenkins passes ;)
=> correctly parse output in test

README.md
=> updated broken link

scmgr/app.go
When adding a new skipchain, it should also get the genesis block, so that we can correctly create the index later.
=> fetching genesis block if needed

README.md, conode/Operating.md
=> updated link

evoting/lib/transaction.go, evoting/service/service_test.go
This ensures the signature is verified for all user transactions.
=> evoting: verify signature on every user transaction

evoting/lib/container.go, evoting/lib/container_test.go, evoting/lib/transaction.go, evoting/service/service.go, evoting/service/service_test.go, evoting/struct.go, external/protobuf/evoting/api.proto, skipchain/skipchain.go
Also: Be more careful with untrusted input.
=> Evoting leader only

external/js/cothority/lib/net/index.js, external/js/cothority/lib/net/net.js, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/test/net/net.js
LeaderSocket reads a roster and allows sending messages to the
leader node. As of now the leader node is the first node in the
roster.
=> cothorityjs: add LeaderSocket

conode/test.sh
These are the tests concerning https://github.com/dedis/onet/pull/401
we keep them in cothority because the behaviour is primarily observed in conode
=> Test for db name update

doc/BuildingBlocks.md
Update broken links, closes #1175
=> Update links; closes #1175

README.md
=> added references

conode/Makefile, conode/conode.go, go.mod, go.modverify
Also: Include the current git tag in the built binaries.
Update go.mod to pick up the related change to onet.
=> A makefile rule for making binary distributions

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/webpack.config.js, external/js/kyber/package-lock.json, external/js/kyber/package.json, external/js/kyber/webpack.config.js
This was needed to get the student_17_cothority-web repo to build again.
=> Update babel config to not emit any leftover ES6.

skipchain/struct_test.go
=> fixing test

evoting/lib/election.go
Changes `setStage` to check against the length of partials and mixes so that it works well with the changes introduced in #1224
=> evoting: check mix and partial length for determining stage

evoting/lib/election.go
In the unlikely event of an empty transaction making it into the skipchain (perhaps due to a panic during skipchain verification) the evoting methods should try to handle the empty transactions gracefully. The changes in this PR would make the evoting methods ignore the faulty blocks.
=> evoting: add nil checks after decoding transaction

ocs/service/service_test.go, skipchain/skipchain_test.go
This is really ugly and should not be needed. But as I've been constantly hitting 'restart' on travis to get PRs through, I think we need this for the moment.
I'm working on #1223 and #1183 to get a better hold on this. But without much success so far :(
=> remove flaky tests for now

pop/service/api.go, pop/service/api_test.go, pop/service/service.go
- api call for verifyLink
- correctly register VerifyLink in service
=> add test for verifyLink

cisc/Reference.md
This PR modifies the Cisc wiki and add the cert commands with their respective functions.
=> Update cert wiki

conode/Operating.md
Onet has no wiki anymore - update links.
=> following onet documentation

skipchain/skipchain.go
=> this todo has been done

evoting/lib/master.go, evoting/service/service.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/struct.go
Also: Update timeouts in order to get big elections to finalize.
=> Fix dangling forward links on server start

skipchain/skipchain.go, skipchain/skipchain_test.go
If a verifier panics, do not crash. Instead report the error
and treat the verifier as if it failed.
=> Do not allow verifier panic to take down the server

external/java/src/main/java/ch/epfl/dedis/lib/eventlog/Event.java
These methods are needed to inspect the event.
=> Add getter and toString to Event

eventlog/api_test.go
Jenkins found a bug in the `long_test` suite...
=> waiting in loop for eventlog to finish

external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Encryption.java, external/java/src/main/java/ch/epfl/dedis/lib/darc/SignaturePath.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/EventLogInstance.java, external/java/src/main/java/ch/epfl/dedis/ocs/OnchainSecrets.java, external/java/src/main/java/ch/epfl/dedis/ocs/OnchainSecretsRPC.java, external/java/src/main/java/ch/epfl/dedis/ocs/WriteRequest.java
Update `pom.xml` in preparation for publication on maven repo.
=> Publish cothority jar file

external/java/pom.xml
Deploy version master-180704, switch to auto-release since it seems to work well.
=> Deploy version master-180704, switch to auto-release

proto.awk
These changes are useful while working on #889.
=> Added comments, fixed warnings.

omniledger/service/service.go, omniledger/service/service_test.go
This is a first proposition to make OmniLedger avoid flooding of its chain.
=> avoid flooding of OmniLedger

omniledger/service/service.go, omniledger/service/service_test.go
@ineiti suggested this fix to get the Omniledger service working.
=> Use req.VerifyWithCB to search for missing DARCs

eventlog/api_test.go, eventlog/el/main_test.go, omniledger/contracts/value_test.go, omniledger/ol/main_test.go, omniledger/service/api_test.go, omniledger/service/service.go, omniledger/service/service_test.go
Instead of having to call Close in all tests, use the new TestClose interface of onet
=> follow onet TestClose

Makefile, omniledger/service/collect_tx.go, omniledger/service/service.go, omniledger/service/service_test.go
Correctly shut down the protocol
=> closing OmniLedger for tests

omniledger/service/contracts.go, skipchain/skipchain.go
Closes https://github.com/dedis/cothority/issues/1362 but
depends on https://github.com/dedis/onet/pull/458
=> Use the onet IsRotation method

omniledger/contracts/coins_test.go, omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/struct.go
=> Remove GetSkipchainID from CollectionView

omniledger/collection/node.go, omniledger/collection/proof.go, omniledger/service/service.go, omniledger/service/struct.go
- We have a lock on collection, so no need more locks in node.
- Closes #1370
=> Store state changes in a batch

pop/service/service.go, pop/service/service_test.go
=> Correctly handling propagation of configuration

omniledger/service/service.go
=> addressing old comment from jeff

omniledger/service/heartbeat_test.go
Using timing assumptions to test heartbeat is flaky. So we detect
changes in heartbeat instead.
Closes #1382
=> Test for change in latest heartbeat

omniledger/service/heartbeat.go, omniledger/service/service.go
This was caught in Jenkins, I don't think it ever happened on Travis or
locally. It's nice that we have multiple testing infrastructures.
=> Fix race condition on pollChan and heartbeat

external/java/src/main/java/ch/epfl/dedis/lib/omniledger/darc/Darc.java
Added missing methods to access rules in java:
- getExpression
- getActions
- removeAction
=> Accessing rules in java

external/java/src/test/java/ch/epfl/dedis/lib/omniledger/DarcTest.java
Created a test-file and forgot to add it :(
=> Forgot DarcTest

ocs/README.md, ocs/protocol/README.md, ocs/protocol/Reencrypt.md, ocs/service/service.go
The name of the paper changed and some links are broken. Also add some
text describing the differences between the paper and the
implementation.
=> Update OCS docs

omniledger/service/service_test.go
This is to prepare for the upcoming work on improving viewchange to work
in more failures scenarios.
=> Generalise the view-change test

pop/app.go
create config file path for pop if it does not exist
=> pop config path

doc/libtest.md, eventlog/api.go, eventlog/el/main.go, eventlog/el/test.sh, eventlog/service.go, external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/Instruction.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/EventLogInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/skipchain/ForwardLink.java, libtest.sh, omniledger/contracts/coins.go, omniledger/contracts/coins_test.go, omniledger/contracts/service.go, omniledger/contracts/value.go, omniledger/contracts/value_test.go, omniledger/ol/main.go, omniledger/ol/test.sh, omniledger/service/transaction.go, omniledger/simulation/coins.go, omniledger/simulation/simul.go
Also: Add el integration test to prove that it still works.
=> Update to our current understanding of how DeriveID works

omniledger/service/heartbeat.go
TestClose should block until all go-routines are closed, otherwise we
might have flaky tests.
=> Add WaitGroup to heartbeats

omniledger/contracts/coins.go, omniledger/contracts/coins_test.go, omniledger/service/service_test.go, omniledger/service/struct.go, omniledger/simulation/coins.go
Coins can be of different types and we need to store that information.
Before merging: change commit-base in #1458
Please also squash this PR.
=> Implementing coin-types

byzcoin/bcadmin/README.md, byzcoin/bcadmin/lib/config.go, eventlog/README.md
=> Better docs, fix one more OL that should be BC.

conode/run_conode.sh
Keep local version only.
Closes #1151
=> remove onet-version detection

cisc/test.sh
something went wrong with the PIN for CISC. Fixed correct grepping and other small failures.
=> Passing Jenkins

conode/Makefile
It's nice to be able to point to docker images with a certain version.
=> Also pushing the dev-YYMMDD to docker

README.md
Fix a link issue of navigating to the `Participating-in-the-cothority`.
=> Fix a link issue in the README.md

calypso/service_test.go, external/java/src/main/java/ch/epfl/dedis/calypso/ReadInstance.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java
Add the missing java classes for the Ephemeral Key Re-encryption.
Closes #1498 
I wish all PRs would be as easy as this one ;)
=> Implement Ephemeral Key Re-encryption

byzcoin/simulation/plot_sim.py
Fixing a small typo in the plotting python script by changing the name of a file from `service.csv` to `coins.csv`
=> Fix small name issue

external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java
=> Add streaming draft for ByzCoinRPC cothority-1516

external/java/src/main/java/ch/epfl/dedis/byzcoin/Block.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/DataBody.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/transaction/ClientTransaction.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/transaction/Instruction.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/transaction/TxResult.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/ValueTest.java
=> Include decode signature in Instruction

byzcoin/service.go, personhood/service.go, pop/app.go, pop/service/api.go, pop/service/api_test.go, pop/service/contract.go, pop/service/proto.go, pop/service/service.go, pop/test.sh
PoP-service:
* Verify the party is really finalized when it is written to the
ByzCoin.
* Re-enabled the test in pop/test.sh.
* Store organizers' keys
Personhood service:
* Correctly calculate service-darc
=> Personhood verification

byzcoin/bcadmin/main.go, calypso/service.go, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java
Forgot to save new LTS shares...
=> Correctly saving LTS secrets

byzcoin/README.md, byzcoin/bcadmin/README.md, byzcoin/trie/README.md, doc/BuildingBlocks.md, eventlog/README.md, eventlog/el/README.md, evoting/protocol/Decrypt.md
Update some missing navigation bars.
=> Update navigation bar in READMEs

byzcoin/proof_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/statetrie.go, byzcoin/statetrie_test.go, byzcoin/viewchange.go, eventlog/api_test.go, eventlog/service.go
=> Return an error in GetReadOnlyStateTrie 

byzcoin/bcadmin/README.md, byzcoin/bcadmin/lib/config.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
=> Implementing DARC editing in bcadmin CLI

helm-chart/README.md, helm-chart/conode/.helmignore, helm-chart/conode/Chart.yaml, helm-chart/conode/templates/NOTES.txt, helm-chart/conode/templates/_helpers.tpl, helm-chart/conode/templates/configmap.yaml, helm-chart/conode/templates/headless-service.yaml, helm-chart/conode/templates/secret.yaml, helm-chart/conode/templates/service.yaml, helm-chart/conode/templates/statefulset.yaml, helm-chart/conode/values.yaml
Provides a [helm](https://helm.sh/) chart for running a conode on kubernetes.
=> Helm chart

libtest.sh, pop/test.sh
removing unused pop-test and prepare for stderr output in onet dedis/onet#502
=> Fixes Jenkins complaints

byzcoin/service.go, byzcoin/service_test.go
=> Correctly updating roster from config-instance to new block

byzcoin/service.go, byzcoin/service_test.go, skipchain/api.go
The 'WithFailure' test is failing only in Jenkins due to a timing-problem.
This PR is passing (currently) in Jenkins, and also locally.
=> Byzcoin.TestService_AddTransaction_WithFailure fix

external/java/src/main/java/ch/epfl/dedis/calypso/ReadData.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteData.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteInstance.java, external/java/src/test/java/ch/epfl/dedis/calypso/ReadInstanceTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/WriteInstanceTest.java
Adding method to get `ReadData` and `WriteData` from a protobuf byte array. For master.
=> Add from protobuf master

.travis.yml, Makefile, byzcoin/service_test.go, external/java/src/main/java/ch/epfl/dedis/calypso/ReadData.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteData.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteInstance.java, external/java/src/test/java/ch/epfl/dedis/calypso/ReadInstanceTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/WriteInstanceTest.java
Adding method to get `ReadData` and `WriteData` from a protobuf byte array.
=> Add from protobuf

authprox/apadmin/test.sh, eventlog/el/test.sh, external/docker/Dockerfile-int, ftcosi/test.sh, integration_test.sh
Fix all current integration tests to work. Add Dockerfile for
the container that runs them.
=> Fix integration tests

conode/Dockerfile, conode/Dockerfile-dev, conode/Makefile, conode/README.md, conode/run_nodes.sh, external/docker/Dockerfile
* making dev-docker smaller
* add a docker tagged to follow git-tag, if available
=> Dockerfile improvements

external/docker/Dockerfile-unit, unit_test.sh
This adds the script required to run the unit tests in Docker
containers to prevent conflicts when running multiple jobs
=> Dockerize unit tests

external/java/src/main/java/ch/epfl/dedis/calypso/WriteData.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/BlsSig.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Bn256G1Point.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Bn256G2Point.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Bn256KeyPair.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Bn256Scalar.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519KeyPair.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519Scalar.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Scalar.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/SchnorrSig.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/bn256/BN.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/bn256/GFp12.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/bn256/GFp2.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/bn256/GFp6.java, external/java/src/main/java/ch/epfl/dedis/lib/darc/SignerEd25519.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/BlsSigTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/Bn256G1PointTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/Bn256G2PointTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/Bn256ScalarTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/Ed25519Test.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/PointFactoryTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/bn256/BNTest.java
Implement bls signatures in java. Completes steps 1 and 2 of https://github.com/dedis/cothority/issues/1440#issuecomment-448958813
=> BLS in java

byzcoin/proto.go, byzcoin/service.go, skipchain/struct.go
Improved logging
Adjusting errors for go vet
Adding some error checks
=> Logging and error cleanup

byzcoin/service.go, byzcoin/statetrie.go, byzcoin/statetrie_test.go, byzcoin/trie/proof.go, byzcoin/trie/staging.go, byzcoin/trie/trie.go
=> Check trie root in transaction

external/java/src/main/java/ch/epfl/dedis/byzcoin/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/darc/Darc.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/AuthorizationTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/DarcTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/ValueTest.java, external/java/src/test/java/ch/epfl/dedis/byzgen/GrantAccessTest.java
Not a lot is changed in terms how we evolve Darcs. Just some clean-up.
Fixes #1635
=> Simplify and clarify how we prepare darcs for evolution

.travis.yml, bftcosi/bftcosi.go, blscosi/simulation/simul.go, byzcoin/heartbeat_test.go, byzcoinx/byzcoinx.go, calypso/protocol/doc.go, calypso/service.go, cosi/simulation/protocol.go, cosi/simulation/simul.go, doc.go, ftcosi/protocol/protocol.go, ftcosi/simulation/simul.go, messaging/doc.go, pop/app.go, skipchain/skipchain.go
The previous problem might have been a transient.
Also fix URLs that were corrupted before.
=> Turn Java testing back on

external/java/src/main/java/ch/epfl/dedis/calypso/Document.java, external/java/src/test/java/ch/epfl/dedis/calypso/DocumentTest.java
=> Return true when comparing null extraData

byzcoin/contracts/insecure_darc.go, byzcoin/contracts/insecure_darc_test.go, byzcoin/secure_darc.go, byzcoin/secure_darc_test.go
=> DARC Version should start at 0

external/docker/Dockerfile, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java
Otherwise Travis stops working...
=> Change java log level back to 1

byzcoin/bcadmin/main.go
Update bcadmin to use `FillSignersAndSignWith`.
=> Fix bcadmin integration test

byzcoin/transaction.go, external/java/src/main/java/ch/epfl/dedis/byzcoin/transaction/Instruction.java
=> Domain separation for byzcoin Instruction hashing

blscosi/protocol/protocol.go, byzcoinx/byzcoinx.go
This adds a parameter to choose how many attempts must
be allowed before giving up
Fixes #1223
=> ByzCoinX timeouts with subleader failures

external/java/src/main/java/ch/epfl/dedis/lib/network/Roster.java, external/java/src/test/java/ch/epfl/dedis/lib/RosterTest.java, external/js/cothority/spec/network/proto.spec.ts, external/js/cothority/src/network/proto.ts
This updates the generation of the roster ID to reflect
the way it is done in Go.
Fixes #1728
=> Fix roster ID generation for Java and Javascript

.travis.yml, dedis-cothority.toml, external/js/cothority/publish.sh, external/js/kyber/publish.sh
=> Add Gaylor's conode to the cothority

byzcoin/replayguard.go, byzcoin/replayguard_test.go
=> Use Create for version 0 in replay state change

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/skipchain/skipchain-rpc.ts, external/js/kyber/package-lock.json
This PR changes the skipchain RPC to poll more than the leader to fetch blocks.
=> Use the roster to fetch blocks

external/js/cothority/spec/byzcoin/byzcoin-rpc.spec.ts, external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/spec/network/websocket-test-adapter.ts, external/js/cothority/spec/status/status-rpc.spec.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/network/websocket-adapter.ts, external/js/cothority/src/status/status-rpc.ts
This adds a timeout when no message is sent back
=> Connection timeout in CothorityJS

dedis-cothority.toml, status/status.go
Also: Fix a usability problem in the status tool.
=> Add a new conode to the public cothority

external/js/cothority/README.md, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/darc/identity.spec.ts, external/js/cothority/src/byzcoin/client-transaction.ts, external/js/cothority/src/byzcoin/config.ts, external/js/cothority/src/byzcoin/contracts/coin-instance.ts, external/js/cothority/src/byzcoin/contracts/credentials-instance.ts, external/js/cothority/src/byzcoin/contracts/pop-party/proto.ts, external/js/cothority/src/byzcoin/contracts/ro-pa-sci-instance.ts, external/js/cothority/src/byzcoin/contracts/spawner-instance.ts, external/js/cothority/src/byzcoin/proof.ts, external/js/cothority/src/byzcoin/proto/data-body.ts, external/js/cothority/src/byzcoin/proto/data-header.ts, external/js/cothority/src/byzcoin/proto/requests.ts, external/js/cothority/src/byzcoin/proto/tx-result.ts, external/js/cothority/src/darc/darc.ts, external/js/cothority/src/darc/identity-darc.ts, external/js/cothority/src/darc/identity-ed25519.ts, external/js/cothority/src/darc/identity-wrapper.ts, external/js/cothority/src/darc/rules.ts, external/js/cothority/src/network/proto.ts, external/js/cothority/src/protobuf/index.ts, external/js/cothority/src/skipchain/proto.ts, external/js/cothority/src/skipchain/skipblock.ts, external/js/cothority/src/status/proto.ts
Some of the messages were not actually instantiated with the right
class as there was no registration. It also forces Long to be used
in a browser environment.
=> Fix protobuf parsing of the instruction in CothorityJS

byzcoin/service.go
Coins are only allowed to travel between instruction boundaries.
Also one fewer state to track in the pipeline work.
Maybe in the future there will be a fee for submitting transactions, where the
fee is taken from the output coins. But that future is not here so we stay
conservative and remove this feature.
=> Do not use coins from old tx in new tx

byzcoin/heartbeat_test.go
The fix is described in https://github.com/dedis/cothority/issues/1473
which is referenced in the test.
=> The test that we've been skipping is fixed

byzcoin/service.go, byzcoin/struct.go, byzcoin/struct_test.go
This fixes some potential issues with the cleaning by size because
an array of sorted timestamp is used and its growth is not limited
and the maintainability depends on the insertion order. Cleaning is
now based on the block index.
It also removes the state changes reconstruction at conode boot by
a calculation of the current size as the state changes are already
built when a block is propagated and persisted in the db.
Follow up of #1784
=> State change storage initialization and cleaning

byzcoin/service.go, byzcoin/service_test.go, byzcoin/tx_pipeline.go, byzcoin/tx_pipeline_test.go, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, skipchain/skipchain.go
This is an optimisation for the leader. While the leader is waiting to create
the next block, he can already start collecting and processing transactions. 
Fixes #1409
=> Pipeline transaction processing

authprox/apadmin/test.sh
Fix the usage of bcadmin in one of the integration test of authprox to reflect the recent changes
=> Fix authprox integration test

blscosi/protocol/gen_tree_test.go, blscosi/protocol/protocol_test.go, byzcoin/collect_tx_test.go, byzcoin/service_test.go, byzcoin/tx_pipeline_test.go, eventlog/el/test.sh, skipchain/long_test.go
This PR includes a bunch of fixes for Jenkins where tests are failing.
=> Fix jenkins failures

byzcoin/service.go, byzcoin/service_test.go, byzcoin/viewchange.go, byzcoin/viewchange_test.go, calypso/csadmin/test.sh
This PR has two purposes:
- Fix the calypso integration tests
- Fix a data race in the test due to the rotationWindow
=> Fix csadmin test

byzcoin/service.go
=> Do not try to catch up non-BC skipchains.

byzcoin/bcadmin/main.go
I made the mistake to keep this code for the next PR (#1868), but it was indeed necessary to make the integration test pass.
=> Fixes the integration test

external/js/kyber/index.html, external/js/kyber/src/index.ts, external/js/kyber/src/pairing/index.ts
This updates the index to also export the pairing module so that
it is available in the bundle.
=> KyberJS: add pairing module to the bundle

dkg/pedersen/dkg.go, dkg/pedersen/dkg_test.go
=> Add an option to use a different suite for DKG

scmgr/app.go
Uses the `onet/app.LoadCothority` to correctly load a private.toml, including
the `URL` field.
=> allows scmgr to use tls websockets

byzcoin/bcadmin/main.go, byzcoin/statereplay.go
For investigating a cothority-ts misbehaviour I wanted to make sure that the forward-links
are correct. As this might also serve other verifications, I propose it as a PR.
=> bcadmin debug replay checks links

external/js/kyber/spec/group/group.spec.ts, external/js/kyber/src/curve/index.ts
This fixes the issue when trying to instantiate a P256 curve.
=> Fix issue with curve p256 in newCurve

byzcoin/contracts/contract_deferred_test.go
- execution of a proposed transaction where two signers are required
- delete of a deferred instance
=> Deferred contract: Adds test scenarios

byzcoin/bcadmin/README.md, byzcoin/bcadmin/main.go
Also use printable characters for darc description.
=> Improve bcadmin docs

external/java/pom.xml, external/js/cothority/package-lock.json, external/js/cothority/package.json, go.mod, go.sum
This updates the version of the different Cothority libraries to reflect the major changes.
=> Release v3.1.0

byzcoin/bcadmin/main.go
=> Do not globally display usage for contract

calypso/csadmin/test.sh
The directory for deleting the config files was wrong.
=> Fix csadmin integration test

external/java/src/main/java/ch/epfl/dedis/skipchain/SkipchainRPC.java, external/java/src/test/java/ch/epfl/dedis/skipchain/SkipchainRPCTest.java
=> Add a method to get all skipchains

external/java/pom.xml
- Better memory overhead for BN points
- New API for getting all the skipchain IDs
=> Bump to java library to 3.1.1

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/byzcoin/coin-instance.spec.ts, external/js/cothority/spec/byzcoin/darc-instance.spec.ts, external/js/cothority/spec/calypso/calypso.spec.ts, external/js/cothority/spec/darc/darc.spec.ts, external/js/cothority/spec/personhood/credentials-instance.spec.ts, external/js/cothority/spec/personhood/ro-pa-sci-instance.spec.ts, external/js/cothority/spec/personhood/spawner-instance.spec.ts, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/contracts/darc-instance.ts, external/js/cothority/src/darc/darc.ts, external/js/cothority/src/darc/rules.ts, external/js/cothority/src/personhood/credentials-instance.ts, external/js/cothority/src/personhood/pop-party-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts
This PR adds some useful methods to two clases:
- CredentialStruct: setCredential, delAttribute
- Rule: append, remove, which work directly on the expression
It also moves the OR and AND from Rules to Rule.
=> extends Rule and Credential

external/js/cothority/src/byzcoin/proof.ts
Before: every proof was always verified starting at the genesis block
Now: it keeps track of the latest known block and only verifies the proof
starting on this latest block, even if more blocks are available.
=> Speed up proofs

byzcoin/collect_tx.go, byzcoin/collect_tx_test.go, byzcoin/contract_darc_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go, byzcoin/transaction.go, byzcoin/transaction_test.go, byzcoin/tx_pipeline.go, byzcoin/viewchange_test.go, eventlog/api.go, eventlog/api_test.go, skipchain/struct.go, skipchain/struct_test.go
Also: improve collection tx to skip collection when block is processing
but preserve the heartbeat
Fixes #1956
=> Improve Jenkins stability

external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/lib/network/Roster.java, external/java/src/main/java/ch/epfl/dedis/lib/network/ServerIdentity.java, external/java/src/main/java/ch/epfl/dedis/lib/network/ServerToml.java, external/java/src/main/java/ch/epfl/dedis/skipchain/ByzcoinSig.java, external/java/src/test/java/ch/epfl/dedis/lib/RosterTest.java, external/java/src/test/java/ch/epfl/dedis/lib/ServerIdentityTest.java, external/java/src/test/java/ch/epfl/dedis/status/StatusRPCTest.java, external/java/src/test/resources/public.toml, go.mod, go.sum
Also: Add support for Url in the Roster and toml files.
Also: Update to Onet v3.0.15
=> Fix websocket not closed in the Java library

external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/Instance.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/Proof.java, external/java/src/main/java/ch/epfl/dedis/eventlog/EventLogInstance.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/contracts/coin-instance.ts, external/js/cothority/src/byzcoin/contracts/darc-instance.ts, external/js/cothority/src/byzcoin/instance.ts, external/js/cothority/src/byzcoin/proof.ts, external/js/cothority/src/calypso/calypso-instance.ts, external/js/cothority/src/calypso/calypso-rpc.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/personhood/ro-pa-sci-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts
Follow up on #1959 to implement the fix for Java and Javascript.
Fixes #1959 
Fixes #1960
=> Proof verification for external libraries

external/js/cothority/package-lock.json, external/js/cothority/package.json
=> Cothority JS: version 3.1.3

conode/Dockerfile, conode/Dockerfile-dev
Forward of dedis/cothority_template#54 (base image issue already fixed).
=> conode/Dockerfile*: use CMD exec form

byzcoin/service.go
=> Verify contract ID in state changes

byzcoin/bcadmin/main.go, byzcoin/bcadmin/main_test.go
=> Fix bcadmin link regression

byzcoin/contract_name_test.go, external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/Instance.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/Proof.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/StateChangeBody.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/contracts/NamingInstance.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/EventlogTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/NamingTest.java
This is the Java API for the naming contract.
=> Name contract java

byzcoin/contract_deferred.go, byzcoin/statetrie.go
Also update the ReadOnlyStateTrie documentation.
=> Check error on StoreAll in deferred

external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java
=> Get ByzCoinIDs in Java

skipchain/struct.go
=> Return error if bucket does not exist

conode/Makefile, external/js/kyber/package-lock.json, external/js/kyber/package.json
Also pick up a change I snuck into the v3.1.3 tools binary distribution.
=> Publish a new version of Kyber to NPM

byzcoin/bcadmin/clicontracts/deferred_test.sh, byzcoin/contract_deferred.go
Fixes #2021
Related to #2019 and #1938
=> Makes testDeferredInvokeDeferred pass

byzcoin/service.go
=> Improve log message when returning a proof

calypso/service.go, external/js/cothority/package-lock.json, external/js/cothority/spec/calypso/calypso.spec.ts, external/js/cothority/spec/personhood/spawner-instance.spec.ts, external/js/cothority/src/byzcoin/instance.ts, external/js/cothority/src/calypso/calypso-rpc.ts, external/js/cothority/src/darc/identity-ed25519.ts, external/js/cothority/src/log.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/personhood/credentials-instance.ts, external/js/cothority/src/personhood/pop-party-instance.ts, external/js/cothority/src/personhood/ro-pa-sci-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts, external/js/cothority/tsconfig.json
Adding changes from the mobile-branch of omniledger. Mostly cosmetic changes and copy-methods to access private fields.
=> Mobile update

external/js/cothority/src/calypso/calypso-instance.ts
There is a test-case that is only used in the dynacred, where a calypsoRead is spawned
using a spawnerInstance and a coinInstance that has to pay for it. For this use-case,
CalypsoReadInstance.spawn didn't use ClientTransaction.make
=> Fix calypsoRead spawn

external/js/kyber/spec/group/edwards25519/vector.spec.ts, external/js/kyber/spec/helpers/jsverify.ts, external/js/kyber/spec/helpers/utils.ts, external/js/kyber/spec/sign/bdn/bdn.spec.ts, external/js/kyber/spec/sign/mask.spec.ts, external/js/kyber/src/curve/edwards25519/scalar.ts, external/js/kyber/src/curve/index.ts, external/js/kyber/src/curve/nist/curve.ts, external/js/kyber/tsconfig.json
Add `noImplicitAny` to the typescript compiler and fixing yield issues.
=> js/kyber: use noImplicitAny

byzcoin/bcadmin/clicontracts/name.go, byzcoin/bcadmin/clicontracts/name_test.sh, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/lib/utils.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh, byzcoin/contract_name.go, byzcoin/service.go, calypso/csadmin/clicontracts/write_test.sh, calypso/csadmin/test.sh
Plus some code formatting / refactoring
=> Adds a cli interface for the name contract

calypso/csadmin/README.md
=> Fixes a minor typo

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/kyber/package-lock.json, external/js/kyber/package.json
Make `npm audit` pass. The problems were mostly in dev dependencies.
Bump version numbers to publish these new packages.
---
=> JS: Update NPM packages

README.md
Updated the roadmap to give clear end of life dates.
=> Updated the roadmap.

.travis.yml, README.md, conode/README.md
Change to using Go 1.13, improve documentation about our policy.
=> Move to Go 1.13

byzcoin/bcadmin/README.md, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh, go.mod, go.sum
This command fetches a block from one or more nodes and displays information
about the header and the body. It can be used to display parts of the chain
as seen from different nodes.
---
=> adds bcadmin debug block

.github/PULL_REQUEST_TEMPLATE.md
Is this OK like that, or should we keep the "shouldn't|couldn't|wouldn't|hasn't"-format?
=> Proposal for error-handling

.github/PULL_REQUEST_TEMPLATE.md
=> Update xerrors use

external/js/cothority/spec/log.spec.ts, external/js/cothority/src/log.ts
=> Move stackFrameOffset to printcaller

conode/README.md, doctoc.sh
This PR updates the doctos.sh, which wasn't handling exit 1 correctly. It also updates the `conode/` readme: I just moved the introduction chapter before the table of content. 
---
=> Updates the doctoc.sh and the conode/ doc

external/Makefile, external/README.md
=> Adds some instructions on how to build `external/`

external/js/cothority/index.html
=> Minor improvement on the cothority/index.html

calypso/csadmin/clicontracts/write.go, calypso/csadmin/commands.go
Commit 79ddf19d2ccb41ffa97a7595e923b5b4aab068a2 included a test that was only compatible with a feature implemented in the odyssey-needs branch.
This PR makes the test pass by adding this missing feature.
---
=> Fixes a csadmin test

byzcoin/bcadmin/clicontracts/name.go, byzcoin/statetrie.go, go.mod
=> Codacy reports

external/java/pom.xml
Update Java client version and some dependencies.
=> Update some java dependencies, bump version number.

byzcoin/viewchange.go
=> correctly print message

byzcoin/api.go, byzcoin/bcadmin/lib/utils.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/viewchange_test.go, calypso/service_test.go, dkg/pedersen/dkg.go, go.sum, skipchain/skipchain.go, skipchain/struct.go
To avoid problems while storing the forward-link and the block, do it
atomically using `StoreBlocks`.
---
=> Atomically commit forward-link and new block

byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
=> Fixes wrong implementation and test of "bcadmin darc cdesc"

byzcoin/service.go
At first I only wanted to update an error in order to include the instanceID when one wants to create two times the same DARC. (the error I get is "contract darc tried to create existing instanceID", and I wanted to add the instanceID that already exist to this error).
I then refactored a bit the function that, IMHO, had some implementation details that made it harder to read (namely using a `defer` to add some post-instruction and the named return parameter, + some non-compliant formatting).
---
=> Refactors the processOneTx function

.travis.yml
Disable NPM auto-deployment for now until we firgure out v4 plans.
=> Disable NPM auto-deploy for master

doctoc.sh
solving some real problem here 😆
---
=> doctoc.sh: Fixes the case where an emoji is used in the title

external/js/cothority/package-lock.json, external/js/cothority/package.json
It also fixes some vulnerabilities.
=> CothorityJS uses KyberJS v3.4.0

byzcoin/bcadmin/lib/config.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
- also fixes a wrong test of "testReset()"
---
=> Updates outputs of "bcadmin info" and "bcadmin instance"

external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/skipchain/skipchain-rpc.ts, go.mod
To have a better user experience, it is useful to give a
IConnection to the constructors of ByzCoinRPC and SkipchainRPC,
so that the calls to the nodes are done in a more defined
manner.
---
=> Extend constructors

external/js/cothority/src/network/proto.ts, external/js/cothority/src/personhood/ro-pa-sci-instance.ts
Adds the following marshalling methods:
RoPaSciInstance: to/from Object
Roster: toToml
---
=> Marshalling methods

bevm/bevm_client.go
Fix a remaining unchecked cast from #2144.
---
=> BEvm cmdline: fix unchecked cast

.travis.yml
* inline single-use anchors
* we are only building for go 1.12, not testing, is it wanted?
* add lint for external/js
=> travis: add lint to external/js

external/js/kyber/spec/pairing/point.spec.ts
Nano patch for the lint issue which now fail the build on master.
=> external/kyber/bn256: fix lint of tests

byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
=> Adds --shortPrint option to "bcadmin darc add"

evoting/api_test.go, evoting/service/service.go, evoting/service/service_test.go, evoting/struct.go, go.mod, go.sum
The people.epfl.ch website we are using changed their output format
so adjust to compensate.
=> Fix LookupSciper problem

external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/network/nodes.ts, external/js/cothority/src/skipchain/skipchain-rpc.ts, skipchain/api.go, skipchain/api_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go
=> GetUpdateChain: send all available updates

byzcoin/api.go, byzcoin/contract_darc_test.go, byzcoin/contracts/coins_test.go, byzcoin/service_test.go, byzcoin/transaction.go, byzcoin/transaction_test.go, calypso/api.go, calypso/csadmin/clicontracts/lts.go, calypso/csadmin/clicontracts/read.go, calypso/csadmin/clicontracts/write.go, calypso/service_test.go, eventlog/api_test.go, personhood/api_popparty.go
Added more warnings:
- when signing the transaction
- when sending a transaction
And fixed failing tests
=> ClientTransaction version warning

external/js/cothority/src/network/connection.ts
=> Simplify error handling

bevm/bevm_contract_test.go, bevm/service.go
This PR simplifies the way the `bevm` contract is registered.
Closes #2206.
---
=> bevm: simplify contract registration

byzcoin/service_test.go, calypso/csadmin/main.go, external/js/cothority/package-lock.json, external/js/cothority/package.json
=> Bumps js/cothority version

.travis.yml, external/js/cothority/package.json, external/js/kyber/package.json
Add a `npm test` pass before publishing.
=> external/cothority: run tests before publish

external/js/cothority/index.html, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/kyber/index.html, external/js/kyber/package-lock.json, external/js/kyber/package.json
To ensure style consistency, adding HTML linting.
=> Add HTML linting

external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/contracts/index.ts, external/js/cothority/src/byzcoin/index.ts, external/js/kyber/src/curve/nist/index.ts, external/js/kyber/src/curve/nist/point.ts
Fix some exports, as the `const` construct somehow does not allow to export `types`.
=> More exports

conode/README.md, dedis-cothority.toml, external/js/cothority/spec/network/proto.spec.ts, external/js/cothority/src/network/proto.ts
Bump to latest version of the roster.
=> roster: update to latest

README.md
=> Adds a links to the original Cothority paper

byzcoin/bcadmin/cmd_db.go
An error did not show the chains that are available.
=> Show chains if none given

README.md, bftcosi/README.md, blscosi/README.md, blscosi/blscosi/README.md, byzcoin/README.md, byzcoinx/README.md, cosi/README.md, doc/Protocols.md, doc/README.md, ftcosi/CLI.md, ftcosi/README.md
=> Uses published versions of the papers

byzcoin/bcadmin/cmd_db.go, skipchain/api.go
Make nicer output and only get 100 blocks at a time.
=> Nicer catchup logs

evoting/lib/transaction.go, evoting/protocol/shuffle.go, evoting/service/service.go, evoting/service/service_test.go, skipchain/skipchain.go
Protect from panic due to shuffle of nil points.
Added a test mode which makes it easier to do full tests including
finalization.
Added date check on vote cast.
=> Evoting improvements

byzcoin/bcadmin/cmd_db.go
When trying to catch-up, it is possible that a node has a wrong view of the
skipchain. This PR makes sure that all nodes agree on the latest
available block.
=> make sure that a latest block is really the latest

byzcoin/wallet/main.go
- correctly return error
- update roster in 'cl' when getting new block
=> Fix wallet

external/js/kyber/package-lock.json, external/js/kyber/package.json
Updated the bn.js library to the latest version.
Used npm audit fix.
=> Publish @dedis/kyber@3.4.3

PUBLISH.md
Describe how to publish a new release of cothority.
=> Add a publish.md file

external/js/cothority/src/byzcoin/byzcoin-rpc.ts
Verifying the signature of the forward-links in javascript is quite heavy.
It takes about 100ms to verify 1 link!
This PR adds a flag to the byzcoinRPC methods to skip that check.
=> Add flag to skip verification

external/js/cothority/src/calypso/calypso-rpc.ts
Adding a missing call to the calypso-API.
=> Adding GetLTSReply

byzcoin/service.go, byzcoin/service_test.go
When a block is proposed, the current check is to make sure the age of the block is between
```- 4 * blockInterval...4 * blockInterval```
In the following scenario the upper age of the block is too small:
- slow transactions - because the timestamp needs to be set _before_ executing the transactions
- subleader retries because of nodes that are down
So this PR changes the verification of the maximum age of the block:
- newer blocks are rejected if their timestamp is _before_ the previous block
- newer blocks are rejected if their timestamp is _after_ the node's time + 4 * blockInterval
=> Verify timestamp of new block

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/test.sh, byzcoin/service.go
- use runBA0 for test.*Grep calls
- fix error report in byzcoin.service.catchupAll
- correctly initialize fetchBlocks in bcadmin
Closes #2303
=> Fix bcadmin tests

.travis.yml
See https://github.com/dedis/Coding/pull/6
=> travis: go mod tidy done by Coding

bevm/service_test.go
Closes #2328
Closes #2328 
---
=> Wait for transaction to be propagated to all nodes

external/js/cothority/README.md, external/js/kyber/README.md
Adds a simple release description to the ts-code.
=> Release description

external/js/cothority/spec/bevm/account.spec.ts, external/js/cothority/spec/bevm/client.spec.ts, external/js/cothority/spec/bevm/contract.spec.ts, external/js/cothority/src/bevm/client.ts
=> Add serialization of client objects

external/js/kyber/package-lock.json, external/js/kyber/package.json
=> js/kyber: mv @types/elliptic to deps

external/js/cothority/package.json
=> Publish cothority-js v3.5.0

PUBLISH.md
=> Update publish doc

external/js/cothority/package-lock.json, external/js/cothority/package.json
This PR upgrades the version of `typedoc` to fix issues during package publication.
Fixes #2352
=> Upgrade typedoc to fix generation issues

external/js/cothority/package-lock.json, external/js/cothority/package.json
Uses the latest version of kyber, where the previous version had some security issues with its dependencies.
=> Updates @dedis/cothority dep

blscosi/protocol/protocol.go, blscosi/protocol/protocol_test.go, blscosi/protocol/sub_protocol.go, byzcoin/viewchange/viewchange.go, byzcoinx/byzcoinx.go, ftcosi/protocol/protocol.go, ftcosi/protocol/protocol_test.go, ftcosi/protocol/sub_protocol.go, skipchain/skipchain.go
Things I saw while working on the Jenkins-patch.
Should not change anything in the processing, mostly cleanup and niceifying of logging-output
=> Some cleanup

byzcoin/bcadmin/cmd_db.go
=> insist on node to fetch blocks from

skipchain/struct.go, skipchain/struct_test.go
The current way of finding the skipchain IDs is to go through all blocks. As the
`network.Decode` is very slow if points need to be decoded, this takes a long time:
on the current chain (100k blocks), it takes about 5 minutes to decode all blocks.
This method only decodes the necessary fields, which gives a speedup of about
150x-200x.
Instead of a Benchmark, there is only a TestBenchmark, because go's Benchmark
insists on using high numbers of b.N, which take too long...
Closes #2374
=> Find skipchain IDs faster

byzcoin/README.md, byzcoin/proto.go, byzcoin/service.go, byzcoin/tx_pipeline.go, external/java/src/main/java/ch/epfl/dedis/lib/proto/ByzCoinProto.java, external/proto/byzcoin.proto
Added some documentation to how the new rollup works.
=> Rollup and new ViewChange documentation

blscosi/protocol/sub_protocol.go, byzcoin/api.go, byzcoin/bcadmin/lib/utils.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go, byzcoin/viewchange.go, byzcoin/viewchange_test.go, byzcoinx/byzcoinx.go
Moving the small fixes to the main code outside of #2384
Closes #2386
=> Small fixes from test-branch

blscosi/blscosi/actions.go, byzcoin/api.go, byzcoin/bctest.go, byzcoin/service_test.go, external/java/pom.xml, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java, external/java/src/test/java/ch/epfl/dedis/integration/ManualTestServerController.java, external/java/src/test/java/ch/epfl/dedis/integration/TestServerController.java, go.mod, go.sum, personhood/api.go, personhood/phapp/main.go, personhood/service.go, skipchain/protocol.go
Leftovers between #2400  and #2404 
Depends on #2404
=> Cleanup of log messages and small stuff

byzcoin/service.go, byzcoin/service_test.go, skipchain/skipchain.go
The current code cannot start a node anymore if it doesn't have
at least the genesis block in the db.
This PR fixes this and allows a node with an empty database to
join the network again.
It also fixes:
- faster download of key/value from the global state (in batches 10'000 instead of 100)
- nicer display of connection errors when updating the blocks
Depends on dedis/onet#664
Depends on #2406
=> Allow to recreate database from scratch

external/js/cothority/src/byzcoin/client-transaction.ts
=> (js/cothority) Fixes bug in beautify

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/bevm/contract.spec.ts, external/js/cothority/src/bevm/bevm-instance.ts
=> BEvm JS: add some more methods for contract users

external/js/cothority/src/byzcoin/beautifier/coin.ts, external/js/cothority/src/byzcoin/beautifier/credential.ts, external/js/cothority/src/byzcoin/beautifier/index.ts, external/js/cothority/src/byzcoin/client-transaction.ts
=> Adds beautifier on the Coin + Credential contracts

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/cmd_db_optimize.go, byzcoin/bcadmin/commands.go
This PR adds a 'bcadmin db optimize' command that goes through the
chain and updates every block that doesn't have the optimal amount
of forward-links.
Closes #2418
=> Add bcadmin db optimize command

external/js/cothority/README.md
I found myself doing the usual voodoo manipulations to make the library work with Webpack. It happened that using the latest version of Webpack makes things even more... 🤷‍♂️ ... obscure ?
So I'm putting that there in case it might help someone.
=> Adds a note about using Webpack V5.

darc/darc_test.go, external/java/pom.xml
Use a table for testing all corner cases.
=> Use table testing

byzcoin/bcadmin/main.go, go.mod, go.sum
As qantik/qrgo disappeared, a copy of it has been put up at c4dt/qrgo.
=> Moved qrgo repo

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/kyber/package-lock.json, external/js/kyber/package.json
Run `npm audit fix` on `external/js/{cothority,kyber}`
=> Updated npm packages

bypros/browse/mod.go, bypros/browse/paginate/mod.go, bypros/proxy.go, go.mod, go.sum
This PR removes the "pure" websocket use in Bypros and relies on the Onet client.
@ineiti discussion is open.
=> Uses the onet client instead of pure websocket

status/status.go
Updates the prometheus template in `status` based on feedback from VPSI.
Changes made:
* Remove newline at the beginning of the template
* Remove newlines between conode metrics
* Add conode description as a tag (In context of evoting, the node's description is set as the school which runs the conode - eg `IC`, `SV`...)
---
=> Update prometheus template based on feedback from VPSI

.gitignore, bypros/proxy.go, bypros/proxy_test.go, bypros/service.go, bypros/storage/sqlstore/docker-compose.yml
This PR updates the part where we listen to blocks, so that when the connection unexpectedly closes, it tries to reconnect.
=> Bypros update

doctoc.sh
Fix 'cothority/doctoc.sh: line 96: output: unbound variable'
=> Fix 'cothority/doctoc.sh: line 96: output: unbound variable'

external/js/cothority/package-lock.json, external/js/cothority/package.json
=> js/cothority: bump ws

.github/workflows/deploy.yaml, .github/workflows/full_test.yaml, .github/workflows/lint_build_test.yaml, .github/workflows/release.yaml, CONTRIBUTING.md, PUBLISH.md, bevm/bevmadmin/README.md, byzcoin/DataStructures.md, byzcoin/InstanceVersioning.md, byzcoin/ReplayGuard.md, byzcoin/bcadmin/README.md, byzcoin/trie/README.md, eventlog/README.md, eventlog/el/README.md, personhood/README.md, personhood/user/README.md
* correctly trigger deployement
* use `actions/checkout@main`
* update some more doc
=> Some more edit for the main branch

blscosi/simulation/fd_test.go, blscosi/simulation/fd_unix_test.go, conode/conode_linux.go, conode/fd_darwin.go, conode/fd_unix.go, conode/full.go, cosi/simulation/fd_test.go, cosi/simulation/fd_unix_test.go, ftcosi/simulation/fd_test.go, ftcosi/simulation/fd_unix_test.go, skipchain/long_test.go, suite.go, suite_vartime.go
=> Applying latest gofmt

.pre-commit-config.yaml, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go
Add '--roster' flag in 'bcadmin info' to show full roster of current byzcoin
=> Show roster in bcadmin

conode/README.md
With this PR Docs have been updated 
docs update => proper capitalisation would be better. 👍
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>
=> fix capitalization

external/js/cothority/src/evoting/proto.ts
Adds a method to the `Partial` structure that allows to retrieve the points directly.
=> Adding points_curve to the Partial evoting

calypso/contracts.go, personhood/contracts/contract_spawner_test.go
=> Checking if LTSID exists
