dedis/cothority

app/conode/config.go, app/conode/conode.go, app/conode/run.go, app/conode/run_locally, lib/cliutils/addresses.go, lib/cliutils/addresses_test.go, lib/coconet/tcphost.go
Use 0.0.0.0 as binding address so we can run it more easy on virtual machines that have an internal private IP which is mapped to a public IP.
=> Global binding

app/conode/README.md, app/conode/check.go, app/conode/conode.go, app/conode/packets.go, app/conode/start-conode, app/conode/validate.go, lib/cliutils/addresses.go, lib/cliutils/addresses_test.go
Added a sub-command to ```conode check``` that allows the remote conode that is in validation-mode to exit, update the config.toml and restart.
=> Exit upon validation

app/shamir/peer.go, app/shamir/server.go
Temp fix is to change the suite used to directly set the suite to edwards.NewAES128SHA256Ed25519(false) (not using the full group).
=> Fixed shamir bug

lib/debug_lvl/debug_lvl.go, lib/debug_lvl/debug_lvl_test.go
Rewrote debug_lvl so that the functions return directly when the debug-level is lower than what is asked for. Before it created the string and only then did the check. But if the string is big (or huge, like printing the host-list of 8192 hosts...), this can delay a lot.
=> checks the DebugVisible before creating the string

lib/monitor/stats.go
So we can now call "-discard round,verify..." on the command line to discard the first measure for each of these measures.
=> Quickfix discard

deploy/platform/deterlab/users/users.go
Instead of just cleaning up the number of servers requested it asks a list of ALL active servers in the deterlab-experiment and kills all remaining processes there. Now we don't have 'rogue' processes sending siginig-requests or whatever from an earlier run.
=> doing cleanup of ALL servers

app/conode/conode.go, app/naive/peer.go, app/ntree/peer.go, lib/app/app.go, lib/graphs/node.go, lib/network/net_test.go, lib/network/packet_test.go, proto/sign/signingMessages.go, proto/sign/signingMessages_test.go
Moving all Edwards-suites from 
```
edwards.NewAES128SHA256Ed25519(true)
```
to
```
edwards.NewAES128SHA256Ed25519(false)
```
=> Verify Usage of Edwards-suite in CoNode

lib/dbg/debug_lvl.go
should not have any side effects: `dbg.Errorf()` currently isn't used at all
=> fixes issue #141: `dbg.Errorf()` no longer `os.Exit()`s

deploy/deploy.go, deploy/platform/localhost.go
localhost deployment fails with too many host. Now it shows the error reason: `too many open files`
see issue #17
=> fixes issue #17

protocols/cosi/cosi.go, protocols/cosi/packets.go, protocols/cosi/simulation.go, simul/platform/localhost.go, simul/runfiles/cosi_simple.toml, simul/runfiles/test_cosi.toml, simul/runfiles/test_cosi_depth.toml, simul/runfiles/test_cosi_verification.toml, simul/simul.go
Just as an example of how to use `Simulation.Node` - here I use a global variable in `lib/cosi` for the verification setting, which is of course not the very best way to do. But `Simulation.Node` is called before the Node is started. Should perhaps be renamed to `Simulation.Host` or `Simulation.Overlay`.
=> Check with simulation node

cothority.go, lib/sda/host.go, lib/sda/host_test.go, lib/sda/local.go, simul/cothority/cothority.go
As we saw in the case of `cosi_cli`, it can be confusing to have a `host.Listen` that waits to be able to connect to itself. So this does rename
- `host.Listen` to `host.ListenAndWait`
- `host.ListenNoBlock` to `host.Listen`
=> changed name to reflect default nowait

lib/crypto/crypto_doc.go, lib/crypto/crypto_test.go, lib/crypto/hash.go, lib/crypto/hash_test.go, lib/crypto/hashid.go, lib/crypto/proof.go, lib/crypto/proof_test.go, lib/crypto/schnorr.go, protocols/byzcoin/blockchain/trblock.go
If we go with merging `cosi_cli` only into `master`, then we should have `lib/crypto` in `development`, as it simplifies somewhat the hashing.
Next step is to find all places where hashes are used and get them to use these hash-functions.
=> Merging `lib/crypto` from `cosi_cli` to `development`

lib/sda/overlay.go, lib/sda/protocol_test.go
that way a
```
StartNewNode
```
is the same as
```
n := CreateNewNode
n.StartProtocol
```
=> taking 'go'-call away from StartNewNode

app/cosi/cosi.go
Exit if we stumbled on an error from which we can't recover from (missing file for instance). Also have spaces between (high level) error user messages and (low-level) errors.Error messages
see #340
=> Consistent, reasonable error handling

lib/sda/node.go, protocols/jvss/handlers.go, protocols/jvss/jvss.go, protocols/jvss/jvss_test.go, protocols/randhound/handlers.go, protocols/randhound/randhound.go, protocols/randhound/utils.go
This PR introduces various helper functions and constructions in `node.go` and addresses #249, #295,  #335.
- Added a field `treeNodeList` in `node.go`
- Added the following functions:
- `SendToParent(...)`
- `SendToChildren(...)`
- `SendToRoot(...)`
- `Broadcast(...)`
- `List()`: To get a list of all TreeNodes
- `Index()`: To get the index of the calling node in the above list / `EntityList`
- `RegisterHandlers(...)`: To register a list of SDA handlers
Moreover, it includes the changes in JVSS and RandHound.
=> Node Helper Functions

simul/platform/deterlab.go, simul/platform/deterlab/users/users.go
Some of the ssh-calls in the simulation fail normally, because the cleanup is not necessary. Only when the previous simulation failed the cleanup is needed. So the error should normally be ignored.
=> changed dbg.Error to dbg.Lvl3 for expected ssh-failures

lib/sda/context.go
It would be very useful  to have the Service's `network.Entity` as part of the `Context` so we can access it from the Services.
=> Add the network.Entity to the Context

app/status/status.go
also removed the init-function and moved `app.Before` into `app.Action`.
=> remove unnecessary constants

log/lvl.go, log/ui.go, log/ui_test.go
Print correct output for `Print` and others when in debug-output.
=> Log print correct

.travis.yml, Makefile, README.md, coveralls.sh, simul/runfiles/byzcoin.toml
Add goveralls/coveralls reporting (to keep track of test code coverage).
Resolves issue #549
=> Add coveralls reporting

app/lib/config/config.go, app/lib/config/config_test.go, app/lib/server/server.go, network/address.go, network/address_test.go, network/struct.go
This PR shows the first part of the big #499 PR regarding the use of an Address type which contains also the type of the connection.
=> [1/7] Network refactoring - Address

monitor/monitor.go
Prolong the lock till after the variable is used.
=> prolong lock

protocols/bftcosi/bftcosi_test.go, protocols/manage/propagate.go, protocols/ntree/doc.go
Changes include:
- less verbosity in bftcosi-test
- propagate timeout in manage-protocol and more debug if the timeout is reached
- add some documentation to the ntree-protocol
=> including small protocol changes

network/local.go, network/local_test.go, network/network.go, network/struct.go
This PR implements the local communication part using signaling and queues..
This PR comes with the basic interface definitions which are used throughout the network library such as `Conn`, `Listener`  & `Host`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dedis/cothority/568)
=> [2/7] Refactor network - interfaces + Local network

app/lib/config/config.go, app/lib/config/config_test.go, crypto/proof.go, crypto/proof_test.go
=> smaller set of changes

sda/simulation.go
Implements #622 
Adds a verification if the crypto-library is updated, as the `Clone()`-method of `nist.Int` was wrong.
=> adding Clone() and verification loop

sda/local.go
This requests bring a small fix to the sda Local API. Namely, it enables on to create only *one* Conode without specifying the type (local/tcp). The `Local` is doing that for us. I needed that during coding the `randhoundco` protocol.
=> unified creation of tcp/local conode for local

log/lvl.go
=> Quickfix: Change default behavior of dbg library to monochrome output

network/address.go, network/address_test.go
When using `SplitHostPort`, the IPv6 unspecified address is returned as "::", whereas other IPv6 addresses are returned in "[]". This patch unifies the behaviour, so that `Address.Host` can be used in all circumstances.
=> return correct IPv6 unspecified address in Address.Host

network/encoding.go, sda/context.go, sda/export_test.go, sda/local.go, sda/messages.go, sda/overlay.go, sda/protocol.go, sda/protocol_test.go, sda/treenode.go
This first PR introduces a way for protocols to have a clean wire format protocol with the least amount of changes. Look for #287 issue.
First this PR introduces the notion `OverlayMessage` which contains everything the `Overlay` needs to know in order to function properly. Protocols that wants to have their full own packet going into the network must have a field of `OverlayMessage` in their packet.
Then there is the notion of `ProtocolIO` (Please suggest other names if you got any) which fulfill two purposes:
-  `Wrap` a protocol *inner* message into the protocol's bigger message with the overlay information `OverlayMessage`
- `Unwrap` a protocol bigger message to give back to the `Overlay` the inner protocol message as well as the `OverlayMessage`
Sorry as there are also some …
=> [Wire-Protocol 1/3 ] SDA Changes

network/encoding.go, network/tcp.go, protocols/bftcosi/packets.go, protocols/byzcoin/cosi/cosi.go, protocols/byzcoin/ntree/ntree.go, protocols/byzcoin/packets.go, protocols/byzcoin/pbft/packets.go, protocols/cosi/packets.go, protocols/jvss/handlers.go, protocols/manage/broadcast.go, protocols/manage/propagate.go, sda/overlay.go
The new wire protocol design is not compatible for simulations because one simulation uses different "network" packages, one for each process, so there are packets which are non registered so it's not possible to Unmarshal them.
This PR fixes that by simply registering the packets a protocol use at init time.
=> Fix wireprotocol for simulation

randhound/randhound.go, randhound/struct.go
Seems like the only thing necessary to resolve #791 was the flattening of `ChosenSecrets` (old: `[][]uint32` new: `[]uint32`) in the `I2` message struct.
=> PR: Adapt RandHound to New Protobuf

conode/run_conode.sh
Closes #832 
Tested on `gasser.blue` and `dedis.ch`-conodes and it seems to work so far.
=> Run conode 832

guard/guard.go
`github.com/SSSaaS/sssa-golang` got updated and has some functions that return `error` now. This PR updates the guard-app to reflect that change.
=> adjusted to newest version of sssas

pop/app.go, pop/service/service.go, pop/test.sh
The final-statement has been signed new every time it was asked for. Now it will only reply with the already-stored final statement.
=> Make tests pass again

conode/run_conode.sh
adding wait-flag to run_conode.sh, so it can be used more easily with `screen`.
=> run_conode improvement

.travis.yml, Makefile, skipchain/skipchain.go, skipchain/skipchain_test.go
The skipchains to asynchronous updating of the forward-links and propagation of the new blocks. This is handy and good for performance (you don't have to wait for all forward-signatures and propagation before being able to go on), but in the tests it's a nuisance, as the go-routines are still active.
This patch adds a counter to the skipchain-service, so that we can test if it's done propagating.
=> Skipchain goroutines

bftcosi/bftcosi.go, bftcosi/packets.go
Like with `kyber/cosi` - bftcosi assumes point-length of 32 bytes, which is wrong for P256.
=> adjusting for different point-lengths

skipchain/skipchain.go
Closes a race when getting a reply to a block-request.
=> correctly locking block-request replies

Makefile, stable/remove_files
Oups - gopkg puts everything in `v1` - no `v1.2` if not specified as such.
Depends on onet#228
=> adjusting stable path

cisc/cisc.go, pop/app.go
Old ui error: when doing
```
cisc id keypair
```
without giving a debug-level, nothing is printed.
=> showing keypair even without debugging on

pop/app.go, pop/service/service.go, pop/test.sh
When running the pop-tests and having DEBUG_COLOR=on, it fails, because there are ESC-characters at the end of the output.
=> running pop-test with DEBUG_COLOR=on

cosi/check/check.go, cosi/client.go, cosi/service/cosi.go
Replace the util/hash package with clearer, simpler code.
=> Adapt to changes in kyber: no more util/hash

cisc/cisc.go, conode/conode.go, conode/run_conode.sh, pop/app.go, pop/service/api.go
Automatically convert public.toml files using the migrate
feature of run_conode.sh.
=> Adapt to change in onet for no base64 in toml files

identity/service.go, scmgr/README.md, scmgr/app.go, scmgr/commands.go, scmgr/test.sh, skipchain/README.md, skipchain/api.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/protocol.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
This is an implementation of #949 with the current skipchain. I'd like to take this as a base for the documentation and the new storage-system.
It also adds a `link` command to restrict who is allowed to communicate with the service:
`scmgr admin link` automatically setting up a private/public key pair and linking that to the skipchain-service
Closes #949
Closes #981
=> skipchain_auth_kyber_3_949

conode/conode.go, conode/run_conode.sh, skipchain/skipchain_test.go
Putting the `-c` and `-d` in front of the command.
Also fixes skipchain-error by following onet.
=> App flag order

bftcosi/bftcosi.go
Doesn't appear to be used anywhere
=> Removed unused aggCommit

bftcosi/bftcosi.go, bftcosi/bftcosi_test.go, bftcosi/packets.go, identity/struct.go, messaging/propagate.go, messaging/propagate_test.go, pop/service/service.go, scmgr/test.sh, skipchain/msgs.go, skipchain/protocol.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
Stop using the websockets to fetch blocks when we need them.
Use the GetBlocks protocol instead.
When instantiating the protocol, we talk to a subset of nodes now, and
take the first answer.
Also: clean up the implementation of timeouts to be typesafe, and adjustable.
=> Make chain synchronisation fault tolerant

skipchain/struct.go
this was removed in https://github.com/dedis/cothority/pull/1003, but OCS still needs it
=> Add GetLatest back as it is used by OCS

.travis.yml, bftcosi/bftcosi_test.go, bftcosi/packets.go, cisc/lib.go, conode/conode.go, conode/run_conode.sh, conode/test.sh, cosi/check/check.go, cosi/client.go, cosi/cosi.go, cosi/server.go, cosi/simulation/cosi_test.go, identity/api_test.go, integration_test.sh, pop/app.go, pop/service/service.go, pop/service/service_test.go, pop/test.sh, scmgr/app.go, scmgr/test.sh, skipchain/api.go, skipchain/api_test.go, skipchain/protocol.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go, status/status.go, suite_vartime.go
cothority.Suite defaults to P256 when vartime is enabled.
Fixes to make it work with P256 (i.e. places where the
length of a signature was hard coded).
Fixes to integration tests to follow these changes.
(But pop/test.sh and cisc/test.sh were already broken and
need to be fixed separately.)
Make run_conode.sh simpler, so that it can run from other
repositories as well unchanged.
=> Fixes so that suite can be changed at runtime

bftcosi/bftcosi.go, pop/app.go, scmgr/app.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/struct.go, skipchain/struct_test.go
Fixed a failure in the skipchain-test and some cleanup:
- one failure was due to `onet/local.CloseAll` misbehaving (dedis/onet#313)
- missing lock on testService
- cleaned up error reporting for clean tests
Depends on dedis/onet#313
=> adding test for failure in localTest

messaging/propagate.go
The propagation-protocol doesn't return errors from sending messages.
=> adding error testing to dispatch

bftcosi/bftcosi.go, skipchain/skipchain.go, skipchain/skipchain_test.go
If a leader does not know of the latest block that a client
mentions, but it does know of the chain, it can ask others in the
chain's roster to catch it up.
Test it by nuking blocks from the db in order to simulate what would
happen if you started a leader with a database backup that was out of
date.
Also: Test follower catchup, which was already working correctly.
=> Implement leader catchup

cisc/cisc.go, identity/service.go, pop/app.go, pop/service/service.go
The `var` defined the error message for a wrong pin, but the app needed an error message for an empty pin. Changed the error message and referenced the correct package.
=> pass correct error message

identity/service.go, identity/service_test.go
services should not return `network.Message` but rather the structures they're creating.
=> return structures instead of network.Message

cisc/README.md, cisc/cisc.go, cisc/commands.go, cisc/lib.go, cisc/test.sh, cosi/test.sh, identity/api.go, identity/api_test.go, identity/service.go, identity/service_test.go, identity/struct.go, integration_test.sh, pop/app.go, pop/test.sh, scmgr/app.go, scmgr/test.sh
Renamed a lot of identity structures to remove old names:
- cothority -> roster
- StorageMap -> storage
Removed double storage of roster, both in `identity.Identity` and `identity.Data`
Added correct storage of authenticated keys to identity-service (before the authentication keys were discarded upon service restart)
Cleanup of the cisc-binary to make commands more intuitive
Fixed authentication
Updated README.md
=> Cisc cleanup

.travis.yml, cosi/simulation/cosi.toml, external/js/kyber/index.js, external/js/kyber/lib/sign/index.js, external/js/kyber/lib/sign/schnorr/schnorr.js, external/js/kyber/package-lock.json, external/js/kyber/package.json, external/js/kyber/test/sign/schnorr/schnorr.js
This adds another module `kyber.sign.schnorr.{sign,verify}` to sign and verify schnorr signatures. So far it only uses what's available p256. When the ed25519 code from @gnarula will be ready, I'll try to add a compatibility test with eddsa verification.
This also adds coverage reports locally and on travis. Just run `npm run cover` to see a good resume of the current coverage.
=> Adding schnorr signatures to JS

external/js/kyber/doc/doc.md, external/js/kyber/index.js, external/js/kyber/lib/group/edwards25519/curve.js, external/js/kyber/lib/group/edwards25519/point.js, external/js/kyber/lib/group/edwards25519/scalar.js, external/js/kyber/lib/group/nist/curve.js, external/js/kyber/lib/group/nist/point.js, external/js/kyber/lib/group/nist/scalar.js, external/js/kyber/lib/index.js, external/js/kyber/lib/sign/schnorr/schnorr.js, external/js/kyber/test/group/edwards25519/index.js, external/js/kyber/test/group/nist/index.js, external/js/kyber/test/sign/schnorr/schnorr.js
exposes kyber.Group, kyber.Point and kyber.Scalar and changes
kyber.group module to kyber.curves to avoid ambiguity
=> kyberjs: rename group module to curves and expose abstract classes

scmgr/app.go, scmgr/commands.go, scmgr/test.sh, skipchain/skipchain.go, skipchain/struct.go, status/README.md, status/service/status.go, status/service/status_test.go, status/status.go
Clean up the type of the status reply, remove a call to an example
that will disappear with #1036.
Correctly display status replies which have multiple parts of the
server reporting stats.
Fixes #940.
=> Clean up status service, client

skipchain/struct.go
This removes an old structure that hangs in skipchains forever but was never used.
=> remove unused structure

messaging/propagate.go, pop/app.go, scmgr/app.go, skipchain/api.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
Change GetUpdateChain to operate on local blocks only. Delegate
responsibility to the client to go contact other servers according
to the latest roster (implemented in api.go, so that existing
clients do not see a change in behaviour).
Also: Added a test to check a worry I had about if new servers
which were invited into a chain would work correctly.
Fixes #1034.
=> Finish removing SendRaw from skipchain

external/js/kyber/.gitignore, external/js/kyber/README.md, external/js/kyber/index.html, external/js/kyber/package-lock.json, external/js/kyber/package.json
Updated package.json to mention different entry points for browser and node environments (browser and main key respectively). Made the package name consistent with the one we have at npm. Published package will only include built files now in the `dist/` directory.
=> kyberjs: update package.json

scmgr/app.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/protocol.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go, skipchain/verification.go
This changes the forward-signatures to something more reasonable like:
```
type ForwardLink struct {
// From - where this forward link comes from
From SkipBlockID
// To - where this forward link points to
To SkipBlockID
// NewRoster is only set to non-nil if the From block has a
// different roster from the To-block.
NewRoster *onet.Roster
// Signature is calculated on the
// sha256(From.Hash()|To.Hash()|NewRoster.ID)
// In the case that NewRoster is nil, the signature is
// calculated on the sha256(From.Hash()|To.Hash())
Signature bftcosi.BFTSignature
}
```
This prevents re-use of a ForwardSignature in a wrong context. It also allows later to get updates
using `ForwardSignature`s only, as it will be enough jumping from one ForwardSignature to the next, given that the `NewRoster` will …
=> Skipchain signature

cosi/simulation/cosi.toml, external/js/cothority/package.json, external/js/cothority/webpack.config.js, external/js/kyber/webpack.config.js
set libraryTarget to umd. This allows importing/requiring the browser target
which is useful for projects in Vue/React
=> js: webpack fixes

external/js/cothority/package.json, external/js/kyber/package.json
Forgot to build before publishing the previous version to npm. Added a hook that ensures this doesn't happen again in future.
=> js: build before publishing

cisc/cisc.go, cisc/commands.go
Title is self-explanatory ... It's just much easier than having to parse a custom output. This is more "unix style" where this output can be piped to other scripts :) (yes I know that `sed 's/.../.../'` is always possible..)
=> [cisc] add id flag to list ids only

bftcosi/bftcosi.go, messaging/propagate.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
Take locks on a per-chain basis, instead of on a per-parent-block
basis. Hold them until the entire update is done.
Allow the client to say "append to this chain" instead of "append to
this block".
Fixes #1073.
=> Correctly handle concurrent skipchain writes

cisc/cisc.go, cisc/commands.go, cisc/test.sh
This pr fixes the functionality of a previous PR I made because I just realized it's better to make it a bit more generic to fit all uses case. And because I haven't thought that through enough before, I realised the csv functionality is not exactly fitting my use case.
So now it's simpler: input is a file, and it's mapped to the filename or a given key. So the user has to decide what to do with the value instead of cisc deciding how to treat the value.
The test is adapted and works.
=> [cisc] replacing csv input by generic file input

identity/service.go, pop/service/service.go, scmgr/app.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/struct.go, skipchain/struct_test.go
Use `[]byte` for `bucketName` to avoid alocation and use `[]byte` in the DB wrapper functions such as Load/Save.
Depends on https://github.com/dedis/onet/pull/350
Fixes #1010
=> Use []byte for bucketName/Load/Save

skipchain/api_test.go, skipchain/skipchain.go, status/service/status.go
After working on #1073, I had some concerns that websocket clients
would not be able to write in parallel like peer services can.
This test proves there's no worries afterall (wow, was not
expecting that).
=> A test to make sure that parallel writes from websock work too

skipchain/api_test.go
@jeffallen please have a look. Turning the number of blocks down to 50 allows the test to pass (in about 66 seconds on my machine). If you think there's a deeper issue in the code please feel free to close this and we can discuss. We may also need to think about what happens if there are too many store block requests, should the server stop accepting blocks if there are too many in the queue?
Fixes https://github.com/dedis/cothority/issues/1100
=> Make TestClient_ParallelWrite shorter

scmgr/app.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
Closes #1088 
Instead of making `GenesisID` private, as proposed, it is replaced by `SkipChainID()` wherever possible and a comment on the `GenesisID` field is added.
=> Genesis id 1088

evoting/lib/chains_test.go, evoting/lib/election.go, evoting/lib/election_test.go, evoting/protocol/decrypt_test.go, evoting/protocol/shuffle_test.go, evoting/service/cast_test.go, evoting/service/decrypt_test.go, evoting/service/getbox_test.go, evoting/service/getmixes_test.go, evoting/service/login_test.go, evoting/service/open_test.go, evoting/service/reconstruct_test.go, evoting/service/service.go, evoting/service/shuffle_test.go
Replaces `Election.Data` with `Election.Candidates`. Changed the field type to `[]uint32` since scipers will be stored in it. Also introduced `Election.MaxChoices` to store maximum votes allowed in a ballot. Added a `Start` field to denote election start unix timestamp.
=> evoting: Election - replace Data with Candidates and add MaxChoices

.gitignore, doc.go, evoting/protocol/dkg.go, evoting/protocol/shuffle_test.go, evoting/service/service_test.go, ftcosi/protocol/sub_protocol.go
new linter complains about `for _ = range`
Adding a forgotten `doc.go`
Updating `.gitignore` for atom-users.
=> pass linter

skipchain/skipchain.go
Previously, in https://github.com/dedis/cothority/pull/1102, `psbd.NewBlock.GenesisID.IsNull()` was changed to `psbd.NewBlock.SkipChainID().IsNull()`. This change affected the logic of `StoreSkipBlock` because `psbd.NewBlock.SkipChainID().IsNull()` is always false and the `TestService_ParallelStoreBlock` test started failing.
I'm curious why this bug didn't break more tests.
=> Correctly add genesis block

evoting/lib/election_test.go, evoting/service/cast_test.go, evoting/service/decrypt_test.go, skipchain/api_test.go, skipchain/skipchain_test.go
Looking at https://travis-ci.org/dedis/cothority/jobs/349317079 to measure length of tests, I limited the tests that travis has to run by the longest running ones. Wherever possible I reduced the test-depth with `-short`, or I commented out the test with `t.Skip`.
If we go this way, we _really_ need to have some regular, full (non-`short`) testing twice a day, if possible including `integration_test.sh`.
=> limiting test time to let travis pass

external/js/cothority/lib/net/net.js, external/js/cothority/lib/shims/ws.js, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/webpack.config.js
The build for `node` target included all the dependencies in minified form (think of this as JS equivalent of a fat JAR). This commit excludes the dependencies in the node build (since npm is capable of resolving them).
This is required for [nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify) to parse the build and replace `ws` with a nativescript compatible dependency.
TL;DR: makes it possible to use the package in nativescript land :)
=> exclude node modules from node target and support WS in nativescript

scmgr/app.go, scmgr/test.sh
There is (at least one) error in `scmgr` that lets it fetch all new skipchains from a conode, even when `-new` is not given. Fixed and added an integration test.
=> Only update known skipchains unless the -new flag is given

external/js/cothority/lib/net/net.js
Websocket reply on android is of type [java.nio.HeapByteBuffer](https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html) which doesn't allow indexed access using square bracket notation. This results in an empty Uint8Array being created in JS and eventually an Error during protobuf decode.
This PR treats the android websocket handler separately and constructs the Uint8Array from the message using `buf.get(i)`
=> cothorityjs: fix onmessage handler on android

skipchain/protocol_test.go, skipchain/struct.go
It is possible that Roster might not be set. Do not crash
when that happens.
Fixes #1027.
=> Add forgotten nil check

bftcosi/bftcosi.go, bftcosi/bftcosi_test.go, bftcosi/packets.go, identity/api_test.go, identity/service.go, messaging/propagate.go, pop/service/service.go, pop/service/service_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
This PR implements an optimised version of bftcosi where the root node does not wait for all replies from its children, it makes progress when 2/3rd of the replies arrive. This so that in an event of a failure, we do not need to wait for a long timeout.
=> Bftcosi optimisation byzgen - byzgen_poc

evoting/service/open_test.go, evoting/service/service.go
Ensures elections aren't created with an end time before the current time.
=> evoting: check end date on election creation

cisc/test.sh
We changed recently the `unjoin` command to `leave` - also do the same thing in the `test.sh`.
=> follow changes in commands

pop/service/api.go, pop/service/service.go, pop/service/service_test.go, pop/service/struct.go
Some of the struct-definitions used lowercase letters which made the websocket-endpoint to be lowercase, too. But all other endpoints start with an uppercase, so fix this.
=> Capitalizing service endpoints

evoting/lib/container.go, evoting/lib/election.go, evoting/protocol/decrypt.go, evoting/protocol/decrypt_test.go, evoting/protocol/shuffle.go, evoting/protocol/shuffle_test.go, evoting/service/service.go
This fixes a long-standing bug in the Neff shuffle verification routing inside ```evoting/protocol```.
As it turned out the code making sure that only the most recent ballot of a user is fetched from
the skipchain invalidated the correct ballot order.
Thus the Neff shuffle code in ```kyber/shuffle``` works fine.
=> Fix shuffle verification bug

byzcoinx/byzcoinx.go, ftcosi/protocol/protocol.go, ftcosi/protocol/sub_protocol.go, messaging/propagate.go, ocs/protocol/dkg.go, ocs/protocol/dkg_test.go, ocs/protocol/ocs.go, ocs/service/service.go, ocs/service/service_test.go
Different protocols were not calling `Done` to terminate it, making a memory-leak.
=> insert defers into protocols to correctly clean up

external/js/cothority/lib/net/net.js
The Conode websocket API returns an event code with value 4000
whenever the underlying service returns an error. This PR updates
the onclose handler to reject the promise if the event code is 4000
Fixes #1084
=> cothorityjs: check event code on websocket close event

external/js/cothority/lib/net/net.js
Protobufjs includes a verification function for ensuring the data
types in the javascript object are compatible with those mentioned
in the protobuf file. This PR uses the verifier before initiating
the websocket request and rejects the promise in case of an error.
=> cothorityjs: verify protobuf message before sending request

bftcosi/bftcosi.go, skipchain/skipchain.go
Correctly fail BFTCoSi if the server is stopped.
Also cleans up correctly by not calling `Shutdown` itself.
=> making testing of bft easier

external/js/cothority/lib/net/net.js, external/js/cothority/package-lock.json, external/js/cothority/package.json
RosterSocket.send has socket redeclared in the try block which
results in lastGoodServer not being cached in the RosterSocket
object. This PR uses a different name for shadowing the "this"
variable and prevents the conflict. Also removed unneeded arguments
in the generator.
=> cothorityjs: fix variable name conflicts in RosterSocket.send

conode/experimental.go, stable/remove_files
Created a new Dockerfile which adds the evoting service to conode.go
before the build.
The resulting image can be pushed to Dockerhub. `dedis/conode:evoting` perhaps?
=> add evoting Dockerfile

evoting/lib/election.go, evoting/service/service.go, evoting/struct.go
The frontend requires a way to filter out elections based on their
current stage to enable/disable buttons and render the elections
at an appropriate position. This commit caches the current phase
of the election in the Stage field.
Another alternative would've been to expose methods on the service that allow checking the phase for every election but that would be quite expensive.
=> evoting: reintroduce Election Stage

external/js/cothority/lib/skipchain/skipchain.js
Compute the hash of the forwardlink and check that it matches the message in the signature.
=> Check correctness of byzcoinx signature message

evoting/service/service_test.go, ftcosi/protocol/helper_functions.go, ftcosi/protocol/protocol.go, ftcosi/protocol/protocol_test.go, ftcosi/protocol/sub_protocol.go
Initially, the sub protocol would return an error immediately if the
verification function returns false and exit the protocol. As a result,
the sub-leader and the leader must wait for a timeout before they
proceed to the next step in the protocol. This commit brings an
exception handling mechanism inspired from bftcosi. The difference is
that instead of returning exceptions, the nodes return the commitment
without their own share and with their part of the mask set to false.
The performance improvement is evident from a byzcoinx test.
```
tsf-444-wpa-1-068:byzcoinx cong$ git co -
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
tsf-444-wpa-1-068:byzcoinx cong$ go test  -count=1 -run TestBftCoSiRefuse
PASS
ok  	github.com/dedis/cothority/byzcoinx	2.898s …
```
=> Responds empty commit when verification fail

evoting/lib/chains.go, evoting/lib/election.go, evoting/lib/master.go, evoting/lib/transaction.go, evoting/protocol/decrypt.go, evoting/protocol/decrypt_test.go, evoting/protocol/shuffle.go, evoting/protocol/shuffle_test.go, evoting/service/service.go
Changes the evoting service to use the skipchain service to create new skipchains and append new blocks.
Blocks appended during the execution of a protocol (Shuffle, Decrypt) still make use of the websocket API since they need to communicate with the leader.
Also updated setStage method to use the skipchain service to retrieve the latest block. This should be considerably faster than iterating over all blocks one at a time.
=> evoting: use skipchain service for creating new skipchains and appending blocks

skipchain/api.go, skipchain/api_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
- StoreSkipBlock: Fetch missing blocks when creating backward links
- api.GetUpdateChain: Fix error when verifying whether the update chain
is correct
=> Correctly create backward links and verify update chain

cisc/Reference.md, cisc/cisc.go, cisc/commands.go, cisc/lib.go, cisc/test.sh
This adds the following four commands to `cisc skipchain roster`:
- show - prints the current roster
- add - adds a node (either ip:port or public.toml) to the roster
- remove - removes a node from the roster
- set - sets the roster
Merge this first into #1182, then merge the result into #1181 and finally merge #1181 into master.
=> adding better roster handling

cisc/Reference.md, cisc/cisc.go, cisc/commands.go, cisc/lib.go, cisc/test.sh, identity/api_test.go, identity/service.go
Continuing cleaning up of `skipchain.NewClient` occurrences. Changing my mind on cross-service calls which seem to be OK now.
This can only be merged into #1181 once #1179 is merged into here.
=> don't use skipchain.NewClient

cisc/Reference.md, cisc/cisc.go, cisc/commands.go, cisc/lib.go, cisc/test.sh, identity/api_test.go, identity/service.go, skipchain/skipchain.go, skipchain/skipchain_test.go
Returning `network.Message` in services is evil - it should return the correct message.
This can only be merged into master once #1182 is merged into here.
=> don't return network.Message

external/js/cothority/lib/identity.js, external/js/cothority/package-lock.json, external/js/cothority/package.json
Add an argument to the TOML parsing method and ServerIdentity,
which if set, will set the wsAddr to use wss as the protocol
=> cothorityjs: allow connecting over wss

conode/.gitignore, conode/Dockerfile, conode/Makefile
This PR removes the `vgo` building from the Makefile, as the usage of `.netrc` is not nice for users who simply want to create a docker image.
It also adds the `-dev-YYMMDD` tag to the master-branch, so that the nodes can be easily recognized on status.dedis.ch.
=> Conode: Show dev version and remove vgo

evoting/lib/master.go, skipchain/api_test.go, skipchain/skipchain.go
I added this while working on evoting's GetMaster, but it is a bad
idea, and not needed. Removing it.
=> Remove the "GetSingleBlock id == -1" hack

skipchain/skipchain.go, skipchain/struct.go, skipchain/struct_test.go
Finally merge the changes from byzgen_poc. I didn't keep all the timing-measurements in there. It:
- replaces `findLatest` with `GetLatest`
- adds an optimization by keeping the latest skipblock of a skipchain
=> merging skipchain changes from byzgen_poc

ocs/darc/darc.go, ocs/darc/struct.go, ocs/protocol/ocs.go, ocs/service/api.go, ocs/service/darcdb.go, ocs/service/service.go, ocs/service/service_test.go
Finally merging the changes to onchain-secrets from byzgen_poc. This includes:
- holding darcs in a database instead of a map
- use a SkipChain 10/10 for faster updating
- better stress-test
- improved darc deep copy
- ocs-reencryption failure handling
=> merging onchain-secrets changes from byzgen_poc

evoting/lib/chains.go, evoting/lib/election.go, evoting/lib/transaction.go, evoting/protocol/decrypt.go, evoting/protocol/decrypt_test.go, evoting/protocol/shuffle.go, evoting/protocol/shuffle_test.go, evoting/service/service.go
Optimisations for Mix and Partial operations used within shuffle and decrypt protocol. They now use the skipchain service to get the blocks. The iterations are also performed from the end to search for the Mix or Partial transactions since they're always at the end of the chain in case of a finished election.
=> evoting: use skipchain service in protocol

skipchain/skipchain.go, skipchain/skipchain_test.go
When creating a new skipblock, a copy of the new block and the older blocks have been sent around excessively:
- once in `createForwardLink0`, once in `createForwardLink` and once at the end of `StoreSkipBlock`
- `createForwardLink0` did not sent the latest block, which led to an incoherent state in the db, because the latest block was stored including the forward-link, but this one was pointing towards nothing
Also added some comments and cleaned up the way we prepare for the new block.
=> removing some of the skipblocks propagations that were not needed

conode/.gitignore, conode/Dockerfile-dev, conode/Makefile
Before you could only make images from source fetched via "go get". Now you can use
"make docker_dev" to build from local source.
=> Make it possible to make a Docker image from local files

messaging/propagate.go, messaging/propagate_test.go
Propagation may fail when a child is down. But the old code will wait
for responses dead children anyway. This commit removes this sub-optimal
functionality and node now only wait for the number of children that
successfully received the initial propagation message.
Tests show improvements in timing.
Before:
```
--- PASS: TestPropagation (5.37s)
PASS
ok  	github.com/dedis/cothority/messaging	5.760s
```
After:
```
--- PASS: TestPropagation (2.39s)
PASS
ok  	github.com/dedis/cothority/messaging	2.782s
```
=> Do not wait for impossible responses

bftcosi/bftcosi.go, byzcoinx/byzcoinx.go, byzcoinx/byzcoinx_test.go, evoting/service/service.go, evoting/service/service_test.go, ftcosi/protocol/gen_tree_test.go, ftcosi/protocol/protocol.go, ftcosi/protocol/protocol_test.go, ftcosi/protocol/sub_protocol.go, skipchain/protocol.go, skipchain/skipchain.go
OK - the previous PR got too intrusive and never worked. Time to start fresh...
This puts the timeouts into a much nicer way, supposing that we're mostly network bound, the timeouts are spread out evenly between the leader, the subleaders and the nodes.
Also includes putting `SendToChildren` in go-routines, so that we don't wait for children accepting the connection but not replying.
Finally some logging changes for nicer and more useful outputs.
Depends on dedis/onet#417
=> minimal changes to get the timeouts correct

pop/service/service.go
This has been seen to fail in `v2`. Expect more over time ;)
=> also increasing pop-timeout

identity/struct.go
When using cisc data list -p. It now shows in addition to the proposed data who and how many people voted for the new proposed data.
=> Update the cisc data list display

skipchain/struct.go
Forgot to copy the payload in `SkipBlock.Copy`.
=> also copy payload

evoting/lib/elgamal.go, evoting/lib/transaction.go, evoting/protocol/shuffle.go, evoting/service/service_test.go
The underlying problem comes from issue #1244. The consequence of
that issue is that when a node that was down during some part of the
election fetches all ballots in order to try to verify the first shuffle
proposed by the leader, we end up with fewer ballots than the leader saw.
Having fewer ballots is no big deal, it just means we will refuse to sign
the forward link. Other conodes, which have the full chain, will sign it,
achieving a quorum.
If the election had only 2 ballots, we might trigger panics in the
shuffle library, and this change prevents that from happening.
=> Making e-voting resilient to out of sync chains

external/js/cothority/webpack.config.js
Cothorithy JS suffers from a bug on Safari 10 where the variable scoping is not correctly handled, thus preventing the module from being loaded (see here for more informations : https://github.com/mishoo/UglifyJS2/issues/1753). These flags allow Uglify JS to handle Safari 10 by correctly mangling the file according to this bug.
=> Add support for Safari 10 on CothorityJS

external/js/cothority/lib/net/net.js, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/test/net/net.js
When the retry 3 times code was added, it had the side effect of
hiding the true reason for the error. Expose the last known
error message again.
=> Cothority-js should not bury error strings

conode/Makefile
using `-P` in `docker run` will create a link to a random port on the host, but we need to link to exactly those ports.
=> changing 'docker run -P' to 'docker run -p 6879-6880:6879-6880'

skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
The current implementation of skipchains made assumptions that are not always true when evolving the roster and when some nodes are down. Also rogue nodes could request to insert invalid skipblocks. This PR fixes some of these shortcomings:
- before new skipblocks are stored in the database, an existing block needs to have a valid forwardlink to this new block
- when asking non-0 level forwardlinks, a proof starting at the genesis block is given to prove that the new block is valid
- for any forwardlink, all necessary blocks are transmitted, so that out-of-date nodes or nodes that were offline can correctly verify the new block is valid
**Message incompatibility**
This PR changes the `ForwardSignature` structure that is used when requesting new forwardlinks. Unfortunately this is a …
=> Making skipchain more robust

.travis.yml, bftcosi/bftcosi_test.go, byzcoinx/byzcoinx_test.go, conode/Makefile, cosi/simulation/cosi_test.go, evoting/lib/chains.go, evoting/lib/transaction.go, evoting/protocol/dkg.go, evoting/protocol/dkg_test.go, evoting/service/service.go, evoting/service/service_test.go, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java, ftcosi/protocol/protocol.go, ftcosi/protocol/protocol_test.go, ftcosi/protocol/sub_protocol.go, ftcosi/simulation/local.toml, messaging/broadcast.go, messaging/broadcast_test.go, ocs/docker/Dockerfile, skipchain/protocol.go, skipchain/skipchain.go, skipchain/skipchain_test.go
These are the patches needed in `cothority` to pass the tests after dedis/onet#428. Most of the tests fail now because they have some lingering protocolInstances, but most of them got fixed. Special cases:
- `messages/broadcast`: rewrote it, it was a mess
- `ftcosi`: put the burden on raphael, as he's rewriting it
=> Follow onet 428

Makefile, skipchain/api.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
Closes #1096 
Instead of creating higher-level forwardlinks and waiting on the creation of them, this PR defers this creation, which also allows to create these forwardlinks on a roster where the current node is not present.
=> Defer higher-level forwardlinks

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/kyber/package-lock.json, external/js/kyber/package.json
Update the file format to work with NPM 6, and use the "npm audit" feature to find out of date dependencies and update them. Update cothority to depend on the resulting kyber, 0.0.10.
=> NPM update, dependencies update

external/java/src/main/java/ch/epfl/dedis/lib/omniledger/darc/Darc.java, external/java/src/main/java/ch/epfl/dedis/proto/DarcProto.java, external/proto/darc.proto, omniledger/darc/darc.go, omniledger/darc/darc_example_test.go, omniledger/darc/darc_test.go, omniledger/darc/struct.go
The Path field in Darc is for offline verification, but the existing
implementation uses it as a part of the ID (the digest of the Darc).
Hashing the path does not give us more security because new darcs
already contain the version, base ID and the previous ID.
Update the java and protobuf code as a result of the change.
This work is a prerequisite for evolving darcs in OmniLedger contracts
and access control in the eventlog service.
=> Remove path from darcs

eventlog/buckets.go, eventlog/service.go, omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/struct.go, omniledger/service/transaction.go
Give the contract a form of the collection that only has
Get operations, not Store operations, so that packages which
implment contracts cannot write into the collection except
by returning StateChanges.
=> Contracts should not be able to write into the collection

bftcosi/bftcosi_test.go
To make the tests run again with the latest onet changes.
=> follow latest onet changes

eventlog/api.go, eventlog/el/main.go, eventlog/service_test.go, omniledger/darc/darc.go, omniledger/darc/darc_example_test.go, omniledger/darc/darc_test.go, omniledger/darc/struct.go, omniledger/service/api.go, omniledger/service/api_test.go, omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/transaction.go, omniledger/service/transaction_test.go
This commit adds a simple contract that checks the darc evolution
request. The functionality of Instruction.Action had to be changed to
allow this feature. That is, the darc-action for Invoke does not have
the "Invoke_" prefix anymore. This is unecessary because the re-created
darc.Request in an instruction must match the darc.Request during
verification. If the action in the instruction does match the action in
the darc, then verification will fail.
For example, when client submits an instruction, the client signs the
instruction by creating a darc.Request and then signs the request. The
request will contain instruction.Action, which would be "Invoke__evolve"
in the old implementation. This instruction is sent to the omniledger
service and it does two verification, one in the service …
=> Add contract for darc evolution

eventlog/api.go, external/java/src/main/java/ch/epfl/dedis/lib/eventlog/EventLog.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/Instruction.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/darc/Darc.java, omniledger/darc/darc.go, omniledger/darc/darc_test.go, omniledger/service/api.go, omniledger/service/api_test.go, omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/transaction.go, omniledger/service/transaction_test.go
We are doing the darc verification twice, once before contract
execution, on the request type, and once inside the contract. The
contract trusts the omniledger service, so it only needs to do some
sanity check of the evolution and not the full verification. This change
also allows us to bring back the invoke/spawn/delete namespace.
Further, we change the namespace naming scheme to use colon-seperated
strings from undescore-separated. This is because the action name might
become difficult for humans to read when underscores are used for the
command name.
=> Simplify darc evolution verification in contract

evoting/service/service.go, skipchain/skipchain.go
* setting decrypt/shuffle timeout to 10 minutes
* propagating forward link and last block together to avoid dangling forward links
=> Increase timeout and better propagate blocks

ftcosi/protocol/protocol.go, ftcosi/protocol/struct.go, ftcosi/protocol/sub_protocol.go
The current cosi implementation trusts the leader to correctly calculate the challenge - but this means that the leader could propose any challenge he wants and get the nodes to sign off something they did not verify.
As we're in `v2` non-breaking mode, it will output a warning if it receives a pre-calculated challenge, but still continue. In the best case, it will calculate the challenge.
Closes #1293
=> adding backward-compatible challenge calculation

external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/byzgen/OcsFactory.java, external/java/src/main/java/ch/epfl/dedis/byzgen/User.java, external/java/src/main/java/ch/epfl/dedis/byzgen/UserId.java, external/java/src/main/java/ch/epfl/dedis/byzgen/UserSignature.java, external/java/src/main/java/ch/epfl/dedis/lib/HashId.java, external/java/src/main/java/ch/epfl/dedis/lib/ServerIdentity.java, external/java/src/main/java/ch/epfl/dedis/lib/Sha256id.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519Point.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519Scalar.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Hex.java, external/java/src/main/java/ch/epfl/dedis/lib/darc/DarcSignature.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/InstanceId.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/SubId.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/TransactionId.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/ValueInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/darc/Darc.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/darc/IdentityDarc.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/darc/IdentityX509EC.java, external/java/src/main/java/ch/epfl/dedis/ocs/Document.java, external/java/src/main/java/ch/epfl/dedis/ocs/OnchainSecretsRPC.java, external/java/src/test/java/ch/epfl/dedis/byzgen/GetPathTest.java, external/java/src/test/java/ch/epfl/dedis/byzgen/GrantAccessTest.java, external/java/src/test/java/ch/epfl/dedis/byzgen/OcsFactoryTest.java, external/java/src/test/java/ch/epfl/dedis/ocs/Ed25519Test.java, external/java/src/test/java/ch/epfl/dedis/ocs/OnchainSecretsRPCTest.java, external/java/src/test/java/ch/epfl/dedis/ocs/RestartError.java, external/java/src/test/java/ch/epfl/dedis/ocs/ServerIdentityTest.java
Remove dependency on javax.xml.bind, which is not available in Android
Remove @nonnull, which is not supported in the same way on
Java and Android. See issue #1328.
=> Make our java compatible with Android

conode/Makefile
Windows binaries should be 64-bit (this was already true on
the evoting branch, but was forgotten on tip).
Fixes #1326.
=> Fix windows build

conode/Makefile, eventlog/service.go, omniledger/service/service.go
Fixes #1331.
Also: Remove forgotten LLvl2.
Also: Add missing clean to bindist, which avoids accidentally
getting a different version than expected if something is lingering
in exe/*.
=> Allow timestamps a few seconds into the future

omniledger/service/service.go, omniledger/service/transaction.go
If the state changes are very big, they flood the logs, for example when
doing a stress test. Change it so that we do not log the value part of
the state change.
=> Reduce statechange logging

omniledger/collection/collection.go, omniledger/collection/collection_test.go, omniledger/collection/getters.go, omniledger/collection/getters_test.go, omniledger/collection/manipulators.go, omniledger/collection/manipulators_test.go, omniledger/collection/navigators.go, omniledger/collection/navigators_test.go, omniledger/collection/node.go, omniledger/collection/proof.go, omniledger/collection/proof_test.go, omniledger/collection/record.go, omniledger/collection/record_test.go, omniledger/collection/singlenode.go, omniledger/collection/singlenode_test.go, omniledger/collection/transaction_test.go, omniledger/collection/update_test.go, omniledger/collection/verifiers_test.go, omniledger/service/service.go, omniledger/service/struct.go
- Add mutex on collection: 
Previously the mutex was on the nodes, which meant that race conditions
is still possible in other parts of the collection. This change removes
that and adds mutex on collections.
- Pass around collections as reference:
If we pass collections around as value, then the mutex changes and we'll
have reace conditions.
=> Collection mutex

omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go
We give the owners of the genesis darc the ability to update the
configuration. The next step is to update the roster and eventually do
view-change.
Closes #1319
=> Add invoke to ConfigContract to update ChainConfig

omniledger/service/api.go, omniledger/service/contracts.go, omniledger/service/proto.go, omniledger/service/service.go, omniledger/service/service_test.go
We add roster to ChainConfig, so that it is possible to change the
roster via the config contract. Changing the roster currently can only
be done via the client, we will add a way to rotate the roster
automatically (view-change) next.
=> Include roster in ChainConfig

external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/OmniledgerRPC.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/DarcInstance.java, external/java/src/test/java/ch/epfl/dedis/lib/omniledger/OmniledgerRPCTest.java, omniledger/contracts/value.go, omniledger/contracts/value_test.go, omniledger/service/service.go
Value-contract uses `DeriveID` now
java:spawnContractAndWait uses `deriveID` now
=> Using deriveID

omniledger/service/service.go, skipchain/skipchain.go
OmniLedger does not have the same propagation timeout as skipchain when
using the same propagation protocol. This commit sets these timeouts to
be the same. Further, we set the polling timeout to be half of the block
interval, so that the other half can be used for processing
transactions.
=> Set skipchain propagation timeout in OmniLedger

external/java/src/test/java/ch/epfl/dedis/ocs/Ed25519Test.java, external/js/cothority/test/skipchain/build/.gitignore, omniledger/collection/getters.go, omniledger/collection/node.go, omniledger/collection/proof.go, omniledger/contracts/coins.go, omniledger/contracts/coins_test.go, omniledger/contracts/service.go, omniledger/ol/main.go, omniledger/service/api.go, omniledger/service/collect_tx.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/simulation/.gitignore, omniledger/simulation/coins.go, omniledger/simulation/coins.toml, omniledger/simulation/plot_sim.py, omniledger/simulation/simul.go, omniledger/simulation/simul_test.go
This is the follow-up of #1323 
This adds a coin-contract with the following possibilities:
- `Spawn` to create a new account with a 0-balance
- `Invoke:transfer` to transfer coins from one to another account
- `Invoke:mint` to create new coins (must be protected by a darc)
In addition to this, a simulation allows for testing the performance of the contract.
=> adding a coin contract together with the simulation

omniledger/simulation/coins.go
This fixes jenkins failures. Reason for the change is:
```
// We wait a bit before closing because c.GetProof is sent to the
// leader, but at this point some of the children might still be doing
// updateCollection. If we stop the simulation immediately, then the
// database gets closed and updateCollection on the children fails to
// complete. 
```
=> Add some delay to the end of coin simulation

omniledger/collection/collection.go, omniledger/collection/collection_test.go, omniledger/collection/proof.go
If not mistaken, the label is the contains the root hash and not the key, because it is updated on after every `collection.Add`.
Closes  #1274
=> Correctly return merkle root

omniledger/service/struct.go, omniledger/service/struct_test.go
Closes #1363
Further, we change collectionDb and CollectionView API to return `[]byte` for contract ID, because the lower-level API do not know about how the application is going to interpret the data, so it should not do any conversion and let the high level code handle it.
=> Remove getValueContract code duplication

pop/service/service.go
Previous check if the node is in the roster was in the propagation function,
which is now only called on the first node. This PR adds the check
for every call to 'StoreConfig'
=> pop check if roster

skipchain/skipchain_test.go
The test itself was correct, but incomplete. When the genesis block is
added, no verification function is called, as no signature is generated.
Only the second block will have a verification function called.
=> Fixing Registration test

omniledger/service/service.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
We add a callback, which is executed everytime when a skipblock gets
stored. This feature is to reduce the number of round trips in
omniledger needed to store and update its state.
=> Add StoreSkipBlock callback

omniledger/service/service.go, omniledger/service/transaction.go, omniledger/service/transaction_test.go
Transactions are re-ordered in createNewBlock, which means that if we
cache the state changes in startPolling, then the cache will be invalid
in createNewBlock.
Depends on https://github.com/dedis/cothority/pull/1388
=> Do not re-order transactions

external/java/src/main/java/ch/epfl/dedis/lib/omniledger/InstanceId.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/OmniledgerRPC.java, omniledger/service/api.go, omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/transaction.go
Simplify everything by storing the config data at the zero instance
instead of in an adjacent one. This is now possible because we store
the darc ID with the config data.
Fixes #1390.
=> Remove DeriveConfigID

external/js/cothority/lib/net/net.js, external/js/cothority/package-lock.json, external/js/cothority/package.json
A portion of code was added in CothorityJS to handle a special bug in the NativeScript websockets on Android. Now that the module has been fixed, this code is not necessary anymore and makes CothorityJS crashes on the last version of nativescript-websockets.
Closes dedis/student_18_xplatform#73
=> Remove needless code in CothorithyJS 

omniledger/service/collect_tx.go, omniledger/service/collect_tx_test.go, omniledger/service/service.go, omniledger/service/service_test.go
We give nodes that were previously down the ability to catch-up to the
latest state. This is done by modifying the getTxs callback used in the
CollectTx protocol to take an additional argument - the latest
skipblock ID. When called, the node will check whether they are up to
date, if not, they'll attempt to synchronise with other nodes.
An earlier implementation maintained its own "background process" to
periodically try to catch-up. It has better encapsulation, but makes
extra communication and requires a lot more code change. Hence,
the piggybacking technique is used.
=> Piggyback getTxs to sync omniledger state

omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/statechange_cache.go
Previously, if a tx is removed because it is bad, the
state changes generated by the remaining tx's would be
cached under the wrong key. The result would be that
an attacker could disable the state change caching by
intentionally sending invalid transactions.
This was found by code inspection, but then I decided
to prove it was really happening by adding the hit/miss
monitoring mechanism.
=> Fix state change caching in the case of bad tx

omniledger/simulation/coins.go
Without this change the simulation may fail for a large number of nodes.
Further, we remove the final sleep because updateCollection is gone and
it is now a callback in skipchain.
=> Wait for nodes to finish propagation in simulation

omniledger/darc/darc.go
We, at LCA1, are using Omniledger to store access control rights for sensitive medical data as a part of the MedChain project. Given the nature of this project, we need to be able to evaluate multiple DARC expressions from a contract's code. 
So it would be great if the functions evalExpr() and evalExprWithSigns() were to be made public.
=> Make evalExpr() and evalExprWithSigns() public in the darc package

eventlog/api.go, eventlog/service.go, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/Instruction.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/EventLogInstance.java, omniledger/Contracts.md, omniledger/contracts/value.go, omniledger/contracts/value_test.go, omniledger/service/transaction.go, omniledger/simulation/coins.go
In accordance with the (new) documentation on DeriveID, it should
ONLY be used inside a contract that needs to create new keys to
store additional information. All other instance ID's should come
from spawning new instances, and those should be inst.Hash().
The ida for DeriveID came from the legitimate need of eventlog
to get keys to store its time buckets. So it is still using
DeriveID.
Remove deriveId from Java, since if contracts are using
it correctly (i.e. only for their own use) then Omniledger
clients will never need to look up those keys.
=> Remove DeriveID as much as possible

conode/Dockerfile-dev, evoting/service/service.go, identity/api_test.go, identity/db.go, identity/db_test.go, identity/service.go, identity/service_test.go, ocs/service/service.go, omniledger/service/service.go, pop/service/service.go, skipchain/skipchain.go
First shot at adding a database versioning for the Identity and the OmniLedger
services. The idea is to add an additional bucket with an integer in it, that
can be used to get older versions of the database. In the Identity service,
`db.go` holds an example that does try different versions before giving up.
This depends on dedis/onet#464
=> Database Versioning

.travis.yml, Makefile, eventlog/api.go, eventlog/service.go, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/Instruction.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/EventLogInstance.java, external/java/src/test/java/ch/epfl/dedis/lib/omniledger/OmniledgerRPCTest.java, omniledger/contracts/coins.go, omniledger/contracts/coins_test.go, omniledger/contracts/value.go, omniledger/contracts/value_test.go, omniledger/service/api.go, omniledger/service/contracts.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/struct.go, omniledger/service/transaction.go, omniledger/simulation/coins.go, omniledger/simulation/coins.toml
There were a couple of things astray in Omniledger land:
- verification of signatures on instructions were done _after_ the contract has been run
-> verification of signatures is done in contracts, so they can do whatever seems fit
- instructions sent to an instance didn't call that instance if it was a 'spawn' instruction
-> all instructions call now the instance in the 'InstanceID' field
-> fixed tests that sent instructions to non-existent instances
- followers didn't verify the signatures of instructions
-> verification is done in contracts, so this is taken care of
- updated java and added `deriveID` again
=> Updating Omniledger to behave

omniledger/service/service.go, omniledger/service/service_test.go
Correctly check the DataHeader when verifying a new skipblock
Fixes #1427.
=> Correctly check the DataHeader when verifying a new skipblock

external/java/src/main/java/ch/epfl/dedis/lib/Sha256id.java, external/java/src/main/java/ch/epfl/dedis/lib/SkipBlock.java, external/java/src/main/java/ch/epfl/dedis/lib/SkipblockId.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/ClientTransaction.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/InstanceId.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/Instruction.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/OmniBlock.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/OmniledgerRPC.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/Proof.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/EventLogInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/omniledger/contracts/ValueInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/skipchain/ByzcoinSig.java, external/java/src/main/java/ch/epfl/dedis/lib/skipchain/ForwardLink.java, external/java/src/main/java/ch/epfl/dedis/proto/CiscProto.java, external/java/src/main/java/ch/epfl/dedis/proto/CollectionProto.java, external/java/src/main/java/ch/epfl/dedis/proto/DarcOCSProto.java, external/java/src/main/java/ch/epfl/dedis/proto/DarcProto.java, external/java/src/main/java/ch/epfl/dedis/proto/EventLogProto.java, external/java/src/main/java/ch/epfl/dedis/proto/NetworkProto.java, external/java/src/main/java/ch/epfl/dedis/proto/OCSProto.java, external/java/src/main/java/ch/epfl/dedis/proto/OmniLedgerProto.java, external/java/src/main/java/ch/epfl/dedis/proto/OnetProto.java, external/java/src/main/java/ch/epfl/dedis/proto/PoPProto.java, external/java/src/main/java/ch/epfl/dedis/proto/SkipchainProto.java, external/java/src/main/java/ch/epfl/dedis/proto/StatusProto.java, external/java/src/test/java/ch/epfl/dedis/lib/omniledger/OmniledgerRPCTest.java, external/proto/darc.proto, omniledger/service/service_test.go
Added missing java API calls for OmniLedger structures.
Added some more documentation.
- Make sure all `omniledger/contracts` correctly make use of `sendTransactionAndWait` instead of `sleep`ing.
- `sendTransactionAndWait` should throw `CothorityProcessingException` if transaction has not been included, and `CothorityCommunicationException` if network fails.
Closes #1407
=> Improved java API

omniledger/service/proof_test.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/struct.go, omniledger/service/struct_test.go
The last applied block index should be kept alongside the data
itself, not in a runtime state structure that will be lost on
server restart.
Fixes #1425.
=> Keep block index with the database

libtest.sh
I'm not sure why co* and cl* were removed, but bring them back fixes the pop integration test.
=> Cleanup cl* and co* files

messaging/propagate.go, omniledger/service/service.go, omniledger/service/service_test.go, skipchain/skipchain.go
When Server.Close is called, the skipchain sometimes tried to finish
transactions and start new ones. This is fixed by adding a
TestClose method to the skipchain service.
The propagation protocol did not correctly handle errors, which is fixed
by always returning how many actual confirmations we get, even in the
case of errors.
=> Fix Closing in Test

omniledger/service/service.go
Fix a missing unlock which may cause deadlock when calling TestClose
more than once.
=> Unlock close mutex

external/java/src/test/java/ch/epfl/dedis/lib/omniledger/contracts/EventLogInstanceTest.java, ftcosi/protocol/sub_protocol.go, omniledger/README.md, omniledger/service/contracts.go, omniledger/service/heartbeat.go, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/viewchange.go, omniledger/viewchange/viewchange.go, omniledger/viewchange/viewchange_test.go
The new version of view-change replaces the previous version, which had
difficulty handling corner cases.
The design is similar to the view-change protocol in PBFT (OSDI99). We
keep the view-change message that replicas send when they detect an
anomaly. But we replace the new-view message with the ftcosi protocol
and block creation. The result of ftcosi is an aggregate signature of
all the nodes that agree to perform the view-change. The signature is
included in the block which nodes accept if the aggregate signature is
correct.
The technique above enables nodes to replay blocks to compute the most
up-to-date leader, which was not possible with the previous
implementation. Additionally, we are able to tolerate multiple failures,
which was also not possible previously. Finally, we enable …
=> Implement view-change.v2

.travis.yml, omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/struct.go, omniledger/service/transaction.go, omniledger/service/viewchange.go
Using `go test -run WaitInclus -count 100 -failfast`
let us flush out lots of reliability problems, especially
related to start/shutdown, and to fast block pace.
Also: Try to turn on travis caching, see if it is helpful or
annoying.
=> Omniledger stability improvements

omniledger/darc/darc.go, omniledger/service/contracts.go, omniledger/service/service_test.go, omniledger/service/transaction.go
This change un-disables a test that I wrote in the past
to prove a problem existed. Recent changes fixed this problem
so now we'll re-enable this test. Doing so uncovered other
problems with how Delete is implemented, which are fixed here.
Fixes #1379.
=> Test instructions that depend on each other

eventlog/api_test.go, omniledger/ol/main.go, omniledger/service/api.go, omniledger/service/api_test.go, omniledger/service/service_test.go
Retrieving the GenesisDarc directly when creating a DefaultGenesisMsg is useful when accessing the api.
Before merging: change commit-base in #1457
=> Adding GenesisDarc to Omniledger.Client

external/java/src/main/java/ch/epfl/dedis/lib/status/StatusRPC.java, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java, external/java/src/test/java/ch/epfl/dedis/integration/ManualTestServerController.java, external/java/src/test/java/ch/epfl/dedis/integration/TestServerController.java, external/java/src/test/java/ch/epfl/dedis/lib/status/StatusRPCTest.java
Instead of using ps to count the number of conodes, make a status
request to make sure it is online.
=> Add status RCP call

conode/conode.go, conode/experimental.go, evoting/protocol/decrypt.go, omniledger/service/service.go, pop/service/api.go, pop/service/api_test.go, pop/service/contract.go, pop/service/proto.go, pop/service/service.go, pop/service/service_test.go, pop/service/struct.go, skipchain/protocol.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, stable/directories
Adding pop-contract First step in having pop in omniledger by adding a simple contract that can save the party-proposition and the final statement. Once the final statement is accepted, the contract will create a new coin-account for every attendee of the party.
Before merging: change commit-base in #1460 
Please also squash this PR.
=> Adding pop-contract - depends on #1463

omniledger/service/service.go, omniledger/service/service_test.go, omniledger/service/viewchange.go, omniledger/viewchange/viewchange.go, omniledger/viewchange/viewchange_test.go
There is a bug that might cause new-view messages not being sent when an
anomaly is the last to arrive. This is fixed and is covered by
regression tests. Further, we fix some flakiness in the omniledger
service tests by waiting for skipblocks to finish propagating before
trying to close.
=> Fix view-change bug and enable it

calypso/service_test.go, omniledger/service/proof.go, omniledger/service/service.go, omniledger/service/service_test.go
The previous technique of looking back to find the correct skipblock
does not work. We still have the inconsistency problem collection versus
skipchain DB. So remove the attempt to find the right skipblock and add
a sanity check.
=> Get proof sanity check

.travis.yml, byzcoin/service.go, cosi/client.go, ftcosi/client.go, scmgr/app.go
Go 1.11 is more careful about detecting % strings, and we had some mistakes.
=> Fix Go 1.11 build break.

external/java/src/main/java/ch/epfl/dedis/lib/SkipBlock.java, external/java/src/main/java/ch/epfl/dedis/lib/byzcoin/Block.java, external/java/src/main/java/ch/epfl/dedis/lib/byzcoin/ByzCoinRPC.java, external/java/src/main/java/ch/epfl/dedis/lib/byzcoin/Subscription.java, external/java/src/test/java/ch/epfl/dedis/lib/byzcoin/ByzCoinRPCTest.java
Implementation of the subscription to new SkipBlocks. Every SkipBlock can easily be transformed to a ByzCoin-`Block` and from there the `ClientTransactions` can be retrieved and looked if they are new.
Closes #1402
=> Transactions 1402

external/Makefile, external/clean_proto_deprecation.sh, external/java/src/main/java/ch/epfl/dedis/byzgen/EpflPermission.java, external/java/src/main/java/ch/epfl/dedis/eventlog/EventLogInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/ByzCoinProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/Calypso.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/CiscProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/CollectionProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/DarcProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/EventLogProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/OnetProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/Personhood.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/PoPProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/SkipchainProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/StatusProto.java, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java
Fix Java build warnings
One thing to note is the script to clean the Protobuf generated code. I made it that way because it's the solution with the less impact but we should consider a more final solution like using proto3 or spending some time to fix this in the Protobuf repository. Let me know if you see a better way.
=> Java warning 1325

calypso/api.go, calypso/api_test.go
A small patch to the Calypso API [PR#1526](https://github.com/dedis/cothority/pull/1526)
where a function WaitProof is created.
=> Add WaitProof to Calypso API

external/java/src/main/java/ch/epfl/dedis/byzcoin/Block.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/ValueTest.java
Proposition from ByzGen to rename this method and make it clear that there is a `getTxResults` method, too.
=> renaming Byzcoin.Block.getClientTransactions to getAcceptedClientTransactions

external/java/src/main/java/ch/epfl/dedis/byzcoin/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/darc/Darc.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/AuthorizationTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/DarcTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/ValueTest.java, external/java/src/test/java/ch/epfl/dedis/byzgen/GrantAccessTest.java
The Darc.copy method does not make a full copy, so update the
documentation and function name to reflect it.
=> Improve documentation for Darc.copy

byzcoin/service.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
This PR removes the view change flag because we use the roster of the source block which means that we cannot allow a different roster to sign the forward link even if it's a rotation. No fix to the mask during the verification is necessary as the failing nodes are already ignored in the signature mask, in the correct order.
Fixes #1538
=> Remove view change flag

byzcoin/service.go, byzcoin/service_test.go, calypso/service_test.go
Doing TestClose and then startAllChains may take longer than the block
interval, which will cause an unintentional view-change in tests that do
not expect it. So increasing the block interval for those tests.
In addition, we add some more delay for the calypso benchmark to make
Jenkins happy.
=> Increase block interval for failure tests

byzcoin/proof_test.go, byzcoin/service.go, byzcoin/statetrie.go
In general, it's better to return the structure than to return an interface.
Here in special, because the return value can be nil. As such, we will return
a nil interface, which is not equal to nil...
=> Don't return interface

byzcoin/service.go
Because we were not using database versions until now, this is
a bit hacky. But future migrations on boot will be easier since
there is now a clear way to detect them and a place to put them.
=> Refuse to start ByzCoin with an old-style database

external/clean_proto_deprecation.sh, external/java/src/main/java/ch/epfl/dedis/lib/proto/AuthProxProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/ByzCoinProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/Calypso.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/CiscProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/CollectionProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/DarcProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/EventLogProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/OnetProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/Personhood.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/PoPProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/SkipchainProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/StatusProto.java, external/java/src/main/java/ch/epfl/dedis/lib/proto/TrieProto.java
This fixes the bash script that replaces the deprecation
in the Java proto files to work on Linux and MacOS
Fixes #1563
=> Proto files deprecation script

pop/test.sh
Following changes in pop/service.go that keeps propositions even once
they have been read.
=> Fixing pop integration test

external/js/cothority/lib/byzcoin/darc/IdentityEd25519.js
The javascript-definition of the identity had an error when
returning a protobuf-structure.
=> Identity Ed25519

byzcoin/service.go, byzcoin/service_test.go
This adds a check to prevent from creating a state trie for a
genesis block if it has already been created.
Fixes #1567
=> Fix state trie already exists error

byzcoin/service_test.go
Jenkins fails on the TestService_SetConfigInterval test. Probably because we may send the transaction just before the root decides to create a block. As a result, the block doesn't take very long to be created. So we relax the constraint a bit.
=> Make the set interval test work for Jenkins

byzcoin/service.go, byzcoin/transaction.go, pop/app.go
We used DeriveID on the instruction to calculate the instance ID, but
that is not correct because the instruction later gets modified to
include a signature. This issue should be fixed by this PR.
Fixes Jenkins failure too.
=> fix: PopParty instance not calculated correctly

byzcoin/service.go, byzcoin/struct.go, byzcoin/struct_test.go, skipchain/struct.go, skipchain/struct_test.go
This removes the String function that was causing bad
formatting when using "%x".
It also fixes a data race in the state change storage.
Fixes #1575
=> Fix skipblock ID string representation

byzcoin/service_test.go, skipchain/api.go, skipchain/skipchain.go
This PR fixes two tests randomly failing on Jenkins during the long tests.
TestService_SetConfigRosterNewNodes was failing because some conodes were still catching up after joining the cothority. A round of tx has been added to each new conode.
TestService_FloodLedger was failing because the GetUpdateChain was buggy with negative parameters.
Hopefully Jenkins will be stable after this PR, at least it's working fine on a different job.
Fixes #1584
=> Fix jenkins long tests

byzcoin/service.go, skipchain/api_test.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
This changes the way the skipchain is propagating new block and
forward links so that it sends minimal information and let conodes
ask for missing data.
Fixes #1395 #1213 #1201
=> Skipchain propagation optimization

byzcoin/service.go, byzcoin/trie/trie.go
The locking and waitgroup counting in Byzcoin was a bit off - fixed.
The errors returned when loading a trie were uncomprehensible when printed on the command line - fixed.
=> Cleanup Locking and Errors

byzcoin/heartbeat.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/viewchange.go, skipchain/skipchain.go
Previously, the block-poller and the viewChangeMonitor have not been correctly
started/stopped when a node joined or left a roster of a ByzCoin. Now
they are correctly started/stopped, so that a full change in the roster
is possible.
Closes #1608
=> Correctly keeping track of poller and viewChangeMonitor

byzcoin/contracts.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go
Whenever the `ChainConfig` gets a new roster, the `invoke:view_change` rule needs to be updated with the list of public keys that are now allowed to create a view change.
An alternative would be to not do this using the darcs, but allow `invoke:view_change` directly based
on the roster. But that seemed to adventurous...
Also fixes a bug in `TestService_StateChangeStorage`.
Closes #1607
=> Updating invoke:view_change rule

external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java
It was confusing why we have configurations for 7 conodes but only start
4. So add a comment to explain why.
Fixes #1618
=> Clarify why we use 4 conodes in java test

byzcoin/api_test.go, byzcoin/service.go, byzcoin/service_test.go
Two input testings added:
- `byzcoin.AddTransaction`: verify if the transaction is for a byzcoin this node is part of
- `byzcoin.createStateChanges`: verify if the instance exists or not depending on create/update/remove
=> Adding input testing

byzcoin/trie/proof.go
Move the length check before trying to indexing the interior nodes to
avoid panic. This issue was noticed when porting this code to Java.
=> Check the length of interior nodes before access

.travis.yml, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java
The logs from the container as a whole are routed to
the logger via withLogConsumer. But for a conode
restarted via exec, the logs need to be fetched by a
callback.
Fixes #1426.
=> Route logs from exec commands to java logger

eventlog/api.go, eventlog/el/main.go, eventlog/el/test.sh
This fixes the eventlog integration test by adding
an option to wait for block inclusion.
The wait block routine doesn't seem to work well on Jenkins and you should anyway be able to know when the event has been sent through because of the signer counter.
=> Fix eventlog integration test

skipchain/long_test.go
This fixes the usage of tags so that the long_test are never run
without the tags parameter. It also removes the short clauses as
the tests won't run on Travis anyway.
=> Fix long_test tag for skipchain tests

byzcoin/service_test.go
This fixes the test with a wrong node by forcing the synchronization
so that the new conode knows about the skipchain.
=> Fix byzcoin test with addTransaction

blscosi/protocol/struct.go, blscosi/protocol/sub_protocol.go
This prevents forged refusals by using a nonce generated by the
subleader instead of the leaf itself.
=> BLS refusal uses nonce as challenge-response

byzcoin/trie/proof.go, external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/Instance.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/Proof.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/contracts/ChainConfigInstance.java, external/java/src/main/java/ch/epfl/dedis/byzcoin/contracts/DarcInstance.java, external/java/src/main/java/ch/epfl/dedis/calypso/CalypsoRPC.java, external/java/src/main/java/ch/epfl/dedis/calypso/LTSInstance.java, external/java/src/main/java/ch/epfl/dedis/calypso/ReadInstance.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteData.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteInstance.java, external/java/src/main/java/ch/epfl/dedis/eventlog/EventLogInstance.java, external/java/src/main/java/ch/epfl/dedis/lib/SkipBlock.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ProofTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/EventlogTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/ValueTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java, external/java/src/test/java/ch/epfl/dedis/skipchain/SkipchainRPCTest.java
Port the proof verification code from go to java. There are no tests that are specific for proofs because we don't have the code to construct those proofs. The proof verification is performed implicitly in EventLog.get and ByzCoinRPC.fromByzCoin.
Fixes https://github.com/dedis/cothority/issues/1440
=> Java trie verification

external/java/src/main/java/ch/epfl/dedis/calypso/Document.java, external/java/src/main/java/ch/epfl/dedis/calypso/Encryption.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/AuthorizationTest.java, external/java/src/test/java/ch/epfl/dedis/byzgen/GrantAccessTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/EncryptionTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/ReadInstanceTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/WriteInstanceTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/Ed25519Test.java
Previously the encryption was done using AES-CBC, which is not
authenticated so that's bad. This PR changes is to use AES-GCM.
Fixes #1488
=> Use AES-GCM to encrypt data on Calypso

byzcoin/service.go, byzcoin/service_test.go, byzcoin/transaction_test.go
Now: If a ClientTransaction with a valid and an invalid instruction comes in, the valid instruction is still applied to the global state, but only on the leader, which breaks the root hash...
Solution: Correctly refuse clienttransaction with one valid and one invalid instruction.
=> Treat Invalid ClientTransaction

external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519Point.java
This PR addresses the first issue in #1493. It does not address the
timing attack the same way as what is described in the issue. Instead,
it uses the randomness technique similar to the Go implementation. If
only one byte decides whether the point is valid (which appears to be
the case in the initial Java implementation). Then the probability of
using SPRNG to find the valid point does not change depending on the
number of bytes that we need to fill. In other words, the expected value
(the timing) is constant, just like the Go one.
Fixes #1493
=> Use randomness in Java embed

calypso/struct.go, external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/calypso/WriteData.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/Ed25519Point.java, external/java/src/test/java/ch/epfl/dedis/KeyAndSignOperationsTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/DarcTest.java, external/java/src/test/java/ch/epfl/dedis/byzgen/GrantAccessTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/SignerX509ECTest.java, external/java/src/test/java/ch/epfl/dedis/lib/crypto/XofTest.java, external/java/src/test/java/ch/epfl/dedis/lib/darc/SignerTest.java
Knowing the secret scalar used to generate `gBar` is a security risk. Instead, we use a deterministic way to embed LTSID to create `gBar`. 
Regarding the use of Bouncy Castle, according to https://keccak.team/software.html it is the only Java keccak/SHAKE implementation that's on maven. There are various implementations on GitHub but it's rather time consuming to access the quality of each one, and none of the ones I looked are on maven.
Fixes #1492
=> Generate gBar from LTSID

external/js/kyber/spec/pairing/point.spec.ts, external/js/kyber/src/pairing/curve-point.ts, external/js/kyber/src/pairing/twist-point.ts
This fixes the test by changing the negative function of
the point to not set t. The _t_ is actually never used so I'm not really sure why it is there at the first place but the issue was caused because it was set to 0 for the negative operation.
Fixes #1681
=> Fix kyberjs test for g2 points

external/docker/Dockerfile, external/java/src/test/java/ch/epfl/dedis/integration/DockerTestServerController.java
Because Travis often fails with the message:
"The job exceeded the maximum log length, and has been terminated."
=> Run conode with log level 1 for java test

ftcosi/protocol/protocol_test.go
Since ftcosi is basically replaced by blscosi, we can shorten its tests
on Travis. Test time reduces from 3 minutes to 34 seconds.
=> Shorter ftcosi tests

skipchain/skipchain.go
I tried looking into how to test this code but I didn't find a nice
way. We need to change StoreSkipBlock to test it. But I'm not aware of a
way to overload the skipchain service to change its StoreSkipBlock
function while keeping everything else working. The service name is used
in the service so just embedding skipchain.Service and then registering
it under a new name won't "just work". We should invest in a "cothority
testing framework" so that we can mock stuff easily.
Fixes #1243
=> Verifier IDs in forward sig should not change

external/java/src/main/java/ch/epfl/dedis/calypso/Document.java, external/java/src/main/java/ch/epfl/dedis/calypso/WriteData.java
It's not possible to tell the exact limit for the data that is stored in
Calypso because it depends on the block size configuration. So we
clarify the documentation and tell the user where to find the block
size.
Fixes #1656
=> Explain Calypso data size

blscosi/blscosi/test.sh, blscosi/service.go, cosi/test.sh, ftcosi/test.sh
This fix the flaky tests for BLS by waiting for conodes
to start.
Fixes #1687
=> Fix integration tests on Jenkins

external/js/cothority/package.json, external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, external/js/cothority/src/skipchain/skipchain-rpc.ts
This PR updates the version to publish pre5 with a fix when verifying a chain of blocks with different roster.
=> Publish cothorityjs pre5

byzcoin/service_test.go
This fixes the test by using bigger intervals so that unrelated overheads and precision should not be the reason for failures.
We have issues with this test for a while and I don't think that testing a block interval of 100ms is really worth as the purpose of the test is to check the interval changes accordingly (and 100ms is not really realistic).
=> Fix block interval long test

byzcoin/service.go, byzcoin/service_test.go
Because it's a big and non-modular function, and the pipeline needs it.
=> Refactor createStateChanges

byzcoin/statetrie.go, byzcoin/statetrie_test.go
The the commit feature was never used before because the staging trie is always thrown away after we propose the block. We need it for the pipeline feature because it can be used as a checkpoint. That is, everything that's not committed could be "rolled back" when an error happens in the pipeline.
=> Implement commit for byzcoin staging trie

skipchain/skipchain_test.go, skipchain/verification.go
This makes sure that a new block will follow the previous static
configuration like the maximum height, the base height, the
genesis ID, etc ...
Fixes #1761
=> Improve standard verification of new blocks

.gitignore, personhood/phapp/test.sh
This disable the test for the moment until the credential instance ID
generation is fixed. It also fixes the resolution of the libtest.sh
file to make the remaining ones working.
=> Disable phapp failing integration test

byzcoin/service.go
A race condition was detected on the catchingUp variable. It is caused
by using different locks in two different functions, so we're actually
not locking the variable if it's used in two different functions. Fix is
to use a single lock.
=> Fix catchingUp race

.travis.yml, byzcoin/service.go, byzcoin/service_test.go, byzcoin/viewchange.go
This fixes the potential crash due to a panic when a view change request is sent with an invalid leader index. It changes the protocol so that negative indices are refused and bigger are reduced modulo the roster length.
=> Fix out of bound leader index in view change

.travis.yml, conode/Makefile
This adds a step to the command that will look for replace in the
go.mod file and exit if any is found.
Fixes #1752
=> Make verify will now make sure there is no replace in go.mod

byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go
This PR moves the restoration of the state change storage to start on boot to recreate the state of the storage (used to clean). It was previously executed after the blocks catch up with the given state trie which is bad. The blocks catch up procedure takes care of creating the state changes for new blocks so we don't need to redo it again after it.
Note: it also cleans the `DecodeWithConstructor` usage to be only `Decode`
=> Fix catch up 1777

byzcoin/service.go, byzcoin/service_test.go, byzcoin/viewchange/viewchange.go, byzcoin/viewchange_test.go
It can happen that a conode gets stuck in the middle of a view change waiting for more requests and the cothority adds one or more new blocks. This fixes the situation by first ignoring invalid requests and by cleaning previous states when a new block is propagated.
Fixes #1583
Note: I moved the view change tests to a separate file
=> Fix out of sync view changes

byzcoin/service.go, byzcoin/viewchange_test.go
There are two situations when this function could be in trouble, a unknown skipchain and a missing latest block. This adds a log to make the difference between the two cases.
Fixes #1613
=> Improve monitor failure error logs

byzcoin/bcadmin/README.md, byzcoin/bcadmin/lib/config.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh, byzcoin/wallet/main.go, personhood/phapp/main.go
The previous version of bcadmin supposed that only the genesis-admin(s)
work on darcs. This PR makes it possible for non-genesis-admins
to create new darcs and to mint their money!
=> Fix BCAdmin to work for non-admins

external/js/cothority/README.md, external/js/cothority/spec/index.spec.ts, external/js/cothority/spec/network/proto.spec.ts, external/js/cothority/spec/support/conondes.ts, external/js/cothority/src/network/proto.ts
Solves issue #1791. 
If an `Url` param is found in the toml file, `getWebSocketAddress()` will use it instead of simply transforming the current server address with a port increment of one.
This PR also adds a test case to check if a docker service is available and changes a strange condition in `spec/support/conondes.ts` that was failing the tests. It also documents how to use `js/cothority` as a local module, which was used in order to check the service against `dedis/student_18_explorer`.
=> Uses URL from ServerIdentity struct (JS only) issue #1791

byzcoin/service_test.go
The test fails due to  #1795. We should enable it when the issue is
fixed.
=> Disable AddTransaction_WithFailure_OnFollower

byzcoin/service.go, byzcoin/service_test.go, skipchain/api.go
This fixes the catch up process that were trying to get blocks from
distant peers where it could get them from the local db.
It also fixes the WaitInclusion test that can 1. panic when the request fails
and 2. fails because of the block interval too small that causes #1813 
Fixes #1795
=> Fix catch up requests when getting latest block

byzcoin/bcadmin/test.sh, byzcoin/service.go, conode/CLI.md, libtest.sh, skipchain/README.md, skipchain/skipchain.go
This PR implements a new function `StoreSkipBlockInternal` which is meant to be used in the case a service is used on the same host as the Skipchain service.~~I also removed a condition in `skipchain/skipchain.go` as discussed.~~
~~Note: I had to update 2 tests in `byzcoin/bcadmin/test.sh` line 95 and 98 that were supposed to pass. This is due to the removal of the condition. I am not 100% confident about the expected behavior now that I removed the condition, so please double check.~~ (Reverted it)
Fixes #1756
=> Fixes #1756 (store new skipblocks when skipchain service is linked)

byzcoin/service.go, byzcoin/service_test.go, byzcoin/tx_pipeline.go, byzcoin/viewchange_test.go, calypso/api.go, calypso/api_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
The collectTx callback can trigger a catch up when necessary but it
could happen that it triggers because of a new block in processing.
This fixes the situation by checking the block buffer before using
the catch up.
Fixes #1813
=> Prevent catch up to trigger when one block away

external/js/kyber/src/index.ts, external/js/kyber/src/pairing/scalar.ts
The scalar interface also should have `marshalSize`, as it's used in some methods, and it's provided at least by the `Ed25519` group.
=> adds marshalSize() to the scalar-interface

calypso/contracts.go, calypso/proto.go, calypso/service.go, calypso/struct.go
Added error handling to the calypso-service to better debug eventual errors.
Export calypso-read and calypso-write contracts for future changes in personhood-spawner.
Added a cost-field to Calypso.ContractWrite, to have paying read-requests.
=> Add error handling to Calypso, export contracts, and add random-source

byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh, byzcoin/contracts/coins.go, byzcoin/proto.go, byzcoin/service.go
byzcoin/bcadmin was missing a lot of error handling, which has been updated.
The 'key' command got '--print' to show the private part of the key.
The 'dump' command got '--verbose' to print some details of the printed instances.
=> add error handling to bcadmin and extend 'key' and 'dump' command

external/js/kyber/package.json, external/js/kyber/spec/sign/bdn/bdn.spec.ts, external/js/kyber/src/sign/bdn/index.ts
This bumps the version of the KyberJS to v3.0.2 and it also fixes
the aggregation of BDN public-keys.
=> KyberJS version 3.0.2

.travis.yml, byzcoin/contracts/coins.go, conode/CLI.md, conode/Dockerfile, conode/Dockerfile-dev, conode/README.md, conode/run_nodes.sh, external/docker/Dockerfile-int, external/docker/Dockerfile-unit
Reverts the change of the coin-contract to be backward-compatible with previous coin-contract.
Fixes Dockerfile(-dev) to use go1.12 (for tls in old linux boxes) and to run ./run_nodes.sh correctly
Closes #1836
=> fixes coin-contract and Dockerfiles

darc/darc.go, darc/darc_test.go
In general, there are two solutions to this problem. The first is to add a depth argument in the recursive call and check that it doesn't become too high. The second is to add a list of visited nodes and check that we don't visit a node in that list. I went for the second solution because picking the depth is tricky. My early implementation using a depth of 10,000 takes 0.3 seconds to return error. Making it too small might prevent legitimate uses. 
Fixes #1308
=> Detect infinite recursive darc delegation

external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java
This changes the test to be much less sensible on the actual block interval that is almost impossible to compute precisely and only verify that the config has changed.
Also: it fixes the updateRoster that can also time out from time to time after we killed one of the subleader
Fixes #1841
=> Fix updateInterval and updateRoster tests in the Java library

byzcoin/contracts/coins_test.go, byzcoin/statetrie.go, byzcoin/trie/dfs.go, byzcoin/trie/staging.go, byzcoin/trie/staging_test.go, byzcoin/trie/trie.go, byzcoin/trie/trie_test.go
This PR implements the ForEach feature in Trie and StagingTrie, similar
to the ForEach in the trie.DB interface. Unlike the one in DB,
Trie.ForEach only considers the leaf nodes.
=> Implement ForEach for Trie and StagingTrie

byzcoin/contracts/coins_test.go, byzcoin/statetrie.go, byzcoin/trie/staging.go, byzcoin/trie/trie.go
This method is needed during the process of creating a new `StagingStateTrie` out of a `ReadOnlyStateTrie`. Here is the scenario:
```go
nonce, err := rst.GetNonce()
sst, err := newMemStagingStateTrie(nonce)
rst.ForEach(sst.Set)
```
Needed for #1837
=> Adds a GetNonce() method on a ReadOnlyStateTrie

external/java/pom.xml, external/java/src/main/java/ch/epfl/dedis/calypso/CalypsoRPC.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java
Yann Gabbud noticed that the existing fromCalypso method was recreating
a ByxCoinRPC which was resulting in many more network round trips than
necessary. Add a new fromCalypso to allow him to correct this problem.
=> Calypso java client optimization

byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/lib/utils.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
This is the first step of using deferred contracts with bcadmin. The plan is to implement the manipulation of contracts in the `bcadmin/clicontracts`* package.
Each contract should be usable on its own. For example, creating a new value contract with `bcadmin contract value spawn --value "myValue"`), but also on its deferred version, where a pipe and a special param (like `--redirect`) is used to redirect the transaction to a deferred contract:
- `bcadmin contract value spawn --value "myValue" --redirect | bcadmin contract deferred spawn`
with this, the value contract is not directly spawned, but the transaction is passed as argument to the spawn of a deferred contract.
**The changes of this PR**:
- Moves utility functions to lib/utils.go
- Adds a new package "clicontracts", which will …
=> Implements the spawn and invoke update of the value contract

personhood/contract_spawner.go, personhood/contract_test.go
Using the new spawner contract in javascript showed up a non-caught error
and a forgotten initialisation.
Adding unit-test for contract.
=> fixes spawner fix

.gitignore
Those are generated during the build and should not be checked in.
=> Ignores the bin folder and .project of external/java

byzcoin/bcadmin/clicontracts/value_test.sh, byzcoin/bcadmin/test.sh
Since I am adding more contracts to `bcadmin/clicontracts`, I think its best to have each contract's corresponding tests within the `bcadmin/clicontracts` folder.
What I did:
- created a new `bcadmin/clicontracts/value_test.sh` file
- Moved the function `testContractValue()` from `bcadmin/test.sh` to `bcadmin/clicontracts/value_test.sh`
This is a small step towards using deferred contracts from bcadmin
=> Refactors the clicontract/value.go test

byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/clicontracts/value_test.sh, byzcoin/bcadmin/main.go, conode/log/conode_co1_7770-190513-1409.log, conode/log/conode_co1_7770-190513-1410.log, conode/log/conode_co1_7770-190513-1411.log, conode/log/conode_co2_7772-190513-1409.log, conode/log/conode_co2_7772-190513-1410.log, conode/log/conode_co2_7772-190513-1411.log, conode/log/conode_co3_7774-190513-1409.log, conode/log/conode_co3_7774-190513-1410.log, conode/log/conode_co3_7774-190513-1411.log, conode/log/conode_co4_7776-190513-1409.log, conode/log/conode_co4_7776-190513-1410.log, conode/log/conode_co4_7776-190513-1411.log, conode/log/conode_co5_7778-190513-1409.log, conode/log/conode_co5_7778-190513-1410.log, conode/log/conode_co5_7778-190513-1411.log
One can now get the value of a value contract with:
`bcadmin contract value get --iid <instance ID>`
We plan to add this to every clicontract. This makes debugging and testing easier.
=> Adds a "get" function to the value clicontract

byzcoin/bcadmin/clicontracts/README.md, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/deferred_test.sh, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
Finally implements the cli version of a deferred contract. I added all the functions except delete of the deferred contract: 
* Spawn:deferred
* Invoke:deferred.addProof
* Invoke:deferred.execProposedTx
Combined with the value contract, we can successfully defer the invocation of a transaction (at least with the value contract yet). Here is a scenario that works:
```bash
➜ ./run_nodes.sh -n 5 -c -t -v 2
➜ export BC_CONFIG=~/GitHub/cothority/conode
➜ bcadmin create -roster ~/GitHub/cothority/conode/public.toml 
➜ bcadmin darc rule -rule spawn:value --identity ed25519:... 
➜ bcadmin darc rule -rule spawn:deferred --identity ed25519:...                                                         
➜ bcadmin darc rule -rule invoke:deferred.addProof --identity ed25519:...        
➜ bcadmin darc …
```
=> Bcadmin: deferred clicontract

byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/contract_deferred.go, byzcoin/contracts/contract_deferred_test.go
If expireBlockIndex is not given, we use `current_blockIdx + 50` as the default value. This gives more flexibility for clients that do not have strong requirements for the expiration of the proposed transaction.
=> Deferred contract: Makes expireBlockIndex optional

external/js/cothority/spec/protobuf/index.spec.ts, external/js/cothority/src/protobuf/index.ts
This adds a function that takes json formatted definition and will
add it to the existing root so that they can be encoded/decoded.
=> CothorityJS: provide API to add proto definition from outside

external/js/kyber/package.json, external/js/kyber/spec/sign/mask.spec.ts, external/js/kyber/src/sign/mask.ts
The previous mask-aggregation misbehaved if one of the public keys was masked.
As the test misbehaved in the same way, it did pass anyway...
This PR makes it behave the same way as in the dedis/kyber library.
Closes #1881
=> fixes the mask-aggregate

personhood/contract_spawner.go, personhood/contract_test.go
Uses the arguments to decide how to behave. Once we have block-versions, this
will be much easier.
=> fixes behaviour for credential-contract

byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/contract_darc.go, byzcoin/contract_deferred.go, byzcoin/contracts.go, byzcoin/contracts/contract_deferred_test.go, byzcoin/contracts/insecure_darc.go, byzcoin/struct.go
This PR contains the side stuff that had to be implemented/refactored in order to use the deferred update_config from bcadmin.
This PR does the following:
- Adds a `VerifyDeferredInstruction(...)` for the Darc and Config contracts
- Fixes a wrong mechanism in the deferred contract when getting contract instances of proposed transactions
- Adds a String representation of a ChainConfig struct
I have another PR ready that depends on this one, which implements the deferred update_config of from bcadmin.
=> Improvements and fix for deferred

skipchain/skipchain.go, skipchain/skipchain_test.go
This cleans the forward links before proposing a block to prevent
old valid forward links to be stored in new blocks.
=> Prevent block with infinite loop

byzcoin/bcadmin/clicontracts/README.md, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/deferred_test.sh, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/clicontracts/value_test.sh, byzcoin/bcadmin/main.go
Until now only the value contract had the "get" method. 
In this PR, I add "get" and "delete" methods to the value and deferred clicontracts.
The get method is particularly convenient for testing. I could one more time verify that a deferred transaction is successfully created by performing a "get" of a proposed transaction after executing `invoke:deferred.execProposedTx`.
I also changed the "--iid" flag to "--instID" for consistency.
=> Adds get and delete methods to clicontracts

byzcoin/bcadmin/clicontracts/README.md, byzcoin/bcadmin/clicontracts/config.go, byzcoin/bcadmin/clicontracts/config_test.sh, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
It is now possible to update the contract config with a deferred transaction. There is a complete scenario in the readme, but here is the main command:
```bash
bcadmin contract config invoke updateConfig --blockInterval 7s \
--maxBlockSize 5000000 \
--darcContractIDs darc,darc2 \
--redirect | bcadmin contract deferred spawn
```
UPDATE:
I added the get method, which displays the latest chain config:
```bash
bcadmin contract config get
```
=> Adds config clicontract with invoke:update_config

external/js/cothority/src/byzcoin/contracts/darc-instance.ts, external/js/cothority/src/calypso/calypso-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts
A common failure in ByzCoin operation is that the instance is created on one node,
and the client asks another node for the proof, which fails, if that other node
did not get the new block yet.
This PR adds a default wait to the SpawnerInstance, and also fixes the
CalypsoWriteInstance which did not have the wait argument.
=> makes SpawnerInstance wait for proofs

blscosi/protocol/protocol.go, blscosi/service.go
This fixes the panic that can occur when the protocol shut down before
the actual start is called because Dispatch is called before Start.
Fixes #1871
=> Fix panic in BlsCoSi

byzcoin/service.go
This is an alternative to the PR that adds a field 'NoVerification' to the
'GetProof' message. As the verification has to be done at the client side
anyway, it is not necessary to verify it in the service call.
Closes #1902
Closes #1903
=> speeds up GetProof by removing verification step

byzcoin/service.go, byzcoin/service_test.go, byzcoin/viewchange.go, byzcoin/viewchange/viewchange.go, byzcoin/viewchange_test.go, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java, messaging/propagate.go, messaging/propagate_test.go, skipchain/skipchain.go
This PR updates the view change to have an upper bound to the timeout value so that situation where the view change is triggered but the signature fails doesn't create a huge timeout.
Also: more verbose log for future debugging
Also: use two locks for catching and trie update
Fixes #1835
=> View change improvement

byzcoin/service.go, eventlog/api.go, eventlog/api_test.go, external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/main/java/ch/epfl/dedis/eventlog/EventLogInstance.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/EventlogTest.java
Implement event streaming in go and java. Under the hood, we still use the old skipblock streaming feature of byzcoin but parse the blocks into events using a handler wrapper. The streaming feature allows the user to stream from blocks in the past. In such cases, we read all the blocks from the one given by the client and then call the handler on those, then we call the handler on the new blocks as before (duplicates are removed in the process).
=> Eventlog streaming

byzcoin/proof.go, byzcoin/proof_test.go, skipchain/protocol.go, skipchain/protocol_test.go, skipchain/skipchain.go, skipchain/struct.go, skipchain/struct_test.go
This adds a check in functions that are following forward-links
to insure that it moves to a more recent block every time and
return an error otherwise.
Also: check forward-links when storing a unknown block.
Fixes #1894
=> Prevent infinite looping when following forward-links

blscosi/protocol/protocol.go, byzcoin/viewchange_test.go, byzcoinx/byzcoinx.go, scmgr/app.go, scmgr/commands.go, scmgr/test.sh, skipchain/api.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
In other words, this PR implements a tool to create missing forward-links by checking that the proof of a given block is the shortest possible and then propagate it to the given roster. If the block ID is a genesis, it will fetch the latest block and use it as the target.
Fixes #1907
=> Optimize block proof

byzcoin/bcadmin/main.go, eventlog/README.md, eventlog/el/README.md, eventlog/el/main.go, eventlog/el/test.sh
- use the bcadmin library for operations in el
- fix integration test (flakiness on jenkins was observed locally too, it should be fixed on this PR)
- the OpenID authentication are untested and left as before, they will be fixed in a future PR
Discussion point:
I copy pasted the key function from bcadmin to el because the keys for logging events need to stay in the el config directory. Alternatively, we tell el the bcadmin config directory by adding a flag (e.g., `--bcconfig`) and remove the `key` function from el. The first approach has nicer UI, but the second approach removes repeated functionality.
=> Make el consistent with bcadmin

eventlog/api_test.go
This forces the goroutine to shutdown before ending the test to prevent a failure on Jenkins.
=> Fix leaking goroutine in eventlog test

authprox/apadmin/test.sh
The eventlog CLI changed, so apadmin needs to be updated to use the new
CLI.
=> Fix apadmin integration test

scmgr/app.go
This makes the use of random identity when fetching information
actually random by using a seed.
=> Use a seed for scmgr for random requests

external/js/cothority/package.json, external/js/cothority/src/darc/identity-ed25519.ts, external/js/cothority/src/darc/identity-wrapper.ts, external/js/cothority/src/darc/signer-ed25519.ts
This fixes the point buffer to be in the protobuf shape as it should
be and correctly casted into a Point when needed.
This revert the changes from #1843
=> CothorityJS: fix ed25519 identity

external/js/kyber/spec/helpers/jsverify.ts, external/js/kyber/spec/sign/schnorr/schnorr.spec.ts, external/js/kyber/src/curve/nist/point.ts
This allocates the buffer filled with zeros instead of an unsafe
allocation that is causing wrong marshaling.
Fixes #1917
=> Fix nist point marshaling

skipchain/skipchain.go, skipchain/skipchain_test.go
This improves the verification of new forward-links by computing
the actual expected height for the distant block.
Fixes #1912
=> Verify the target height in ForwardSignature

byzcoin/bcadmin/clicontracts/README.md, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/deferred_test.sh, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/clicontracts/value_test.sh, byzcoin/bcadmin/main.go
- Updated `--instID` to `--instid`
- Fixes a wrong description of `-darc` parameter for `bcadmin darc rule`
- Removes unnecessary printing of a proposed Tx
=> Cosmetic updates for bcadmin deferred

byzcoin/bcadmin/clicontracts/README.md, byzcoin/bcadmin/clicontracts/config.go, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/deferred_test.sh, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/clicontracts/value_test.sh, byzcoin/bcadmin/lib/utils.go, byzcoin/bcadmin/main.go
Now any transaction can be exported using the `--export` (`--x`) option and the `lib.AddTransactionAndWaitWithOption(..)` method, which automaticaly detects if the global `--export` argument is used.
Note: Test with --export and deferred contract is written but commented because of a bug: see #1938
=> bcadmin: Refactors --redirect to a global --export (-x)

byzcoin/api_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/streaming.go, byzcoin/tx_pipeline.go, eventlog/api.go, eventlog/api_test.go, skipchain/skipchain.go
This fixes the pipeline by cleaning the block buffer so that the tx collection will proceed after a block signature has failed (happening on the leader's side). It also changes the callback to be slightly less restrictive so that the heartbeat won't be missed.
Also: fixes some issues with leaking goroutines when closing
Also: correctly close open streaming connections when closing
=> Fix tx collection after block failure

external/java/src/main/java/ch/epfl/dedis/lib/darc/SignerEd25519.java, external/java/src/main/java/ch/epfl/dedis/lib/darc/SignerX509EC.java
The constructor does not work as expected because the serialize method
puts an extra byte at the front.
=> Clarify SignerEd25519 constructor

byzcoin/bcadmin/main_test.go, darc/darc.go
Removes the darcID, which is useless. Only the base ID is usefull to show.
See #1924
=> Updates darc.String()

external/js/cothority/src/calypso/calypso-rpc.ts
Before: Calypso roster was always the same as the byzcoin roster
Now: Allow for different roster
=> Allow for different calypso roster

conode/conode.go
Currently, `conode setup --non-interactive` doesn't respect given config path (always saved to `$HOME/.config` on Linux) and only allow the creation of nodes with loopback address.
* added `--host` to allow to select host
* use `--config` directly (the default is the same anyway)
* remove a bit of dead code
* "config" and "debug" should be read via `cli.GlobalString`, path was never triggered
* btw, to actually have the wanted check in place, it would be best to have non-interactive as a subcmd
=> conode setup: improve non-interactive mode

eventlog/api.go
This fixes the Go routine leak in the eventlog test in Jenkins.
=> Fix wait group stuck in eventlog if a panic occurs

external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, external/js/cothority/src/network/connection.ts
This PR switches to a next node if the current node returns an error. It
tries to keep the same 'working' node as long as possible.
=> Try other nodes if command fails

byzcoin/bcadmin/main.go
Instead of putting a long `Usage` field, better use the `Description` that is only shown with
```bash
bcadmin link --help
```
=> Nicer description

byzcoin/api.go, byzcoin/api_test.go, byzcoin/bcadmin/clicontracts/config.go, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/lib/utils.go, byzcoin/bcadmin/main.go, byzcoin/contracts/contract_deferred_test.go, byzcoin/proof.go, byzcoin/proof_test.go, byzcoin/wallet/main.go, calypso/service.go, calypso/service_test.go, eventlog/api.go, personhood/contract_popparty.go, personhood/phapp/main.go, personhood/service.go
This fixes the Byzcoin proof attack by making sure the roster provided inside the first link is correct and not tampered. It also adds an API to ask for shorter proofs but the default request keeps asking for the proof from the genesis block so that this proof can be shared among peers.
Also: remove duplication of the proof verification already done by the request API
Part of #1959
=> Byzcoin proof attack

evoting/service/service.go
To be able to track which users have failed to cast votes.
=> Add username to failed Cast operations

external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, external/js/cothority/src/network/connection.ts
When using the cothority-ts in the omniledger-demonstrator I see sometimes a big
lag in the messages, specifically if dedis.nella.org is replying (I love that node
exactly for this reason!)
This PR solves the problem by sending all messages in parallel and returning the first
successful reply. It still tries to fetch all nodes, in case there are multiple
errors.
=> Parallel sending of messages

external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/proto/check-auth.ts
Add TypeScript RPC call corresponding to `byzcoin/api.go:CheckAuthorization`. Most code was written by @ineiti, I just fw the patch.
=> external/js: add CheckAuthorization

external/js/cothority/src/personhood/spawner-instance.ts
In order to merge instructions into one single transaction for speeding up the
creation of a user, this PR creates methods that simply create the instructions
for spawning.
=> Splitting instructions from transactions

byzcoin/service.go, byzcoin/service_test.go, byzcoin/statereplay.go, byzcoin/statetrie.go
This commit implements a workaround for #1982. Instead of doing
transactions atomically, we detect consistency issues on startup and fix
it if possible.
=> Fix consistency issue if any

byzcoin/service_test.go
The race condition is caused by using the internal stateTries map in the
test. Which is fixed by using the appropriate locks in the test.
=> Fix race condition in the repair test

byzcoin/contract_name_test.go, byzcoin/contracts/contract_deferred_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go, byzcoin/tx_pipeline.go, external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/ByzCoinRPCTest.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/NamingTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java
With the new use of the Client-calls, where the same
instruction is sent in parallel to more than one node,
it can happen that the same transaction is proposed
twice in the same block. This removes duplicate transactions
in same and directly following blocks.
Closes #1987
=> Remove duplicate transactions

external/java/src/main/java/ch/epfl/dedis/byzcoin/contracts/NamingInstance.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/NamingTest.java
It's more convenient to have the set and the resolution in the same
class. This is also consistent with EventLogInstance.
=> Resolve name from the naming instance

conode/Dockerfile, conode/Dockerfile-base, conode/Dockerfile-dev, conode/Makefile
Based on #1976.
* use a `Dockerfile-base` containing the common code of `Dockerfile{,-dev}`
* `Dockerfile{,-dev}` depends on a new build arg, `FROM`, describing where to get the base image
* add phony Makefile target `docker-base` which ensure that the base image is build
=> conode/Dockerfile*: avoid code duplicates

byzcoin/collect_tx.go
This log prints a lot of information while the client does nothing.
In my opinion log =< 2 should not print anything if the client doesn't interact with the system.
If this log is valuable but there is already too much things printed at log level 3, then we should move some stuff from log level 3 to log level 4.
=> Changes a log.Lvl2 to log.Lvl3

byzcoin/contract_name_test.go, byzcoin/contracts/contract_deferred_test.go, byzcoin/transaction.go, byzcoin/tx_pipeline.go, external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/java/src/test/java/ch/epfl/dedis/byzcoin/contracts/NamingTest.java, external/java/src/test/java/ch/epfl/dedis/calypso/CalypsoTest.java
The detection of duplicate transactions makes it difficult to test
in the case where you want to prove that
1. the transaction doesn't go through
2. something changes (darc gets updated)
3. the same transaction as in 1 goes through
Using ClientTransaction.Hash, the same transaction can be re-submitted
after a new signature.
Also reverts patches to tests that didn't work with the old duplicate transaction detection.
This _should_ be backwards-compatible, as the test is only done in the leader. So if different version of conodes are available, it might be that sometimes given transactions are rejected as being doubles, and sometimes not...
=> Adding ClientTransaction.Hash

.travis.yml
We stopped checking for go 1.11 build failures, after changing the default to 1.12. This PR adds it back.
=> Build go 1.11 in travis

byzcoin/contract_deferred.go, byzcoin/contracts/coins_test.go, byzcoin/statetrie.go, personhood/contract_test.go
Doing ForEach in the deferred contract might become expensive when the
state grows big. So we introduce StoreAllToReplica that makes a
"lightweight" copy of the trie and then applies the state changes. It
still makes copies of key/values but only those that are waiting to be
committed to a new block.
Closes #1938
=> Implement StoreAllToReplica

external/js/kyber/package-lock.json, external/js/kyber/package.json
Currently, using `@dedis/kyber` with typescript requires to do `npm i -D @types/bn.js` before building. Moving it from `devDependencies` to `dependencies` fixes that. (it was also bumped during that).
Can also someone make a NPM release after merging please?
=> external/js/kyber: add @types/bn.js for users

byzcoin/bcadmin/clicontracts/config.go, byzcoin/bcadmin/clicontracts/config_test.sh, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/deferred_test.sh, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/clicontracts/value_test.sh, byzcoin/contract_deferred.go, calypso/csadmin/clicontracts/lts_test.sh, calypso/csadmin/clicontracts/read_test.sh, calypso/csadmin/clicontracts/write_test.sh
Using `matchOK` performs an exact match contrary to `testGrep`. It should improves the robustness of the tests.
Fixes #2015
=> Use "matchOK" in favour of "testGrep"

byzcoin/api_test.go, skipchain/struct.go
This makes sure the correct function is used to iterate over the
database.
Fixes #2028
=> Fix phantom skipchains when getting byzcoin IDs

byzcoin/collect_tx.go, byzcoin/collect_tx_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/tx_pipeline.go, byzcoin/tx_pipeline_test.go
This updates the transaction collection to include the version of the
Byzcoin protocol of the conode so that the leader can synchronize an
upgrade.
=> Leader detects when to upgrade the byzcoin protocol version

.travis.yml
Nearly full rewrite of `travis.yml`. With magic YAML feature such as anchors to reduce code duplication.
* separate the build by stages, so that we avoid running the tests if the build fails for example ie faster feedback
* ensure that we really support the wanted version of go/js: every job using go is duplicated into 1.11 and 1.12
* dropping support for go 1.10, because it doesn't support modules; for eg, it can't lint the project
* it's easy to add back if wanted, but there isn't currently full support for it
* add deployment to NPM of external/js/{kyber,cothority} on a `dev` tag (the feature I initially wanted when starting this PR)
* IMHO, with this PR, it's easier to read/code/manage `travis.yml`
NB: if you want to actually use the deploy stage, one would need to **set …
=> revamp travis.yml

external/js/cothority/src/network/proto.ts
When cothority-ts is used in nativescript, 'new URL' doesn't work. So I
simplified the ServerIdentity.urlToWebsocket with a simple regexp.
=> Porting urlToWebsocket simplification

calypso/csadmin/README.md, calypso/csadmin/clicontracts/write.go, calypso/csadmin/clicontracts/write_test.sh, calypso/csadmin/commands.go
I found out that I somehow miss-interpreted the use of the `data` and `extraData` fields of a write instance in Calypso.
This PR updates the cli to include the `extraData` option when spawning a write instance and also update the explanations to make the use of `data` vs `extraData` clear.
=> Updates write spawn to include the extraData field

.travis.yml
Currently, there is a hook to avoid pushing new NPM packages with the same content. But there isn't really a stable/safe way to do it. By discussing with @nkcr, we decided to drop this feature because it was already failing for some use cases (push force, new branch, ...).
=> travis: deploy without checking for changes

external/java/src/main/java/ch/epfl/dedis/lib/crypto/bn256/OptAte.java, external/java/src/main/java/ch/epfl/dedis/lib/crypto/bn256/TwistPoint.java
This makes sure that the pool is also used in the pairing operation
when TwistPoints are instantiated.
Fixes #1945
---
=> Java: Use the pool for TwistPoint

byzcoin/contract_darc.go, calypso/csadmin/README.md, calypso/csadmin/clicontracts/read_test.sh, calypso/csadmin/clicontracts/write.go, calypso/csadmin/clicontracts/write_test.sh, calypso/csadmin/commands.go, calypso/csadmin/main.go, calypso/csadmin/test.sh
This PR updates the `--secret` argument to accept hexadecimal encoded string instead of plain string. It is easier to manipulate hexadecimal string via the command line since it does not have special chars that can be accidentally interpreted by the command line, and it makes it easier to reason in term of bytes (in this case a secret must not exceed 29 bytes).
---
=> Csadmin update

personhood/contract_spawner.go
When using the spawner-instance, darcs with spawn:calypsoRead should
be allowed, as they can only be used as instructions to a calypsoWrite
instance that will check if coins are needed or not.
---
=> Allow darcs with spawn:calypsoRead

external/java/src/main/java/ch/epfl/dedis/byzcoin/ByzCoinRPC.java, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, go.mod, personhood/contract_ropasci.go, personhood/contract_ropasci_test.go, personhood/contract_spawner.go, personhood/contract_test.go, personhood/proto.go
When testing the new personhood contracts with bcadmin replay, it showed that they
were not backwards-compatible. This PR fixes the contracts such that all blocks can
be successfully applied to get the current global state.
This increases the `Version` to `2`, so that the spawner-contract can behave correctly in the future.
---
=> Fixes personhood contracts

byzcoin/bcadmin/README.md, byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh, byzcoin/contracts/coins.go, byzcoin/statereplay.go, byzcoin/statereplay_test.go, conode/conode_linux.go, external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, go.mod, go.sum, libtest.sh, skipchain/api.go, skipchain/skipchain.go, skipchain/struct.go
Bcadmin can now also work on the database - either a separate, or a database from
a conode. The following commands are available:
- `db merge` copies the skipblocks from one database to another
- `db catchup` fetches new blocks from the network
- `db replay` applies the blocks from the database to the global state
- `db status` returns simple status' about the internal database
Before a release of a new version, the following commands should be run 
and return success:
```bash
bcadmin db catchup cache.db 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3 https://conode.dedis.ch
bcadmin db replay cache.db 9cc36071ccb902a1de7e0d21a2c176d73894b1cf88ae4cc2ba4c95cd76f474f3 --continue
```
---
=> Check chain

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/src/network/connection.ts
**Simplify `Address || Url -> websocket URL` translation.**
Currently, when using a Roster with servers without `Url`, when using `ServerIdentity.getWebSocketAddress`, the system default to building one from `Address`.
The default protocol used is `ws:` which, when providing js/cothority via `https:`, is killed with some browser (see https://github.com/c4dt/omniledger/issues/143#issuecomment-536920787). But the Roster didn't always provide the `Url` field, so, when following the chain, it happens that some are contacted via unsecure WebSocket.
This PR fixes that by defaulting to `wss:` when missing `Url`, and some other small changes.
* rm unused `static ServerIdentity.{urlToWebsocket,addressToWebsocket}`
* enforce more structure on `Address` and `Url`: they should both be valid URL when …
=> external/cothority: use wss when got via https

.gitignore, .travis.yml, Makefile
**Auto clone dedis/Coding**
To avoid having to explicitly clone Coding before `make`-ing cothority, the `Makefile` now does it by itself.
---
=> Makefile: auto-get Coding

byzcoin/api.go, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/lib/utils.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh, byzcoin/proof.go
Correct `WaitPropagation` to correctly wait for all nodes to be in the same state.
Also `xerrors.Errorf` changes while searching the bug.
Also more error-handling where `err` was not checked.
Closes #2083 
---
=> Fixes some race conditions

external/js/cothority/spec/byzcoin/client-transaction.spec.ts, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/client-transaction.ts
Adds a local cache for the counters that is invalidated if a transaction
fails. This speeds up transactions a lot, because after a short set-up
phase, the counters don't have to be updated anymore.
---
=> speed up counter handling in byzcoin

external/js/cothority/src/personhood/credentials-instance.ts, external/js/cothority/src/personhood/pop-party-instance.ts, external/js/cothority/src/personhood/ro-pa-sci-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts, personhood/contract_popparty.go
The new personhood Rock-Paper-Scissors contract allows to use calypso for
making sure that the 2nd player can finalize the game. This adds the
javascript support for this functionality.
---
=> add calypso ropascis to personhood

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/helpers/global-this.ts, external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/src/network/connection.ts
This changes the logic to instead check the current protocol so that
browser context with a location using HTTPS will always use WSS.
Fixes #2104
---
=> Fix issue with isSecureContext with local content

Makefile
**Small changes to Makefile**
This PR is for allowing small changes PR on Coding to not break, see dedis/Coding#3.
=> Makefile: define EXCLUDE_LINT before include

calypso/api.go, calypso/contracts.go, calypso/csadmin/clicontracts/lts.go, calypso/csadmin/clicontracts/read.go, calypso/csadmin/clicontracts/write.go, calypso/csadmin/main.go, calypso/db.go, calypso/protocol/ocs.go, calypso/protocol/ocs_test.go, calypso/protocol/onchain_test.go, calypso/service.go
Wraps errors using the xerrors package
---
=> calypso: use xerrors

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/test.sh, go.mod
When the chain malfunctions and has a latest block with a dangling forward-link,
bcadmin db resetBlock
can remove that dangling forward-link.
Closes #2118
---
=> reset forwardlinks of latest block

byzcoin/viewchange/viewchange.go, go.mod
The viewchange timeout was not handled correctly in case of very big
numbers. `time.Duration(float64(1e100))*time.Second == 0s`! So the
verification `if duration < 0` was never `true`, and the viewchange
was reset to `0s`!
---
=> Limit viewchange timeout

calypso/csadmin/README.md, calypso/csadmin/commands.go, calypso/csadmin/main.go, calypso/csadmin/test.sh, conode/run_nodes.sh
Adds the `csadmin dkg info` command to print the roster of an lts-instance.
Also adds the `run_nodes.sh -a` option to allow insecure lts creations.
---
=> Add LTS info

byzcoin/viewchange.go, skipchain/skipchain.go
If the block cache is cleaned before the block is stored in the db,
byzcoin might think that the block is missing, when in fact it is
available.
---
=> Clean the block-cache correctly

.travis.yml
Kyber and Cothority JS should not be linked together during a deployment
as it should use existing dependency. Kyber should be upgraded first and
then Cothority can use the new version.
Fixes #2124 
---
=> Remove the link for the deploy stage

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/kyber/package-lock.json, external/js/kyber/package.json
**Allow @dedis/{kyber, cothority} to be imported in typescript land without adding extra deps**
This PR moves `@types/elliptic` from dev deps to user deps, thus allowing theses project to use it with typescript direclty, without having to add its own version of the typing lib. It's also removing the now dangling deps of @dedis/cothority.
When building a project using @dedis/cothority or @dedis/kyber, `tsc` yield:
```
node_modules/@dedis/kyber/curve/edwards25519/curve.d.ts:2:23 - error TS7016: Could not find a declaration file for module 'elliptic'. '/home/tharvik/c4dt/service-drynx/library/node_modules/elliptic/lib/elliptic.js' implicitly has an 'any' type.
Try `npm install @types/elliptic` if it exists or add a new declaration (.d.ts) file containing `declare module 'elliptic';`
2 import …
```
=> external/js/kyber: add @types/elliptic for users

byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go, byzcoin/bcadmin/test.sh
This PR adds a new command `bcadmin instance get` that simply prints the content of an instance if found. 
I also took the opportunity to reformat the "commands.go" file in order to have commands alphabetically sorted. I also made some formatting on the "main.go" file for oversized lines.
---
=> Adds "bcadmin instance get"

external/js/cothority/package.json, external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/src/byzcoin/instance.ts, external/js/cothority/src/calypso/calypso-rpc.ts, external/js/cothority/src/index.ts
Some of the files still imported 'protobufjs' instead of the
light version.
index.ts exports now Log and Logger.
---
=> protobufjs/light and export Log

byzcoin/bcadmin/main.go, byzcoin/messages.go, personhood/contract_popparty.go
There has been a mismatch with the release of the nodes and the spawning of contracts. To keep the chain in a consistent state, the version needs to be updated to version 3, and only then the new darc rule needs to be used.
---
=> Use new darc-rule only in version 3

proto.awk
`proto.awk` doesn't support `float{32,64}`. Now it can.
=> proto.awk: supports floating

external/js/cothority/spec/personhood/credentials-instance.spec.ts, external/js/cothority/spec/personhood/ro-pa-sci-instance.spec.ts, external/js/cothority/src/byzcoin/contracts/coin-instance.ts, external/js/cothority/src/byzcoin/contracts/value-instance.ts, external/js/cothority/src/calypso/calypso-instance.ts, external/js/cothority/src/calypso/calypso-rpc.ts, external/js/cothority/src/log.ts, external/js/cothority/src/personhood/credentials-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts, go.mod
When getting a proof for a transaction without waiting, it is important
to try again, in case the transaction has been sent to node A, and
the proof is asked from node B which doesn't have the block yet.
Also includes a small fix to the `Log` module to respect the stack-depth.
---
=> Waiting for proof

external/js/cothority/src/protobuf/index.ts
`protobuf.addJSON` doesn't support adding already existing namespaces (such as `network`, `skipchain`, `onet`), which happens when adding a model which uses the cothority's models.
=> external/cothority/protobuf: addJSON supports known namespace

.gitattributes, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/personhood/ro-pa-sci-instance.spec.ts, external/js/cothority/src/byzcoin/client-transaction.ts, external/js/cothority/src/byzcoin/contracts/coin-instance.ts, external/js/cothority/src/byzcoin/proof.ts, external/js/cothority/src/calypso/calypso-instance.ts, external/js/cothority/src/darc/darc.ts, external/js/cothority/src/darc/signer-ed25519.ts, external/js/cothority/src/network/proto.ts, external/js/cothority/src/personhood/credentials-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts, external/js/cothority/src/skipchain/skipblock.ts, external/js/cothority/tsconfig.json, external/js/kyber/package-lock.json, external/js/kyber/package.json, external/js/kyber/spec/group/edwards25519/vector.spec.ts, external/js/kyber/src/curve/edwards25519/curve.ts, external/js/kyber/src/curve/edwards25519/point.ts, external/js/kyber/src/curve/edwards25519/scalar.ts, external/js/kyber/src/curve/nist/point.ts, external/js/kyber/src/curve/nist/scalar.ts, external/js/kyber/src/pairing/curve-point.ts, external/js/kyber/src/pairing/point.ts, external/js/kyber/src/pairing/scalar.ts, external/js/kyber/src/sign/schnorr/schnorr.ts, external/js/kyber/tsconfig.json, external/js/types/crypto-browserify/index.d.ts
When using the npms in nativescript, I have to manually change the 'crypto' into
'crypto-browserify'. This change uses a more compatible module
that allows to run the same code in node, the browser, and nativescript.
Depends on #2165 and #2164 
Also updates the version of the npms `@dedis/cothority` and `@dedis/kyber`.
This PR fails, as the `external/js/cothority` already points to the new `@dedis/kyber`.
---
=> Browserify

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, byzcoin/service.go, byzcoin/statereplay.go, personhood/contract_spawner.go
In order to run the 'bcadmin db replay' command on travis with ~30k blocks,
this PR adds a '--summarize' flag that takes as an argument the number of
blocks to summarize before printing statistics about the blocks.
---
=> Nicer replay output

external/js/kyber/spec/pairing/point.spec.ts, external/js/kyber/src/pairing/curve-point.ts
This allows a and this to be the same object and still get a correct
result.
Closes #2172 
---
=> KyberJS: fix curve point double stability

external/js/kyber/spec/pairing/point.spec.ts, external/js/kyber/src/pairing/point.ts
Found another mutability issue, very close to dedis/cothority#2172; adding a test triggering it (spoiler, it's `sub`).
And the fix is simply to `clone` the point before modifiying it.
=> external/kyber: test for BN256 add/sub/neg/mul immutability

external/js/kyber/spec/pairing/point.spec.ts, external/js/kyber/spec/pairing/scalar.spec.ts, external/js/kyber/src/pairing/curve-point.ts, external/js/kyber/src/pairing/scalar.ts
**The modulo for bn256' scalar in typescript is wrong.**
By looking at the [golang implementation of bn256' scalar](https://github.com/dedis/kyber/blob/master/pairing/bn256/group.go#L69), we see that it uses the order (the number of element of a ring) as modulus. In the typescript, it actually uses `p`, not `group`, which gives that addition is not consistent with multiplication when using negatives.
This PR adds a test triggering the issue, and the fix. It also contain a simplification of multiplication for bn256 (which is unrelated, just easier to understand).
Kudos to @ineiti for helping me debug :)
=> external/kyber/bn256: fix order for scalar

external/js/kyber/spec/pairing/point.spec.ts, external/js/kyber/src/pairing/curve-point.ts
-1 is not encoded the same when using `neg` rather than `mul`. Adding a small test for it and a fix (yet, I'm no cryptographer, I don't know if it's correct at all).
I'm using `p` here, as throughout the typescript codebase, see dedis/kyber#412 if you find it weird.
=> external/kyber/bn256: mod after neg

byzcoin/transaction.go
With the change to the new signature scheme, it can happen that the
`ClienTransaction` is missing the version field, and the signing
will use the old version, and finally the verification will fail.
This adds a `log.Warn` if one of the signatures is wrong, and prints
a reference to `byzcoin.Client.CreateTransaction` in that case.
=> Warn if wrong signature

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/byzcoin/byzcoin-rpc.spec.ts, external/js/cothority/spec/byzcoin/stream.spec.ts, external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/contracts/darc-instance.ts, external/js/cothority/src/network/connection.ts
Bringing the wonderful world of rxjs to cothority/byzcoin:
- connection:sendString - uses Observable instead of callbacks
- ByzCoinRPC.getNewBlocks - returns a BehaviorSubject
- ByzCoinRPC.proofObservable - returns a BehaviorSubject of a proof
**It breaks API compatibility for the new WebSocketAdapter.sendStream**
If that is a problem, it's quite straightforward to do the following:
- change `sendStream` to `sendStreamObservable`
- add `sendStream` that behaves like before, but calls `sendStreamObservable`
Readmes:
https://rxjs.dev/guide/observable
https://gist.github.com/staltz/868e7e9bc2a7b8c1f754
=> Observable ByzCoin

external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/src/network/connection.ts, external/js/cothority/src/skipchain/skipchain-rpc.ts
Fixes a limitation introduced by #2196
Right now its impossible to host a conode at an adress that contains a path.
=> Fixes an unwanted limitation on URLs

byzcoin/api_test.go, byzcoin/collect_tx_test.go, byzcoin/service_test.go, byzcoin/statereplay_test.go, byzcoin/viewchange.go, darc/darc_test.go, skipchain/skipchain_test.go, skipchain/struct_test.go
I recently found the `-s` flag to `gofmt`, which simplify code. Running it here gave me some small changes, mostly in tests.
=> gofmt -simplify

byzcoin/bcadmin/README.md, dedis-cothority.toml
Following the recent update of the Roster, bumping the group's config.
Also, bumping the README of bcamin because of the decommissioning of the HTTP server on conde.c4dt.org.
=> byzcoin: move C4DT node to 443

byzcoin/struct.go, external/js/cothority/src/personhood/spawner-instance.ts, personhood/contracts/contract_spawner.go, personhood/contracts/contract_spawner_test.go
Whenever a spawner contract creates a new coin instance, it fills it with all available coins.
This works fine if you only create one coin in a transaction. But if multiple instructions
with multiple spawners are created in the same transaction, it will fail.
This PR adds a new argument when spawning a coin that allows filling of the coin with only
a partial available amount.
@Gilthoniel there is a _real_ unit tests in this PR - it is possible ;)
=> Use coinValue in spawner contract

external/js/cothority/spec/personhood/spawner-instance.spec.ts, external/js/cothority/src/byzcoin/proof.ts, external/js/cothority/src/darc/darc.ts, external/js/cothority/src/personhood/credentials-instance.ts
In the latest dynacred2, there can be a lot of proofs requested when a new block
comes in. The previous code checked the forward-links for every proof, which
made it very slow.
This PR stores the latest trusted block, and doesn't check the forward-links
if a proof with that latest block is received.
Also changes new darcs with `version=0` to have a random `prevID`, enabling
to store a darc with the same rules and description twice under a different
ID.
Also extends the `Credential.setAttribute` method to allow for strings in the value.
=> Speed up proofs

.travis.yml
Running tests twice doesn't make much sense; also, I broke deploy on master by not linking kyber in the previous iteration, so, two birds, one stone.
=> travis: revert to old npm publish

byzcoin/api_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/tx_pipeline.go, go.mod, go.sum, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
Divers races have been fixed:
- between closing down byzcoin/skipchain and calling propagateForwardLinks
- between resetting byzcoin and calling propagateForwardLinks
- added some `local.WaitDone(time.Second)` to the end of some tests to make sure all messages are passed before closing the services
Plus a proposed change to the ill-named skipchain::Service.WaitBlock
Closes #2129
---
=> Fix message races

.travis.yml
Heurm, so, I made a typo in https://github.com/dedis/cothority/pull/2235; here goes the small fix.
This time, the deploy itself has been [tested on travis](https://travis-ci.org/github/c4dt/cothority/builds/666815813).
=> travis: publish -> publish.sh

byzcoin/rostsimul.go, personhood/contracts/contract_credential_test.go, personhood/contracts/contract_popparty_test.go, personhood/contracts/contract_ropasci_test.go, personhood/contracts/contract_spawner.go, personhood/contracts/contract_spawner_test.go
In order to test also other than personhood contracts in a more unit-testing manner,
move the ReadOnlyStateTrieSimulator to the byzcoin directory.
=> Moving StateTrie simulator to byzcoin

byzcoin/contracts.go, byzcoin/service.go, byzcoin/transaction.go, byzcoin/transaction_test.go, calypso/contracts.go, external/js/cothority/spec/calypso/calypso.spec.ts, external/js/cothority/src/byzcoin/client-transaction.ts, external/js/cothority/src/byzcoin/instance.ts, external/js/cothority/src/calypso/calypso-instance.ts, external/js/cothority/src/calypso/calypso-rpc.ts, external/js/cothority/src/skipchain/skipchain-rpc.ts, personhood/contracts/contract_spawner.go
This PR adds the following new features to ByzCoin:
- deleting instances by default: now the BasicContract includes a default 'Delete'
- added preIDs to Instruction: there is now a default way to calculate the preIDs for a contract
- using preIDs in CalypsoContracts: allowing to choose the pre-image of the IDs of the Write and Read Instances
- fixes small bugs:
- missing error handling in executeTransaction
- missing argument strings in calypso-instance.ts
Both the go-code and the js-code have been updated.
=> Adding deletion and preIDs for Calypso contracts

byzcoin/service.go, byzcoin/service_test.go, byzcoin/tx_pipeline.go, byzcoin/viewchange_test.go
Some small improvements to make the tests pass. The viewchange tests are
still flaky - but using the go-test cache, it will eventually pass :(
=> Jenkins failures

conode/run_nodes.sh, scmgr/README.md, scmgr/app.go
The scmgr/README.md was out of date with regard to the rest of the code.
Updated the following to work well:
- conode/run_nodes.sh - build public.toml with first node at beginning
- scmgr/app.go - use leader node and store both forward-link and new block
OR-reviewers: first to think it's OK, please merge...
Closes #2251
=> Fixing README of scmgr

calypso/contracts.go, calypso/contracts_test.go, external/js/cothority/src/calypso/calypso-instance.ts, personhood/contracts/contract_spawner.go
Allow the CalypsoWrite contract to update the Data and ExtraData part of the
Write structure.
Depends on #2240
=> Calypso update

byzcoin/README.md
I already lost a lot of time on this issue and that just happened to someone else. In particular it produces an error hard to debug since it just says that nodes can't reach a consensus.
=> Adds a warning about using maps in contracts

byzcoin/service.go, byzcoin/viewchange.go, byzcoin/viewchange/viewchange.go
This patch fixes the initialization of the viewchange when the node
starts up: instead of calculating 'f' from the genesis-block, it
looks up the latest block and calculates 'f' from this one.
=> Another fix for the viewchange

byzcoin/api_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go
Currently GetUpdates returns an error if it is queried for an unknown instance.
This is not correct, as instances can disappear. 
It should either ignore them, or return a proof of missing instance.
Both is possible now, depending on the flag sent to GetUpdates.
=> Ignore non-existing instances in GetUpdates

external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/client-transaction.ts, external/js/cothority/tsconfig.json
This PR adds error-handling and an improvement of updating the cached
instances by sending a grouped update-request to ByzCoin.
This allows the web-client to have a quick first value of an instance
which might be outdated, and then receive a new value as soon as it's
available.
=> Update cached instances when new blocks arrive

byzcoin/service.go, byzcoin/viewchange.go, byzcoin/viewchange/viewchange.go, byzcoin/viewchange/viewchange_test.go, byzcoin/viewchange_test.go
This implements the fix described in #2267
Also removes code from viewchange that made it go forward too fast. Which _might_ break viewchanges in real life :(
Closes #2267
=> Fix viewchange threshold

byzcoin/contracts.go, byzcoin/messages.go, byzcoin/viewchange.go, byzcoin/viewchange/viewchange.go, byzcoin/viewchange/viewchange_test.go
As @LefKok validated #2264, this PR removes the BLSCoSi round for the view-change. This makes it faster and simpler.
One more idea would be to avoid the view-change requests completely. But that will break even more stuff. So let's start small...
=> Removing the BLS signature from the view-change

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/main.go
I'm not sure this should really go in or not. Once
```
bcadmin remove block
```
is called, the internal state of the node will not be correct anymore
with the state stored in the trie. Probably it's better to just
scrap the db and start fresh.
=> Adding bcadmin remove block

byzcoin/proof.go, byzcoin/service.go, byzcoin/viewchange.go, skipchain/struct.go
Two small patches for byzcoin:
- on 14th of May, another split occured, with higher-level forward-links pointing to
one block, and lower-level to another block. After restarting the nodes, it was still
in an unstable state, as the lower-level links led to another block than the higher-
level links. This patch makes sure that higher-level links that lead to nowhere are
removed from the db.
- part of the code spanned a lot of 'bbolt.Bucket's. This is fixed, and a method is
added to clean up
=> Patch up split and db

external/js/cothority/src/network/websocket.ts
When the websocket gets an error, even if it is empty,
it should be reported.
=> Correctly report error

byzcoin/bcadmin/README.md, byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/test.sh, byzcoin/contracts.go, byzcoin/service.go, byzcoin/statereplay.go, byzcoin/statereplay_test.go
This PR does the following for 'bcadmin db replay':
- clean up the different backward-compatible but used nowhere extensions of `StateReplay`
- add all blocks to the skipchain.db, so that contracts using 'ReadOnlySkipchain' work
- by default doesn't verify the forward link signature of blocks, as this is very costly,
and can be supposed to be correct if its in 'cached.db'
- use a memory state trie instead of a disk state trie when replaying -> much faster
- can discard, write, resume blocks
This makes replaying the current chain having 50k blocks possible in about 30' on a fast machine.
=> Work on db replay

byzcoin/wallet/main.go, byzcoin/wallet/test.sh
This PR only applies 'cl.UseNode' in the case '-multi' is used.
For simple transfers, two nodes are chosen randomly, thus avoiding
a failing transfer if one node is down.
=> Improve behaviour when nodes are down

byzcoin/contracts/value.go, byzcoin/messages.go, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/contracts/coin-instance.ts, external/js/cothority/src/byzcoin/contracts/value-instance.ts, external/js/cothority/src/personhood/credentials-instance.ts, external/js/cothority/src/personhood/spawner-instance.ts, personhood/contracts/contract_popparty.go, personhood/contracts/contract_ropasci.go, personhood/contracts/contract_spawner.go, personhood/contracts/contract_spawner_test.go
Before only some contracts allowed for preID additions. Now all contracts
supported by the spawner-contract have preID support.
=> Add more preID derives

calypso/csadmin/clicontracts/lts.go, calypso/csadmin/commands.go, calypso/csadmin/main.go, calypso/service.go
When creating a new LTS instance on byzcoin, the roster used for the re-encryption can be different from the roster used by byzcoin.
This PR adds the possibility to `csadmin` to indicate a different roster. It also contacts the correct set of nodes for the different operations.
=> Lts roster

external/js/cothority/package-lock.json, external/js/cothority/package.json
Using new kyber
Ran npm audit fix
Jumping the 3.4.5 version, which was never published. One of the previous commit already changed the version from 3.4.4 to 3.4.5, but it was not ready. So going directly to 3.4.6.
Depends on #2298 #2299
=> Publish cothority 3.4.6

libtest.sh
In `libtest.sh`'s functions `testGrep()` and `testFGrep()`, unlike the other `test*Grep()`, the output is not displayed when the grep fails. As it is useful for debugging, this PR makes them all uniform.
=> test{F,}Grep(): display output when failing

bevm/bevm_client.go, bevm/database_byz.go
Improved the following two steps in bevmclient:
- use GetProofFromLatest for more succint, but still validatable proofs
- don't verify the proof twice: GetProof.* already verifies the proof
=> Speedup BEVMClient

external/js/cothority/package.json, external/js/cothority/src/darc/darc.ts
One of the imports in cothority has been using 'crypto', which
makes it fail when used. Replaced with 'crypto-browserify'.
=> Use crypto-browserify

byzcoin/service.go
Also print the paths to the errors using %+v format.
=> Add more information to warnings

byzcoin/messages.go, personhood/contracts/contract_spawner.go, personhood/contracts/contract_spawner_test.go
The previous spawner contract didn't allow updating of coins that haven't
been set before.
This PR adds a new byzcoin-version to correctly ignore previous transactions
that failed, so that replay still works.
=> Correctly update spawner contract

external/js/cothority/src/byzcoin/byzcoin-rpc.ts
Makes verify being respected when calling ByzCoinRPC.getProofFromLatest
=> Propagate verify argument

byzcoin/service.go, byzcoin/struct.go, byzcoin/struct_test.go
- Background calculation of stateChangeStorage - else it takes 90s on startup
- Only calculate the scs once in byzcoin/service.go
=> stateChangeStorage background calculation

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/byzcoin/byzcoin-rpc.spec.ts, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, skipchain/struct.go
The first call to ByzCoinRPC.instanceObservable was too late, making an eventual
recovery in ByzCoinRPC.getUpdate impossible.
ByzCoinRPC.getUpdate can fail if a block has been created but not yet sent to
the client. Now it waits for a confirmation of a new block and then retries
to get the updates.
=> Re-arrange block updates and wait for new block

ftcosi/simulation/protocol.go, messaging/propagate.go
The propagation protocol uses a tree, but it does not handle failing nodes.
Change the tree to a start-communication and fix an off-by-one error.
Also removes a debug-option from ftcosi.
=> Fix propagation protocol

bevm/api.go, bevm/bevmclient/cmd_imp.go, bevm/bevmclient/test.sh, bevm/service.go, bevm/service_test.go, external/js/cothority/spec/bevm/client.spec.ts, external/js/cothority/src/bevm/client.ts
These changes make the mechanism symmetrical to how arguments are passed to view methods, transactions or contract deployments: it uses strings to encode numbers with a large range (such as `uint256`), so as to preserve precision. The client can decide how to handle the string, e.g. in JavaScript it can be converted to a `BigInt` or a `Long`.
Closes c4dt/TODO#161
---
=> Handle large numeric return values in view method calls

Makefile, byzcoin/service.go, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/proto/requests.ts
If byzcoin.GetUpdates is called while a block is confirmed, it might be that the block
is already in the database, but the state is not updated yet.
This PR locks the mutex to make sure this does not happen during byzcoin.GetUpdates.
=> Removes a race in byzcoin.GetUpdates

external/js/kyber/package-lock.json, external/js/kyber/package.json
As js/kyber exposes some BN types, it needs to have its type definition. Having it in devs deps doesn't publihs it alongside it. Moving it to normal deps should help.
=> js/kyber: mv bn.js to deps

byzcoin/RosterChange.md, byzcoin/service.go, byzcoin/service_test.go, byzcoin/struct.go, byzcoin/viewchange_test.go, messaging/propagate.go
This are different things I found when working on rollup:
- typo in byzcoin/RosterChange.md
- byzcoin/Service.AddTransaction need for checking if the node is closing (less test-failures)
- byzcoin/Service.catchupAll iterating over all nodes to get the latest chain
- byzcoin/*_test.go simplifications and more stability for some tests
- messaging/propagate.go use a start propagation instead of a tree propagation, as the latter cannot handle failures
=> Backporting some of the rollup work

byzcoin/api.go, byzcoin/bcadmin/clicontracts/deferred.go, byzcoin/bcadmin/clicontracts/name.go, byzcoin/bcadmin/clicontracts/value.go, byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, byzcoin/bcadmin/lib/utils.go, byzcoin/bcadmin/main.go, byzcoin/proof_test.go, byzcoin/rostsimul.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/statetrie_test.go, byzcoin/struct.go, byzcoin/tx_pipeline.go, byzcoin/viewchange.go, byzcoin/viewchange/viewchange.go, byzcoin/wallet/main.go
To make sure the upcoming rollup-protocol branch is correct, I'm using
staticcheck from https://github.com/dominikh/go-tools .
This pass is over the master branch before the rollup-protocol, so that I
have to consider only the errors shown by the rollup-protocol branch.
Currently, staticcheck complains about two things that I didn't fix here:
- `blscosi` is deprecated - but I don't want to change the consensus-protocol at this stage
- unused methods when using `t.Skip` - so this is kind of right, but still didn't fix
=> Cleaning up using staticcheck

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/bevm/bevm-instance.spec.ts, external/js/cothority/src/bevm/bevm-instance.ts, external/js/cothority/src/bevm/index.ts
The change of library brings back support of the [ABIEncoderV2](https://solidity.readthedocs.io/en/v0.7.0/layout-of-source-files.html#abiencoderv2) (arbitrarily nested arrays and structs).
Closes #2350
=> Use @ethersproject/abi instead of ethereumjs-abi

external/js/cothority/spec/bevm/contract.spec.ts, external/js/cothority/src/bevm/bevm-instance.ts
This PR brings some improvements to the TypeScript BEvm code:
* Allow to pass an empty bytecode when creating a contract, for client code that only uses existing contract instances but don't need to deploy them.
* Factor EVM call data encoding and decoding.
* Add checks and better error handling.
=> BEvm TS improvements

go.mod, go.sum
Kyber's signature verification was potentially allowing malleable signatures with certain public keys. This version disallows those keys.
The public ByzCoin chain still replays correctly with this change in place.
=> Update to Kyber v3.0.13.

byzcoin/service.go, cosi/service/cosi.go, go.mod, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
Both urfave/cli and satori/uuid are now available as go-modules.
=> Remove two gopkg.in

external/js/cothority/package.json, external/js/cothority/src/log.ts
There was a superfluous buffer-import in log.ts which might confuse stackblitz. Also bumps cothority-version.
=> Don't import buffer

external/js/cothority/package.json, external/js/cothority/src/byzcoin/byzcoin-rpc.ts, external/js/cothority/src/byzcoin/proto/requests.ts
The calls to recover different instance versions from byzcoin have not been implemented
in the @dedis/cothority library.
This PR adds all the necessary calls to recover older versions of the instances.
=> Adding GetInstanceVersion calls

byzcoin/api_test.go, byzcoin/bctest.go, byzcoin/contract_darc_test.go, byzcoin/contracts/contract_deferred_test.go, byzcoin/service_test.go, byzcoin/statereplay_test.go, byzcoin/statetrie_test.go, byzcoin/streaming_test.go, byzcoin/transaction_test.go, byzcoin/viewchange_test.go
This PR makes a nicer BCTest structure that can be used in the different tests.
Its main purpose was to have a correct 'CloseAll' method that waits for all
activity to stop.
But finally it also cleans up a lot of trailing cruft in different tests.
The goal is to have a BCTest structure that can also be used by other modules.
For this reason BCTest is exported in the main package.
For any idea how to make this cleaner, comments are welcome :)
Ran the tests from #2387 in a loop here:
https://travis-ci.com/github/dedis/cothority/jobs/394084093
https://travis-ci.com/github/dedis/cothority/builds/187765748
Closes #2387
=> Extract BCTest

byzcoin/viewchange.go, byzcoin/viewchange_test.go
The Basic3 test runs 10 nodes, then stops 3, and waits for a view-change by the
remaining 7 nodes. This needs a lot of messages, and some time. While locally
it ran all right, on Jenkins it failed for two reasons:
1. the view-change block took too long to be verified, so it failed
2. sometimes view-change request messages got lost
This PR fixes it like this:
1. Increase the PropagationInterval for the view-change tests
2. Re-send view-change request message after a random delay between
[PropagationInterval/2..PropagationInterval]
=> Making TestViewChange_Basic3 working on Jenkins

unit_test.sh
Adds `DEBUG_TIME=true` and the current testing directory to the jenkins-test, to better debug why it's failing on the main test.
=> Add debug timing

Makefile, external/docker/Dockerfile, external/docker/Makefile
Under MacOSX, the docker-test image doesn't contain the bevm contract, which makes it
impossible to run all tests in external/js/cothority.
This PR uses golang-docker to create the docker-test image, so that also under MacOSX
all tests from external/js/cothority can be run.
=> Use golang-docker to create docker-test

external/js/cothority/CHANGELOG.md, external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/spec/helpers/bctest.ts, external/js/cothority/spec/support/historyObs.ts, external/js/cothority/spec/support/jasmine.json, external/js/cothority/spec/tsconfig.json, external/js/cothority/spec/v2/coin-inst.spec.ts, external/js/cothority/spec/v2/darc-inst.spec.ts, external/js/cothority/src/bevm/bevm-instance.ts, external/js/cothority/src/byzcoin/client-transaction.ts, external/js/cothority/src/v2/README.md, external/js/cothority/src/v2/byzcoin/contracts/coinContract.ts, external/js/cothority/src/v2/byzcoin/contracts/coinInst.ts, external/js/cothority/src/v2/byzcoin/contracts/darcContract.ts, external/js/cothority/src/v2/byzcoin/contracts/darcInsts.ts, external/js/cothority/src/v2/byzcoin/contracts/index.ts, external/js/cothority/src/v2/byzcoin/index.ts, external/js/cothority/src/v2/byzcoin/transactionBuilder.ts, external/js/cothority/src/v2/byzcoin/util.ts, external/js/cothority/tsconfig.json
The previous requests and instances were difficult to use for multi-instruction transactions.
Also, they didn't use the new Observable interface given by ByzCoin.
This PR adds a v2/ directory with some soon-to-be stable version of Darc and Coin instances.
Every instance can now be created as a BehaviorSubject that updates automatically whenever
a new block is available.
This allows to program a much more reactive programming of the user-interface: instead of
polling for new values, the UI can subscribe to the BehaviorSubjects and be updated
whenever something changes.
In the long run, other contracts should also find their way into byzcoin/v2.
Depends on #2392
=> Adding new v2-byzcoin requests

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/src/network/websocket.ts
As the dedis/cothority is not only used in the browser, but also in node
and nativescript, URL cannot be used reliably.
This PR replaces URL with the url-parse implementation.
=> Replace URL with url-parse

external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/spec/network/websocket-test-adapter.ts, external/js/cothority/src/network/websocket.ts
Took https://tools.ietf.org/html/rfc6455 to convert the error-codes of the
websocket to text.
Closes #2396
=> Convert websocket error-codes to text

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/src/byzcoin/beautifier/config.ts, external/js/cothority/src/byzcoin/beautifier/darc.ts, external/js/cothority/src/byzcoin/beautifier/default.ts, external/js/cothority/src/byzcoin/beautifier/index.ts, external/js/cothority/src/byzcoin/beautifier/utils.ts, external/js/cothority/src/byzcoin/client-transaction.ts, external/js/cothority/src/byzcoin/config.ts
This PR implements a `instruction.getArranged()` function on @cothority/byzcoin that returns a general-purpose JSON representation of an instruction. This representation is contract aware in the sense that arguments should have a meaningful string representation, based on each different contract.
The JSON has the following structure:
```
*  {
*      status: 0 | 1,   // Non-zero means an error occured
*      type: "spawn|invoke|delete|UNKNOWN",
*      contract: "config|darc|...",
*      args: [
*          {
*              "name": "<NAME>",
*              "value": "<VALUE>",    // Arg value or its summary
*              "full": "<FULL VALUE>" // Optional. useful if the argument
*                                     // have a very long representation.
*          }
* …
```
=> @cothority/byzcoin meaningful instruction print

byzcoin/api_test.go, byzcoin/service.go, byzcoin/service_test.go, byzcoin/streaming.go, byzcoin/struct.go, byzcoin/viewchange.go, byzcoin/viewchange_test.go
The use of mutexes in byzcoin.Service got somehow out of hand.
This PR cleans up the use of 'Service.close' and 'Service.working' by
adding two new structures that do all the locking.
It also contains minimal changes to the tests to make them pass.
For review: can you please look at the two structures `runSingleWG` and `tasksWG` in `byzcoin/struct.go` and tell me if they look OK? It simplifies a lot the locking in the `byzcoin.Service`. I hope the tests are relevant ;)
I tried to think of how to merge the two
=> Cleaning up mutexes in byzcoin.Service

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, skipchain/struct.go
This PR improves a bit the output of the 'bcadmin db check' command by
removing superfluous messages and differentiating between warnings and
errors.
=> Improve db checking

external/js/cothority/package.json, external/js/cothority/spec/helpers/bctest.ts, external/js/cothority/spec/network/connection.spec.ts, external/js/cothority/spec/skipchain/skipchain-rpc.spec.ts, external/js/cothority/src/network/websocket.ts
Clearing the timeout doesn't set it back. This would make the websocket connection have a connection error (coming from Onet I guess..?) instead of the expected timeout.
Also added a `npm run watch` to automatically compile files on changes.
Fixes https://github.com/dedis/columbus-united/issues/40
=> Fixes timeout in Websocket

external/js/cothority/src/skipchain/skipchain-rpc.ts
=> Adds an optional acceptForeigner flag

status/status.go
Adds a command that initiates ConnectivityCheck every `interval`
and serves the results in the form of prometheus metrics.
=> status: allow exporting ConnectivityCheck results over HTTP

external/js/cothority/spec/byzcoin/byzcoin-rpc.spec.ts, external/js/cothority/src/byzcoin/byzcoin-rpc.ts
When a new byzcoinrpc is instantiated, it uses a LocalCache if no DB is given.
Closes #2416
=> Use LocalCache per default

byzcoin/service_test.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go, skipchain/struct_test.go
Previously the GetByID was only available as a service-endpoint, but as it is
a handy method in general, this PR moves it to the SkipchainDB as `GetFullProof`,
which can do much more.
Also contains a fix to SkipBlock.pathForIndex
=> Adding SkipchainDB.GetProofFromIndex

scmgr/app.go, skipchain/msgs.go, skipchain/skipchain.go, skipchain/skipchain_test.go, skipchain/struct.go
The current chain optimization is badly defined, as you need to give it a block,
but for some blocks the optimization will always fail, as the nodes will not
accept the new forward-links.
This PR re-defines the chain optimization:
- if given a skipchain-ID it optimizes the route from the genesis to the latest block
- if given a random skipblock-ID, it optimizes that block only
This will allow to crawl through all blocks and ask an optimization for every
block that is lacking forward-links.
Depends on #2423
=> Fix chain optimization

byzcoin/service.go
This is (hopefully) the last place where additional buckets have been
created by error.
=> Fix creation of additional buckets

byzcoin/bcadmin/cmd_db.go, byzcoin/bcadmin/commands.go, skipchain/struct.go
The preivous merging behaviour in bcadmin was counter-intuitive and
potentially damaging to the stored global state.
This makes it clearer and simplifies the code.
=> Improved merging from backup-db

external/js/cothority/package-lock.json, external/js/cothority/package.json, external/js/cothority/src/network/websocket.ts
So, `url-parse` came back to bit my hand, first because `@types/url-parse` was missing yet the `URL` type was exposed, then because I wasn't able to *compile* some of its deps.. It was initially added because webpack doesn't deal well with "subdir imports" and that some platforms doesn't come with the same definition of `URL` (Node, NS, ...). I don't think that the Node target is needed anymore (correct me @nkcr) and we just removed the support for mobile/NS in omniledger. Let's remove (once again) `url-parse`.
I was thinking of finally fixing this webpack issue as a fallback plan, but if this PR is merged, I'll wait until an unfixable issue comes along. (Disclaimer: to fix webpack, I'll probably have to reorganise the whole import hierarchy)
=> js/cothority: rm url-parse

.github/workflows/lint_build_test.yaml, Makefile, bypros/browse/paginate/mod.go, bypros/proxy.go, byzcoin/service.go, byzcoin/statereplay.go
LLvl are used for debugging and should not be used in the final code.
Adds a test_llvl target to the Makefile.
=> Remove LLvl

PUBLISH.md, bevm/bevmclient/README.md, blscosi/simulation/simul.go, byzcoin/Contracts.md, byzcoin/README.md, byzcoin/RosterChange.md, calypso/protocol/doc.go, calypso/service.go, conode/README.md, cosi/simulation/simul.go, darc/README.md, doc.go, skipchain/skipchain_test.go
There are some `Master` references in the code, specifically in the `evoting` section, that I don't know if it's correct to replace them... @gnarula , any idea?
=> Move master branch to main branch

byzcoin/bcadmin/cmd_db.go
The `bcadmin db catchup` had an error where it looped forever if the latest node in the roster was down.
This PR fixes this corner-case.
=> Don't loop when latest node in roster is not responsive

byzcoin/api.go, byzcoin/api_test.go, byzcoin/bcadmin/main.go, byzcoin/service.go, personhood/phapp/main.go, personhood/service.go, personhood/service_test.go, personhood/user/builder.go, personhood/user/user.go, skipchain/skipchain.go
This is a collection of patches for byzcoin and skipchain:
- solve a race condition where the bftForwardLinkLevel0Ack has been called before bftForwardLinkLevel0 is done
- allow storing of new SkipBlocks in existing chains, even if a Client has been registered
- changing the byzcoin.Client.GetInstance method to also do the protobuf-decoding
- adding a byzcoin.Client.UpdateNodes in case some of the nodes didn't catch up
This has been tested in production and behaves nicer. Of course there are still some bugs left...
=> Refine byzcoin

personhood/email.go, personhood/service.go, personhood/service_test.go
Instead of using a hardcoded CC address, use the one from the registered user during setup.
=> Changing address for CC

personhood/user/builder.go, personhood/user/user.go
Corrected the following things to make it behave like the web-frontend:
- when adding a recovery to a new user, only add it to the 'evolve' rule of the signer-darc
- when recovering an existing user
- add the new darc using the admin-signer
- add the darc-ID to the recovered user with the ephemeral key as signer
=> Correctly recover users

darc/darc_test.go
Adds a test to the darcs for easy insert of a new identity.
=> Adding darc identity test for Pilar/DuoKey

personhood/service_test.go, personhood/user/user.go, personhood/user/user_test.go
The evolve-instruction was badly calculated, and thus only one recovery was
possible.
Unfortunately all accounts with a recovery cannot be recovered :(
=> Fix multiple recoveries

blscosi/protocol/protocol.go, blscosi/protocol/protocol_test.go, blscosi/protocol/sub_protocol.go, byzcoinx/byzcoinx_test.go, messaging/propagate.go
This PR does the following:
- increase the number of subleaders to sqrt(roster.len - 1), according
to the OmniLedger paper
- put all calls to Send in the blscosi protocol in a go-routine, so that
a blocking subleader doesn't stop the protocol
=> Fix subleader handling

byzcoin/bctest.go, byzcoin/service.go, byzcoin/service_test.go, darc/darc.go, darc/darc_test.go, external/js/cothority/spec/byzcoin/darc-instance.spec.ts, external/js/cothority/src/darc/identity-tsm.ts, external/js/cothority/src/darc/identity-wrapper.ts, external/js/cothority/src/darc/index.ts, external/js/cothority/tsconfig.json
The first PR to implement the IdentityTSM used a (Un)MarshalBinary that was not compatible
with the protobuf-encoding we were doing.
This PR contains also some tests used to discover this discrepancy.
Because there is no TSM-identity stored in binary form, this should not break anything.
=> Change the encoding of the IdentityTSM

dedis-cothority.toml
Now that the other nodes are not used anymore in login.c4dt.org, also remove them from the dedis-cothority.toml file
=> Removing non-C4DT nodes
